TrackingManager Class Reference
Manager responsible for keeping track of game entity positions.
#include <TrackingManager.h>
Public Member Functions
TrackingManager ()
Constructor for Tracking manager.
void manage (ActionData &action_data_container)
Manage function allowing the position of all Trackable entities to be kept.
void addNewEntity (std::weak_ptr< Trackable > new_entity)
Add Trackable-type shared_ptr's to the TrackingManagers internal data members.
const float getP1PositionX ()
Return x position of P1 Tank.
const float getP1PositionY ()
Return y position of P1 Tank.
const float getP1Rotation ()
Return rotation of P1 Tank.
const float getP2PositionX ()
Return x position of P2 Tank.
const float getP2PositionY ()
Return y position of P2 Tank.
const float getP2Rotation ()
Return rotation of P2 Tank.
const std::vector< float > & getTurretPositionsX ()
Return x position of all Turrets.
const std::vector< float > & getTurretPositionsY ()
Return y position of all Turrets.
const std::vector< float > & getTurretRotations ()
Return rotation of all Turrets.
virtual ~TrackingManager ()
Destructor for Tracking manager.
Private Member Functions
void removeGarbage ()
Remove all deleted entities from _trackables.
Private Attributes
std::vector< std::weak_ptr
*
< Trackable > > _trackables
Pointers to all trackable entities within the game world.
GeometryEngine _geometry_engine
Helper Engine.
float _p1Rotation
Player 1 tank current rotation.
float _p1PositionX
Player 1 tank current x position.
float _p1PositionY
Player 1 tank current y position.
rect_corners _p1BoundingBox
Player 1 Bounding box.
float _p2Rotation
Player 2 tank current rotation.
float _p2PositionX
Player 2tank current x position.
float _p2PositionY
Player 2 tank current y position.
rect_corners _p2BoundingBox
Player 2 Bounding box.
std::vector< float > _turretPositionsX
All of the Turrets current x positions.
std::vector< float > _turretPositionsY
All of the Turrets current y positions.
std::vector< float > _turretRotations
all of the Turrets current Rotations
Detailed Description
Manager responsible for keeping track of game entity positions.
Definition at line 22 of file TrackingManager.h.
Constructor & Destructor Documentation
TrackingManager::TrackingManager ()
Constructor for Tracking manager.
Constructor that initialises the _geometry_engine.
Definition at line 15 of file TrackingManager.cpp.
                                :
    _geometry_engine()
{
}
TrackingManager::~TrackingManager () [virtual]
Destructor for Tracking manager.
Definition at line 21 of file TrackingManager.cpp.
{
}
Member Function Documentation
void TrackingManager::addNewEntity (std::weak_ptr< Trackable > new_entity)
Add Trackable-type shared_ptr's to the TrackingManagers internal data members.
Definition at line 196 of file TrackingManager.cpp.
References _trackables.
Referenced by Game::addTrackable(), and TEST().
{
    _trackables.push_back(new_entity);
}
const float TrackingManager::getP1PositionX ()
Return x position of P1 Tank.
Definition at line 147 of file TrackingManager.cpp.
References _p1PositionX.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _p1PositionX;
}
const float TrackingManager::getP1PositionY ()
Return y position of P1 Tank.
Definition at line 155 of file TrackingManager.cpp.
References _p1PositionY.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _p1PositionY;
}
const float TrackingManager::getP1Rotation ()
Return rotation of P1 Tank.
Definition at line 164 of file TrackingManager.cpp.
References _p1Rotation.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _p1Rotation;
}
const float TrackingManager::getP2PositionX ()
Return x position of P2 Tank.
Definition at line 172 of file TrackingManager.cpp.
References _p2PositionX.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _p2PositionX;
}
const float TrackingManager::getP2PositionY ()
Return y position of P2 Tank.
Definition at line 180 of file TrackingManager.cpp.
References _p2PositionY.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _p2PositionY;
}
const float TrackingManager::getP2Rotation ()
Return rotation of P2 Tank.
Definition at line 188 of file TrackingManager.cpp.
References _p2Rotation.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _p2Rotation;
}
const std::vector< float > & TrackingManager::getTurretPositionsX ()
Return x position of all Turrets.
Definition at line 122 of file TrackingManager.cpp.
References _turretPositionsX.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _turretPositionsX;
}
const std::vector< float > & TrackingManager::getTurretPositionsY ()
Return y position of all Turrets.
Definition at line 131 of file TrackingManager.cpp.
References _turretPositionsY.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _turretPositionsY;
}
const std::vector< float > & TrackingManager::getTurretRotations ()
Return rotation of all Turrets.
Definition at line 139 of file TrackingManager.cpp.
References _turretRotations.
Referenced by Game::addNewWorldEntity().
{
    return _turretRotations;
}
void TrackingManager::manage (ActionData & action_data_container)
Manage function allowing the position of all Trackable entities to be kept.
This includes the tracking of the tanks by the turrets. The positions are obtained and then passed to the _geometry_engine where comparisons are made.
Parameters
action_data_container :: Will set turret file in this container if needs be
Definition at line 31 of file TrackingManager.cpp.
References _geometry_engine, _p1BoundingBox, _p1PositionX, _p1PositionY, _p1Rotation, _p2BoundingBox, _p2PositionX, _p2PositionY, _p2Rotation, _trackables, _turretPositionsX, _turretPositionsY, _turretRotations, GeometryEngine::calculateVectorLength(), GeometryEngine::isInLineOfFire(), p1_tank, p2_tank, removeGarbage(), ActionData::setTurretFire(), and turret.
Referenced by Game::runAllManagers(), and TEST().
{
    removeGarbage();
    //Clear position vectors for new cycle
    _turretPositionsX.clear();
    _turretPositionsY.clear();
    _turretRotations.clear();
    auto _trackables_itterator = _trackables.begin();
    for(; _trackables_itterator != _trackables.end(); _trackables_itterator++)
    {
        //Convert Itterator to Weak Pointer
        std::weak_ptr<Trackable> entity_track_wp = (*_trackables_itterator);
        //Convert Weak Pointer to Shared Pointer
        std::shared_ptr<Trackable> entity_track_sp = entity_track_wp.lock();
        //Check to see if entity still exists
            if(entity_track_sp->getType() == p1_tank)
            {
                _p1PositionX = entity_track_sp->getPositionX();
                _p1PositionY = entity_track_sp->getPositionY();
                _p1Rotation = entity_track_sp->getOrientation();
                _p1BoundingBox = entity_track_sp->getTrackingBoundingBox();
            }
            else if(entity_track_sp->getType() == p2_tank)
            {
                _p2PositionX = entity_track_sp->getPositionX();
                _p2PositionY = entity_track_sp->getPositionY();
                _p2Rotation = entity_track_sp->getOrientation();
                _p2BoundingBox = entity_track_sp->getTrackingBoundingBox();
            }
            else if(entity_track_sp->getType() == turret)
            {
                //Temp variables
                float temp_Turret_Xpos = entity_track_sp->getPositionX();
                float temp_Turret_Ypos = entity_track_sp->getPositionY();
                float temp_Turret_Rotation = entity_track_sp->getOrientation();
                auto temp_Turret_BoundingBox = entity_track_sp->getTrackingBoundingBox();
                //See if turrets are viewing (tank1 or tank2) and it is in proximity
                //Using case gaurds
                if((_geometry_engine.isInLineOfFire(temp_Turret_Rotation,
      temp_Turret_BoundingBox, _p1BoundingBox, temp_Turret_Ypos,
      _p1PositionY)) &&
                   (_geometry_engine.calculateVectorLength(
      temp_Turret_Xpos,temp_Turret_Ypos,_p1PositionX,_p2PositionY) < 400.0))
                {
                    action_data_container.setTurretFire();
                    _turretPositionsX.push_back(temp_Turret_Xpos);
                    _turretPositionsY.push_back(temp_Turret_Ypos);
                    _turretRotations.push_back(temp_Turret_Rotation);
                }
                if((_geometry_engine.isInLineOfFire(temp_Turret_Rotation,
      temp_Turret_BoundingBox, _p2BoundingBox, temp_Turret_Ypos,
      _p2PositionY)) &&
                   (_geometry_engine.calculateVectorLength(
      temp_Turret_Xpos,temp_Turret_Ypos,_p2PositionX,_p2PositionY) < 400.0))
                {
                    action_data_container.setTurretFire();
                    _turretPositionsX.push_back(temp_Turret_Xpos);
                    _turretPositionsY.push_back(temp_Turret_Ypos);
                    _turretRotations.push_back(temp_Turret_Rotation);
                }
            }
    }//For
}//function
void TrackingManager::removeGarbage () [private]
Remove all deleted entities from _trackables.
Clear all deleted pointers.
Definition at line 98 of file TrackingManager.cpp.
References _trackables.
Referenced by manage().
{
    //Clear all deleted entities from the _trackables vector
    auto removal = _trackables.begin();
    for (; removal != _trackables.end();)
    {
        std::weak_ptr<Trackable> removal_wp = (*removal);
        //Convert weak_ptr to shared_ptr
        std::shared_ptr<Trackable> removal_sp = removal_wp.lock();
        //Test if pointer still valid
        if(removal_sp)
        {
            removal++;
        }
        else
        {
            _trackables.erase(removal);
        }
    }// if
}//function
Member Data Documentation
GeometryEngine TrackingManager::_geometry_engine [private]
Helper Engine.
Definition at line 63 of file TrackingManager.h.
Referenced by manage().
rect_corners TrackingManager::_p1BoundingBox [private]
Player 1 Bounding box.
Definition at line 72 of file TrackingManager.h.
Referenced by manage().
float TrackingManager::_p1PositionX [private]
Player 1 tank current x position.
Definition at line 68 of file TrackingManager.h.
Referenced by getP1PositionX(), and manage().
float TrackingManager::_p1PositionY [private]
Player 1 tank current y position.
Definition at line 70 of file TrackingManager.h.
Referenced by getP1PositionY(), and manage().
float TrackingManager::_p1Rotation [private]
Player 1 tank current rotation.
Definition at line 66 of file TrackingManager.h.
Referenced by getP1Rotation(), and manage().
rect_corners TrackingManager::_p2BoundingBox [private]
Player 2 Bounding box.
Definition at line 81 of file TrackingManager.h.
Referenced by manage().
float TrackingManager::_p2PositionX [private]
Player 2tank current x position.
Definition at line 77 of file TrackingManager.h.
Referenced by getP2PositionX(), and manage().
float TrackingManager::_p2PositionY [private]
Player 2 tank current y position.
Definition at line 79 of file TrackingManager.h.
Referenced by getP2PositionY(), and manage().
float TrackingManager::_p2Rotation [private]
Player 2 tank current rotation.
Definition at line 75 of file TrackingManager.h.
Referenced by getP2Rotation(), and manage().
std::vector<std::weak_ptr<Trackable> > TrackingManager::_trackables [private]
Pointers to all trackable entities within the game world.
Definition at line 57 of file TrackingManager.h.
Referenced by addNewEntity(), manage(), and removeGarbage().
std::vector<float> TrackingManager::_turretPositionsX [private]
All of the Turrets current x positions.
Definition at line 84 of file TrackingManager.h.
Referenced by getTurretPositionsX(), and manage().
std::vector<float> TrackingManager::_turretPositionsY [private]
All of the Turrets current y positions.
Definition at line 86 of file TrackingManager.h.
Referenced by getTurretPositionsY(), and manage().
std::vector<float> TrackingManager::_turretRotations [private]
all of the Turrets current Rotations
Definition at line 88 of file TrackingManager.h.
Referenced by getTurretRotations(), and manage().
The documentation for this class was generated from the following files:
TrackingManager.h
TrackingManager.cpp