StopWatch Class Reference
Responsible for keeping time.
#include <StopWatch.h>
Public Member Functions
StopWatch ()
Constuctor that initialises private class variables.
void start ()
Starts the stopwatch.
void stop ()
Stops the stopwatch.
void lap ()
Gives the lap time.
void reset ()
Resets the stopwatch.
bool isRunning ()
Check if the stopwatch is running.
double getTimerValue ()
Gets the time since the stopwatch started.
Private Member Functions
double getProcessTime ()
Returns the amount of time in seconds.
Private Attributes
double _start
Holds the system time from when the stopwatch starts.
double _stop
Holds the stopped or total clock running time.
bool _running
Used to tell if the stopwatch is running.
Detailed Description
Responsible for keeping time.
Definition at line 16 of file StopWatch.h.
Constructor & Destructor Documentation
StopWatch::StopWatch ()
Constuctor that initialises private class variables.
Definition at line 17 of file StopWatch.cpp.
                    :
    _stop(0.0),
    _start(0.0),
    _running(false)
{}
Member Function Documentation
double StopWatch::getProcessTime () [private]
Returns the amount of time in seconds.
The return time is the tim ethat has passed since the process (i.e. the program) started executing
Returns
double
Definition at line 71 of file StopWatch.cpp.
Referenced by getTimerValue(), lap(), start(), and stop().
{
    clock_t time = clock();
    return static_cast<double>(time)/CLOCKS_PER_SEC;
}
double StopWatch::getTimerValue ()
Gets the time since the stopwatch started.
Returns
double
Definition at line 90 of file StopWatch.cpp.
References _start, getProcessTime(), and isRunning().
Referenced by GameStateManager::manage(), and GameStateManager::timeRunOut().
{
    if (isRunning())
        return getProcessTime() - _start;
}
bool StopWatch::isRunning ()
Check if the stopwatch is running.
Returns
bool
Definition at line 80 of file StopWatch.cpp.
References _running.
Referenced by getTimerValue(), lap(), GameStateManager::manage(), reset(), stop(), and GameStateManager::timeRunOut().
{
    if (_running)
        return true;
    return false;
}
void StopWatch::lap ()
Gives the lap time.
Definition at line 47 of file StopWatch.cpp.
References _start, getProcessTime(), and isRunning().
{
    if (isRunning())
        std::cout << "Lap: " << (getProcessTime() - _start) << std::endl;
}
void StopWatch::reset ()
Resets the stopwatch.
Definition at line 57 of file StopWatch.cpp.
References _stop, isRunning(), and start().
Referenced by GameStateManager::timeRunOut().
{
    if (isRunning())
    {
        _stop = 0.0;
        start();
    }
}
void StopWatch::start ()
Starts the stopwatch.
Set the running status to true.
Definition at line 26 of file StopWatch.cpp.
References _running, _start, _stop, and getProcessTime().
Referenced by GameStateManager::GameStateManager(), GameStateManager::manage(), reset(), and GameStateManager::timeRunOut().
{
    _start = getProcessTime() - _stop;
    _running = true;
}
void StopWatch::stop ()
Stops the stopwatch.
Set the running status to false and gets the stop time.
Definition at line 35 of file StopWatch.cpp.
References _running, _start, _stop, getProcessTime(), and isRunning().
Referenced by GameStateManager::manage().
{
    if (isRunning())
    {
        _stop = getProcessTime() - _start;
        _running = false;
    }
}
Member Data Documentation
bool StopWatch::_running [private]
Used to tell if the stopwatch is running.
Definition at line 32 of file StopWatch.h.
Referenced by isRunning(), start(), and stop().
double StopWatch::_start [private]
Holds the system time from when the stopwatch starts.
Definition at line 28 of file StopWatch.h.
Referenced by getTimerValue(), lap(), start(), and stop().
double StopWatch::_stop [private]
Holds the stopped or total clock running time.
Definition at line 30 of file StopWatch.h.
Referenced by reset(), start(), and stop().
The documentation for this class was generated from the following files:
StopWatch.h
StopWatch.cpp