Missile Class Reference
Missile Class implementation.
#include <Missile.h>
Public Member Functions
Missile (float positionX, float positionY, float rotation, entity_type missileOwner)
Missile object constructor.
virtual const entity_type & getType () const
Return the ownership and type of the Missile entity.
virtual void moveForward ()
Forward movement for a missile entity.
virtual void moveBackward ()
Backward movement for a missile entity.
virtual void rotateLeft ()
Left rotation for a missile entity.
virtual void rotateRight ()
Right rotation for a missile entity.
virtual const rect_corners & getBoundingBox ()
Provide the bounding box for the missile entity.
virtual const rect_corners & getAlignedBoundingBox ()
Get Axis Aligned bounding box of entity.
virtual const int setBlocked (const blocked_status obstruction_type)
Instruct the missile entity that it cannot move along its trajectory.
virtual void setUnblocked ()
Instruct the missile entity that it can move.
virtual void setCollided ()
Instruct the missile entity that it has collided with another object.
virtual const blocked_status isBlocked ()
Determine the blocked state of the missile entity.
virtual bool const isDeleted ()
Boolean state of the missile entity's life.
virtual const float getDrawPositionX ()
Retrieve the missile x Position.
virtual const float getDrawPositionY ()
Retrieve the missile y Position.
virtual const float getDrawRotation ()
Receive the missile rotation.
virtual void setMovementDirection (const movement_direction Movement_input)
Set the movement direction of the entity.
virtual ~Missile ()
Missile object destructor.
Private Attributes
blocked_status _blockedStatus
Movability of the Missile entity: 1 for blocked, 0 for free.
bool _collidedStatus
Collision state of the Missile Entity: 1 for collided, 0 for not.
float _rotation
The angle of rotation for the Missile entity.
Orientation _missile
SFML Co-ordinate system for the Missile.
entity_type _type
Enumeration type defining the Missile.
SpriteDimensions _sprite_dimensions
Missile Sprite dimensions.
int _rebound_lives
Defines the number of times the Missile can rebound off barriers.
Additional Inherited Members
Detailed Description
Missile Class implementation.
Entity Class representing the Missile in the game world.
This class possesses multiple interfaces for interaction with various managers and forms part of the basic model entities
Definition at line 26 of file Missile.h.
Constructor & Destructor Documentation
Missile::Missile (float positionX, float positionY, float rotation, entity_type missileOwner)
Missile object constructor.
Definition at line 15 of file Missile.cpp.
References _blockedStatus, _collidedStatus, _missile, _rebound_lives, _sprite_dimensions, _type, Orientation::getOriginX(), Orientation::getOriginY(), Orientation::getRotation(), SpriteDimensions::missile_sprite_x, SpriteDimensions::missile_sprite_y, p1_missile, p2_missile, Orientation::setHeight(), Orientation::setWidth(), turret_missile, and unblocked.
                                                                                          :
    _rotation(rotation),
    _type(missileOwner),
    _missile(positionX,positionY,0,0,rotation, false),
    _sprite_dimensions()
{
    //Error input checking
    if (_missile.getOriginX() < 0) throw
      InvalidConstructorArgumentsMissile();
    if (_missile.getOriginY() < 0) throw
      InvalidConstructorArgumentsMissile();
    if (_missile.getRotation() < 0) throw
      InvalidConstructorArgumentsMissile();
    if ((_type != p1_missile) && (_type != p2_missile) && (
      _type != turret_missile)) throw
      InvalidConstructorArgumentsMissile();
    _missile.setWidth(_sprite_dimensions.
      missile_sprite_x);
    _missile.setHeight(_sprite_dimensions.
      missile_sprite_y);
    _blockedStatus = unblocked;
    _collidedStatus = 0;
    _rebound_lives = 7;
}
Missile::~Missile () [virtual]
Missile object destructor.
Definition at line 141 of file Missile.cpp.
{
    //Consider adding something here
}
Member Function Documentation
const rect_corners & Missile::getAlignedBoundingBox () [virtual]
Get Axis Aligned bounding box of entity.
Implements Collidable.
Definition at line 78 of file Missile.cpp.
References _missile, and Orientation::getAlignedGlobalBounds().
{
    return _missile.getAlignedGlobalBounds();
}
const rect_corners & Missile::getBoundingBox () [virtual]
Provide the bounding box for the missile entity.
Implements Collidable.
Definition at line 73 of file Missile.cpp.
References _missile, and Orientation::getGlobalBounds().
{
    return _missile.getGlobalBounds();
}
const float Missile::getDrawPositionX () [virtual]
Retrieve the missile x Position.
Retrieve the Missile x Position.
Implements Deletable.
Definition at line 116 of file Missile.cpp.
References _missile, and Orientation::getOriginX().
Referenced by TEST().
{
    return _missile.getOriginX();
}
const float Missile::getDrawPositionY () [virtual]
Retrieve the missile y Position.
Retrieve the Missile y Position.
Implements Deletable.
Definition at line 122 of file Missile.cpp.
References _missile, and Orientation::getOriginY().
Referenced by TEST().
{
    return _missile.getOriginY();
}
const float Missile::getDrawRotation () [virtual]
Receive the missile rotation.
Recieve the Missile rotation.
Implements Deletable.
Definition at line 129 of file Missile.cpp.
References _missile, and Orientation::getRotation().
Referenced by TEST().
{
    return _missile.getRotation();
}
const entity_type & Missile::getType () const [virtual]
Return the ownership and type of the Missile entity.
Implements Deletable.
Definition at line 36 of file Missile.cpp.
References _type.
Referenced by TEST().
{
    return _type;
}
const blocked_status Missile::isBlocked () [virtual]
Determine the blocked state of the missile entity.
Implements Movable.
Definition at line 104 of file Missile.cpp.
References _blockedStatus.
Referenced by TEST().
{
    return _blockedStatus;
}
const bool Missile::isDeleted () [virtual]
Boolean state of the missile entity's life.
Implements Deletable.
Definition at line 110 of file Missile.cpp.
References _collidedStatus.
Referenced by TEST().
{
    return _collidedStatus;
}
void Missile::moveBackward () [virtual]
Backward movement for a missile entity.
Implements Movable.
Definition at line 49 of file Missile.cpp.
References _missile, Movable::_missileMovementSpeed, _rotation, Orientation::move(), and PI.
Referenced by TEST().
{
    _missile.move(-_missileMovementSpeed*cos((
      _rotation*PI)/180.0),-_missileMovementSpeed*sin((
      _rotation*PI)/180.0));
}
void Missile::moveForward () [virtual]
Forward movement for a missile entity.
Implements Movable.
Definition at line 43 of file Missile.cpp.
References _missile, Movable::_missileMovementSpeed, _rotation, Orientation::move(), and PI.
Referenced by TEST().
{
    _missile.move(_missileMovementSpeed*cos((
      _rotation*PI)/180.0),_missileMovementSpeed*sin((
      _rotation*PI)/180.0));
}
void Missile::rotateLeft () [virtual]
Left rotation for a missile entity.
Implements Movable.
Definition at line 55 of file Missile.cpp.
References _missile, _rotation, Orientation::getRotation(), and Orientation::rotate().
Referenced by TEST().
{
    float rotationFactor = ((abs(_rotation-180)-90)*2);
    _missile.rotate(rotationFactor);
    _rotation = _missile.getRotation();
}
void Missile::rotateRight () [virtual]
Right rotation for a missile entity.
Implements Movable.
Definition at line 64 of file Missile.cpp.
References _missile, _rotation, Orientation::getRotation(), and Orientation::rotate().
{
    float rotationFactor = ((180-_rotation)*2);
    _missile.rotate(rotationFactor);
    _rotation = _missile.getRotation();
}
const int Missile::setBlocked (const blocked_status obstruction_type) [virtual]
Instruct the missile entity that it cannot move along its trajectory.
Implements Collidable.
Definition at line 84 of file Missile.cpp.
References _blockedStatus, and _rebound_lives.
Referenced by TEST().
{
    _blockedStatus = obstruction_type;
    _rebound_lives -= 1;
    return _rebound_lives;
}
void Missile::setCollided () [virtual]
Instruct the missile entity that it has collided with another object.
Implements Collidable.
Definition at line 98 of file Missile.cpp.
References _collidedStatus.
Referenced by TEST().
{
    _collidedStatus = 1;
}
void Missile::setMovementDirection (const movement_direction Movement_input) [virtual]
Set the movement direction of the entity.
Implements Movable.
Definition at line 135 of file Missile.cpp.
References _missile, and Orientation::setMoveDirection().
{
    _missile.setMoveDirection(Movement_input);
}
void Missile::setUnblocked () [virtual]
Instruct the missile entity that it can move.
Instruct the tank entity that it can move.
Implements Collidable.
Definition at line 92 of file Missile.cpp.
References _blockedStatus, and unblocked.
Referenced by TEST().
{
    _blockedStatus = unblocked;
}
Member Data Documentation
blocked_status Missile::_blockedStatus [private]
Movability of the Missile entity: 1 for blocked, 0 for free.
Definition at line 70 of file Missile.h.
Referenced by isBlocked(), Missile(), setBlocked(), and setUnblocked().
bool Missile::_collidedStatus [private]
Collision state of the Missile Entity: 1 for collided, 0 for not.
Definition at line 72 of file Missile.h.
Referenced by isDeleted(), Missile(), and setCollided().
Orientation Missile::_missile [private]
SFML Co-ordinate system for the Missile.
Definition at line 76 of file Missile.h.
Referenced by getAlignedBoundingBox(), getBoundingBox(), getDrawPositionX(), getDrawPositionY(), getDrawRotation(), Missile(), moveBackward(), moveForward(), rotateLeft(), rotateRight(), and setMovementDirection().
int Missile::_rebound_lives [private]
Defines the number of times the Missile can rebound off barriers.
Definition at line 82 of file Missile.h.
Referenced by Missile(), and setBlocked().
float Missile::_rotation [private]
The angle of rotation for the Missile entity.
Definition at line 74 of file Missile.h.
Referenced by moveBackward(), moveForward(), rotateLeft(), and rotateRight().
SpriteDimensions Missile::_sprite_dimensions [private]
Missile Sprite dimensions.
Definition at line 80 of file Missile.h.
Referenced by Missile().
entity_type Missile::_type [private]
Enumeration type defining the Missile.
Definition at line 78 of file Missile.h.
Referenced by getType(), and Missile().
The documentation for this class was generated from the following files:
Missile.h
Missile.cpp