ActionData Class Reference
#include <ActionData.h>
Public Member Functions
virtual void resetActionsInfo ()=0
Virtual void function, look to child for defenition.
virtual const actions_info & giveActionInfo () const =0
Provide the actions_info structure of a class.
virtual void resetTurretFire ()=0
Virtual void function, look to child for defenition.
virtual void setTurretFire ()=0
Virtual void function, look to child for defenition.
virtual void moveForwardP1 ()=0
Virtual void function, look to child for defenition.
virtual void moveBackwardP1 ()=0
Virtual void function, look to child for defenition.
virtual void rotateLeftP1 ()=0
Virtual void function, look to child for defenition.
virtual void rotateRightP1 ()=0
Virtual void function, look to child for defenition.
virtual void moveForwardP2 ()=0
Virtual void function, look to child for defenition.
virtual void moveBackwardP2 ()=0
Virtual void function, look to child for defenition.
virtual void rotateLeftP2 ()=0
Virtual void function, look to child for defenition.
virtual void rotateRightP2 ()=0
Virtual void function, look to child for defenition.
virtual void missileFiredP1 ()=0
Virtual void function, look to child for defenition.
virtual void missileFiredP2 ()=0
Virtual void function, look to child for defenition.
virtual void mineLaidP1 ()=0
Virtual void function, look to child for defenition.
virtual void mineLaidP2 ()=0
Virtual void function, look to child for defenition.
virtual void resetP1Attack ()=0
Virtual void function, look to child for defenition.
virtual void resetP2Attack ()=0
Virtual void function, look to child for defenition.
virtual ~ActionData ()
Destructor for Action Data.
Detailed Description
Definition at line 16 of file ActionData.h.
Constructor & Destructor Documentation
virtual ActionData::~ActionData () [inline], [virtual]
Destructor for Action Data.
Definition at line 57 of file ActionData.h.
{};
Member Function Documentation
virtual const actions_info& ActionData::giveActionInfo () const [pure virtual]
Provide the actions_info structure of a class.
Implemented in GameManagementData.
Referenced by MoveManager::manage(), and GameStateManager::manageAttackTimers().
virtual void ActionData::mineLaidP1 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::mineLaidP2 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::missileFiredP1 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::missileFiredP2 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::moveBackwardP1 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::moveBackwardP2 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::moveForwardP1 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::moveForwardP2 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::resetActionsInfo () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
virtual void ActionData::resetP1Attack () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by GameStateManager::manageAttackTimers().
virtual void ActionData::resetP2Attack () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by GameStateManager::manageAttackTimers().
virtual void ActionData::resetTurretFire () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
virtual void ActionData::rotateLeftP1 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::rotateLeftP2 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::rotateRightP1 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::rotateRightP2 () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by Game::checkKeyboardInput().
virtual void ActionData::setTurretFire () [pure virtual]
Virtual void function, look to child for defenition.
Implemented in GameManagementData.
Referenced by TrackingManager::manage().
The documentation for this class was generated from the following file:
ActionData.h