DrawManager Class Reference
Manager class responsible for preparing draw data.
#include <DrawManager.h>
Public Member Functions
DrawManager ()
Draw manager object constructor.
virtual void manage (GameStateData &game_state_container, std::shared_ptr< Display > display)
Drawing management cycle.
void addNewEntity (const std::weak_ptr< Deletable > new_entity)
Adds a pointer to a drawable object.
virtual ~DrawManager ()
Private Member Functions
void getTankDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info &draw_info)
Gets info for tank to be drawn.
void getMissileDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info &draw_info)
Gets info for missile to be drawn.
void getMineDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info &draw_info)
Gets info for mine to be drawn.
void getBarrierDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info &draw_info)
Gets info for barrier to be drawn.
void getTurretDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info &draw_info)
Gets info for turret to be drawn.
void getDrawPosition (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info &draw_info)
Gets info for an entity to be drawn.
Private Attributes
std::vector< std::weak_ptr
*
< Deletable > > _drawables
Pointers to all drawable entites within the game world.
SpriteDimensions _sprite_dimensions
Private data object that holds sprite dimension info.
Detailed Description
Manager class responsible for preparing draw data.
Definition at line 24 of file DrawManager.h.
Constructor & Destructor Documentation
DrawManager::DrawManager ()
Draw manager object constructor.
Create the sprite dimensions object
Definition at line 18 of file DrawManager.cpp.
                        :
    _sprite_dimensions()
{
}
DrawManager::~DrawManager () [virtual]
Definition at line 209 of file DrawManager.cpp.
{
}
Member Function Documentation
void DrawManager::addNewEntity (const std::weak_ptr< Deletable > new_entity)
Adds a pointer to a drawable object.
A weak pointer is saved to the private vector of the DrawManager
Parameters
new_entity :: weak pointer to entity that will be added
Definition at line 203 of file DrawManager.cpp.
References _drawables.
Referenced by Game::addDeletable(), and main().
{
    _drawables.push_back(new_entity);
}
void DrawManager::getBarrierDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info & draw_info) [private]
Gets info for barrier to be drawn.
This info includs the origin and position of the barrier.
Parameters
draw_entity_sp :: shared pointer to the object from which info will be extracted
draw_info :: Info that will be updated with the entity draw position info.
Definition at line 144 of file DrawManager.cpp.
References _sprite_dimensions, SpriteDimensions::barrier_sprite_x, SpriteDimensions::barrier_sprite_y, getDrawPosition(), sprite_draw_info::origin, coordinate::x, and coordinate::y.
Referenced by manage().
{
    draw_info.origin.x = _sprite_dimensions.
      barrier_sprite_x/2;
    draw_info.origin.y = _sprite_dimensions.
      barrier_sprite_y/2;
    getDrawPosition(draw_entity_sp, draw_info);
}
void DrawManager::getDrawPosition (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info & draw_info) [private]
Gets info for an entity to be drawn.
This info includs the origin and position of the entity.
Parameters
draw_entity_sp :: shared pointer to the object from which info will be extracted
draw_info :: Info that will be updated with the entity draw position info.
Definition at line 192 of file DrawManager.cpp.
References sprite_draw_info::draw_pos, sprite_draw_info::rotation, coordinate::x, and coordinate::y.
Referenced by getBarrierDrawInfo(), getMineDrawInfo(), getMissileDrawInfo(), getTankDrawInfo(), and getTurretDrawInfo().
{
    draw_info.draw_pos.x = draw_entity_sp->getDrawPositionX();
    draw_info.draw_pos.y = draw_entity_sp->getDrawPositionY();
    draw_info.rotation = draw_entity_sp->getDrawRotation();
}
void DrawManager::getMineDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info & draw_info) [private]
Gets info for mine to be drawn.
This info includs the origin and position of the mine.
Parameters
draw_entity_sp :: shared pointer to the object from which info will be extracted
draw_info :: Info that will be updated with the entity draw position info.
Definition at line 168 of file DrawManager.cpp.
References _sprite_dimensions, getDrawPosition(), SpriteDimensions::mine_sprite_x, SpriteDimensions::mine_sprite_y, sprite_draw_info::origin, coordinate::x, and coordinate::y.
Referenced by manage().
{
    draw_info.origin.x = _sprite_dimensions.
      mine_sprite_x/2;
    draw_info.origin.y = _sprite_dimensions.
      mine_sprite_y/2;
    getDrawPosition(draw_entity_sp, draw_info);
}
void DrawManager::getMissileDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info & draw_info) [private]
Gets info for missile to be drawn.
This info includs the origin and position of the missile.
Parameters
draw_entity_sp :: shared pointer to the object from which info will be extracted
draw_info :: Info that will be updated with the entity draw position info.
Definition at line 156 of file DrawManager.cpp.
References _sprite_dimensions, getDrawPosition(), SpriteDimensions::missile_sprite_x, SpriteDimensions::missile_sprite_y, sprite_draw_info::origin, coordinate::x, and coordinate::y.
Referenced by manage().
{
    draw_info.origin.x = _sprite_dimensions.
      missile_sprite_x/2;
    draw_info.origin.y = _sprite_dimensions.
      missile_sprite_y/2;
    getDrawPosition(draw_entity_sp, draw_info);
}
void DrawManager::getTankDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info & draw_info) [private]
Gets info for tank to be drawn.
This info includs the origin and position of the tank.
Parameters
draw_entity_sp :: shared pointer to the object from which info will be extracted
draw_info :: Info that will be updated with the entity draw position info.
Definition at line 132 of file DrawManager.cpp.
References _sprite_dimensions, getDrawPosition(), sprite_draw_info::origin, SpriteDimensions::tank_sprite_x, SpriteDimensions::tank_sprite_y, coordinate::x, and coordinate::y.
Referenced by manage().
{
    draw_info.origin.x = _sprite_dimensions.
      tank_sprite_x/2;
    draw_info.origin.y = _sprite_dimensions.
      tank_sprite_y/2;
    getDrawPosition(draw_entity_sp, draw_info);
}
void DrawManager::getTurretDrawInfo (std::shared_ptr< Deletable > draw_entity_sp, sprite_draw_info & draw_info) [private]
Gets info for turret to be drawn.
This info includs the origin and position of the turret.
Parameters
draw_entity_sp :: shared pointer to the object from which info will be extracted
draw_info :: Info that will be updated with the entity draw position info.
Definition at line 180 of file DrawManager.cpp.
References _sprite_dimensions, getDrawPosition(), sprite_draw_info::origin, SpriteDimensions::turret_sprite_x, SpriteDimensions::turret_sprite_y, coordinate::x, and coordinate::y.
Referenced by manage().
{
    draw_info.origin.x = _sprite_dimensions.
      turret_sprite_x/2;
    draw_info.origin.y = _sprite_dimensions.
      turret_sprite_y/2;
    getDrawPosition(draw_entity_sp, draw_info);
}
void DrawManager::manage (GameStateData & game_state_container, std::shared_ptr< Display > display) [virtual]
Drawing management cycle.
Main function of the DrawManager. The display object is accessable within here. The DrawManager first gets the display to clear the window and display the background. Then all drawables are iterated through and drawn. Info is collected based on the entity that will be drawn. This information is passed to the display object which actually performs the drawing.
Parameters
game_state_container :: Game data that hold the time and player scores to be drawn
display :: The display to which display information is passed.
Definition at line 32 of file DrawManager.cpp.
References _drawables, barrier, draw_strings::game_time, getBarrierDrawInfo(), GameStateData::getGameTime(), getMineDrawInfo(), getMissileDrawInfo(), GameStateData::getP1Score(), GameStateData::getP2Score(), getTankDrawInfo(), getTurretDrawInfo(), p1_mine, p1_missile, draw_strings::p1_score, p1_tank, p2_mine, p2_missile, draw_strings::p2_score, p2_tank, turret, and turret_missile.
Referenced by main(), and Game::runAllManagers().
{
    display->clear();
    display->drawBackground();
    sprite_draw_info draw_info;
    //Used to traverse the vector of drawables held by DrawManager
    auto draw_itterator = _drawables.begin();
    //Loop through Array of Drawables and draw the corresponding sprite
    for(;draw_itterator != _drawables.end();)
    {
        //Deref itterator to weak pointer
        std::weak_ptr<Deletable> draw_entity_wp = (*draw_itterator);
        //Convert to shared pointer
        std::shared_ptr<Deletable> draw_entity_sp = draw_entity_wp.lock();
        //Check to see if the entity still exists
        if(draw_entity_sp)
        {
            switch (draw_entity_sp->getType())
            {
                case p1_tank:
                    getTankDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(p1_tank, draw_info);
                    break;
                case p2_tank:
                    getTankDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(p2_tank, draw_info);
                    break;
                case barrier:
                    getBarrierDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(barrier, draw_info);
                    break;
                case p1_missile:
                    getMissileDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(p1_missile, draw_info);
                    break;
                case p2_missile:
                    getMissileDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(p2_missile, draw_info);
                    break;
                case p1_mine:
                    getMineDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(p1_mine, draw_info);
                    break;
                case p2_mine:
                    getMineDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(p2_mine, draw_info);
                    break;
                case turret:
                    getTurretDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(turret, draw_info);
                    break;
                case turret_missile:
                    getMissileDrawInfo(draw_entity_sp, draw_info);
                    display->drawEntity(turret_missile, draw_info);
                    break;
                default:
                break;
            } //Switch
            draw_itterator++;
        } //if (pointer still valid)
        else
            _drawables.erase(draw_itterator);
    } //for
    draw_strings strings;
    std::ostringstream strs1; // convert to strings
    strs1 << game_state_container.getGameTime();
    strings.game_time = strs1.str();
    std::ostringstream strs2;
    strs2 << game_state_container.getP1Score();
    strings.p1_score = strs2.str();
    std::ostringstream strs3;
    strs3 << game_state_container.getP2Score();
    strings.p2_score = strs3.str();
    display->drawText(strings);
    display->display();
}
Member Data Documentation
std::vector<std::weak_ptr<Deletable> > DrawManager::_drawables [private]
Pointers to all drawable entites within the game world.
Definition at line 34 of file DrawManager.h.
Referenced by addNewEntity(), and manage().
SpriteDimensions DrawManager::_sprite_dimensions [private]
Private data object that holds sprite dimension info.
Definition at line 36 of file DrawManager.h.
Referenced by getBarrierDrawInfo(), getMineDrawInfo(), getMissileDrawInfo(), getTankDrawInfo(), and getTurretDrawInfo().
The documentation for this class was generated from the following files:
DrawManager.h
DrawManager.cpp