GameManagementData Class Reference
Implementation for the GameManagementData Class.
#include <GameManagementData.h>
Public Member Functions
GameManagementData ()
Constructor.
virtual void resetActionsInfo ()
Virtual void function, look to child for defenition.
virtual const actions_info & giveActionInfo () const
Returns the action data container held by the class.
virtual void resetTurretFire ()
Reset the firing condition of the game Turrets.
virtual void setTurretFire ()
Enable the firing conditon of the game Turrets.
virtual void moveForwardP1 ()
Set Player1 to move forward.
virtual void moveBackwardP1 ()
Set player2 to move forward.
virtual void rotateLeftP1 ()
Set player1 to rotate left.
virtual void rotateRightP1 ()
Set player1 to rotate right.
virtual void moveForwardP2 ()
Set player2 to move forward.
virtual void moveBackwardP2 ()
Set player 2 to move backward.
virtual void rotateLeftP2 ()
Set player 2 to rotate left.
virtual void rotateRightP2 ()
Set player 2 to rotate right.
virtual void missileFiredP1 ()
Set missile for player 1 fired.
virtual void missileFiredP2 ()
Set missile for player 2 fired.
virtual void mineLaidP1 ()
Set mine laid for player 1.
virtual void mineLaidP2 ()
Set mine laid for player 2.
virtual void resetP1Attack ()
Restt player1 attack state.
virtual void resetP2Attack ()
Reset player2 attack state.
virtual const int getP1Score ()
Getter for p1 score.
virtual const int getP2Score ()
Getter for p2 score.
virtual void increaseP1Score ()
Increment p1 score by 1.
virtual void increaseP2Score ()
Increment p2 score by 1.
virtual void setP1Respawn ()
Set p1 to respawn.
virtual void setP2Respawn ()
Set p2 to respawn.
virtual void disableP1Respawn ()
Disable p1 to respawn.
virtual void disableP2Respawn ()
Disable p2 to respawn.
virtual const bool isP1Respawn ()
Check if p1 is respawnable.
virtual const bool isP2Respawn ()
Check if p2 is respawnable.
virtual const bool isGameFinished ()
Check if Game is in a finished state.
virtual void setGameFinished ()
Set game in a finishe state.
virtual void setGameTime (const float game_time)
Set the game time.
virtual const float getGameTime ()
Retrieve the game time for draw manager.
virtual ~GameManagementData ()
Destructor.
Private Attributes
actions_info _game_actions
int _p1_score
int _p2_score
bool _p1_respawn
bool _p2_respawn
bool _game_state
float _game_time
Detailed Description
Implementation for the GameManagementData Class.
GameManagementData serves as a dynamic data container which is passed around during the game management cycle. It holds basic getter and setter functions which are visible to only certain managers at specific times.
Definition at line 17 of file GameManagementData.h.
Constructor & Destructor Documentation
GameManagementData::GameManagementData ()
Constructor.
Constructor for GameManagementData object.
Initialises all private data members to a zero state. The reset actions info funcition called during the constructor ensures the struct held by the class is set to zero as well.
Definition at line 19 of file GameManagementData.cpp.
References resetActionsInfo().
                                       :
     _p1_score(0),
     _p2_score(0),
     _game_time(0),
     _p1_respawn(false),
     _p2_respawn(false),
     _game_state(false)
     {
        resetActionsInfo();
     }
GameManagementData::~GameManagementData () [virtual]
Destructor.
Definition at line 320 of file GameManagementData.cpp.
{
}
Member Function Documentation
void GameManagementData::disableP1Respawn () [virtual]
Disable p1 to respawn.
Disallow p1 to respwan again.
This function stops the Game object from creating another tank player while it is alive it has been destroyed
Implements GameStateData.
Definition at line 254 of file GameManagementData.cpp.
References _p1_respawn.
Referenced by Game::manageRespawns().
{
    _p1_respawn = false;
}
void GameManagementData::disableP2Respawn () [virtual]
Disable p2 to respawn.
Disallow p2 to respwan again.
This function stops the Game object from creating another tank player while it is alive it has been destroyed
Implements GameStateData.
Definition at line 263 of file GameManagementData.cpp.
References _p2_respawn.
Referenced by Game::manageRespawns().
{
    _p2_respawn = false;
}
const float GameManagementData::getGameTime () [virtual]
Retrieve the game time for draw manager.
Function to fetch the current game time.
Returns the value of the current game timer within GameStateManager
Implements GameStateData.
Definition at line 315 of file GameManagementData.cpp.
References _game_time.
{
    return _game_time;
}
const int GameManagementData::getP1Score () [virtual]
Getter for p1 score.
Retrieve p1 score.
This is a simple getter method
Implements GameStateData.
Definition at line 200 of file GameManagementData.cpp.
References _p1_score.
Referenced by TEST().
{
    return _p1_score;
}
const int GameManagementData::getP2Score () [virtual]
Getter for p2 score.
Retrieve p2 score.
This is a simple getter method
Implements GameStateData.
Definition at line 208 of file GameManagementData.cpp.
References _p2_score.
Referenced by TEST().
{
    return _p2_score;
}
const actions_info & GameManagementData::giveActionInfo () const [virtual]
Returns the action data container held by the class.
Getter for the actions_info object.
This retrieves the current version of the actions_info container
Returns
actions_info
Implements ActionData.
Definition at line 50 of file GameManagementData.cpp.
References _game_actions.
Referenced by Game::addNewWorldEntity(), and TEST().
{
    return _game_actions;
}
void GameManagementData::increaseP1Score () [virtual]
Increment p1 score by 1.
Increment p1 score.
This increments p1's score by one point
Implements GameStateData.
Definition at line 216 of file GameManagementData.cpp.
References _p1_respawn, and _p1_score.
{
    _p1_score++;
    _p1_respawn = true;
}
void GameManagementData::increaseP2Score () [virtual]
Increment p2 score by 1.
Increment p2 score.
This increments p2's score by one point
Implements GameStateData.
Definition at line 226 of file GameManagementData.cpp.
References _p2_respawn, and _p2_score.
{
    _p2_score++;
    _p2_respawn = true;
}
const bool GameManagementData::isGameFinished () [virtual]
Check if Game is in a finished state.
Check boolean state of the game.
This function will return a true result after 2 minutes of the game running.
Returns
bool
Implements GameStateData.
Definition at line 290 of file GameManagementData.cpp.
References _game_state.
Referenced by Game::runWorld().
{
    return _game_state;
}
const bool GameManagementData::isP1Respawn () [virtual]
Check if p1 is respawnable.
Check boolean state of the respawn condition.
Check for changes to see if p1 needs to be respawned
Implements GameStateData.
Definition at line 272 of file GameManagementData.cpp.
References _p1_respawn.
Referenced by Game::manageRespawns().
{
    return _p1_respawn;
}
const bool GameManagementData::isP2Respawn () [virtual]
Check if p2 is respawnable.
Check boolean state of the respawn condition.
Check for changes to see if p2 needs to be respawned
Implements GameStateData.
Definition at line 280 of file GameManagementData.cpp.
References _p2_respawn.
Referenced by Game::manageRespawns().
{
    return _p2_respawn;
}
void GameManagementData::mineLaidP1 () [virtual]
Set mine laid for player 1.
Sets condition for p1 to lay a mine.
This is a simple setter for p1 to lay a mine
Implements ActionData.
Definition at line 166 of file GameManagementData.cpp.
References _game_actions, actions_info::attack_1, actions_info::change_1, and lay_mine.
Referenced by TEST().
{
    _game_actions.change_1 = true;
    _game_actions.attack_1 = lay_mine;
}
void GameManagementData::mineLaidP2 () [virtual]
Set mine laid for player 2.
Sets condition for p2 to lay a mine.
This is a simple setter for p2 to lay a mine
Implements ActionData.
Definition at line 175 of file GameManagementData.cpp.
References _game_actions, actions_info::attack_2, actions_info::change_2, and lay_mine.
Referenced by TEST().
{
    _game_actions.change_2 = true;
    _game_actions.attack_2 = lay_mine;
}
void GameManagementData::missileFiredP1 () [virtual]
Set missile for player 1 fired.
Sets condition for p1 to fire missile.
This is a simple setter for p1 missile firing
Implements ActionData.
Definition at line 148 of file GameManagementData.cpp.
References _game_actions, actions_info::attack_1, actions_info::change_1, and fire_missile.
Referenced by TEST().
{
    _game_actions.change_1 = true;
    _game_actions.attack_1 = fire_missile;
}
void GameManagementData::missileFiredP2 () [virtual]
Set missile for player 2 fired.
Sets condition for p2 to fire missile.
This is a simple setter for p2 missile firing
Implements ActionData.
Definition at line 157 of file GameManagementData.cpp.
References _game_actions, actions_info::attack_2, actions_info::change_2, and fire_missile.
Referenced by TEST().
{
    _game_actions.change_2 = true;
    _game_actions.attack_2 = fire_missile;
}
void GameManagementData::moveBackwardP1 () [virtual]
Set player2 to move forward.
Sets p1 to move backward.
This is a simple setter for p1 backward movement
Implements ActionData.
Definition at line 85 of file GameManagementData.cpp.
References _game_actions, actions_info::change_1, actions_info::move_1, and reverse.
{
    _game_actions.change_1 = true;
    _game_actions.move_1 = reverse;
}
void GameManagementData::moveBackwardP2 () [virtual]
Set player 2 to move backward.
Sets p2 to move backward.
This is a simple setter for p2 backward movement
Implements ActionData.
Definition at line 121 of file GameManagementData.cpp.
References _game_actions, actions_info::change_2, actions_info::move_2, and reverse.
{
    _game_actions.change_2 = true;
    _game_actions.move_2 = reverse;
}
void GameManagementData::moveForwardP1 () [virtual]
Set Player1 to move forward.
Sets p1 to move forward.
This is a simple setter for p1 forward movement
Implements ActionData.
Definition at line 76 of file GameManagementData.cpp.
References _game_actions, actions_info::change_1, forward, and actions_info::move_1.
Referenced by TEST().
{
    _game_actions.change_1 = true;
    _game_actions.move_1 = forward;
}
void GameManagementData::moveForwardP2 () [virtual]
Set player2 to move forward.
Sets p2 to move forward.
This is a simple setter for p2 forward movement
Implements ActionData.
Definition at line 112 of file GameManagementData.cpp.
References _game_actions, actions_info::change_2, forward, and actions_info::move_2.
Referenced by TEST().
{
    _game_actions.change_2 = true;
    _game_actions.move_2 = forward;
}
void GameManagementData::resetActionsInfo () [virtual]
Virtual void function, look to child for defenition.
Reset The actions_info structure values to zero.
All values are reduced from their current state to a default idle state
Implements ActionData.
Definition at line 34 of file GameManagementData.cpp.
References _game_actions, actions_info::attack_1, actions_info::attack_2, actions_info::change_1, actions_info::change_2, do_nothing, actions_info::move_1, actions_info::move_2, and actions_info::turret_fire.
Referenced by GameManagementData(), Game::runWorld(), and TEST().
{
    _game_actions.change_1 = false;
    _game_actions.change_2 = false;
    _game_actions.turret_fire = false;
    _game_actions.move_1 = do_nothing;
    _game_actions.move_2 = do_nothing;
    _game_actions.attack_1 = do_nothing;
    _game_actions.attack_2 = do_nothing;
}
void GameManagementData::resetP1Attack () [virtual]
Restt player1 attack state.
This stops p1 from attacking.
P1 cannot fire for the current management cycle
Implements ActionData.
Definition at line 184 of file GameManagementData.cpp.
References _game_actions, actions_info::attack_1, and do_nothing.
{
    _game_actions.attack_1 = do_nothing;
}
void GameManagementData::resetP2Attack () [virtual]
Reset player2 attack state.
This stops p2 from attacking.
P1 cannot fire for the current management cycle
Implements ActionData.
Definition at line 192 of file GameManagementData.cpp.
References _game_actions, actions_info::attack_2, and do_nothing.
{
    _game_actions.attack_2 =do_nothing;
}
void GameManagementData::resetTurretFire () [virtual]
Reset the firing condition of the game Turrets.
Function to reset the firing state of turrets.
This function will prevent turrets from continually firing at a players tank
Implements ActionData.
Definition at line 59 of file GameManagementData.cpp.
References _game_actions, and actions_info::turret_fire.
Referenced by Game::addNewWorldEntity().
{
    _game_actions.turret_fire = false;
}
void GameManagementData::rotateLeftP1 () [virtual]
Set player1 to rotate left.
Sets p1 to rotate left.
This is a simple setter for p1 left rotation
Implements ActionData.
Definition at line 94 of file GameManagementData.cpp.
References _game_actions, actions_info::change_1, actions_info::move_1, and rotate_left.
{
    _game_actions.change_1 = true;
    _game_actions.move_1 = rotate_left;
}
void GameManagementData::rotateLeftP2 () [virtual]
Set player 2 to rotate left.
Sets p2 to rotateLeft.
This is a simple setter for p2 left rotation
Implements ActionData.
Definition at line 130 of file GameManagementData.cpp.
References _game_actions, actions_info::change_2, actions_info::move_2, and rotate_left.
{
    _game_actions.change_2 = true;
    _game_actions.move_2 = rotate_left;
}
void GameManagementData::rotateRightP1 () [virtual]
Set player1 to rotate right.
Sets p1 to rotate right.
This is a simple setter for p1 right rotation
Implements ActionData.
Definition at line 103 of file GameManagementData.cpp.
References _game_actions, actions_info::change_1, actions_info::move_1, and rotate_right.
{
    _game_actions.change_1 = true;
    _game_actions.move_1 = rotate_right;
}
void GameManagementData::rotateRightP2 () [virtual]
Set player 2 to rotate right.
Sets p2 to rotate right.
This is a simple setter for p2 right rotation
Implements ActionData.
Definition at line 139 of file GameManagementData.cpp.
References _game_actions, actions_info::change_2, actions_info::move_2, and rotate_right.
{
    _game_actions.change_2 = true;
    _game_actions.move_2 = rotate_right;
}
void GameManagementData::setGameFinished () [virtual]
Set game in a finishe state.
Set the game to be finished.
This function is called after 2 minutes of gameplay
Implements GameStateData.
Definition at line 298 of file GameManagementData.cpp.
References _game_state.
Referenced by GameStateManager::manage().
{
    _game_state = true;
}
void GameManagementData::setGameTime (const float game_time) [virtual]
Set the game time.
Update the current time of the game display clock.
This is used by draw and StateManager to render the game clock
Parameters
game_time :: the current game time retrueved from the GameStateManager
Implements GameStateData.
Definition at line 307 of file GameManagementData.cpp.
References _game_time.
Referenced by GameStateManager::manage().
{
    _game_time = game_time;
}
void GameManagementData::setP1Respawn () [virtual]
Set p1 to respawn.
Allow p1 to respwan again.
This function allows the Game object to create another tank player once it has been destroyed
Implements GameStateData.
Definition at line 236 of file GameManagementData.cpp.
References _p1_respawn.
{
    _p1_respawn = true;
}
void GameManagementData::setP2Respawn () [virtual]
Set p2 to respawn.
Allow p2 to respwan again.
This function allows the Game object to create another tank player once it has been destroyed
Implements GameStateData.
Definition at line 245 of file GameManagementData.cpp.
References _p2_respawn.
{
    _p2_respawn = true;
}
void GameManagementData::setTurretFire () [virtual]
Enable the firing conditon of the game Turrets.
Function to set the firing state of turrets.
This funcion will cause turrets to fire at a players tank in its proximity
Implements ActionData.
Definition at line 68 of file GameManagementData.cpp.
References _game_actions, and actions_info::turret_fire.
{
    _game_actions.turret_fire = true;
}
Member Data Documentation
actions_info GameManagementData::_game_actions [private]
Definition at line 93 of file GameManagementData.h.
Referenced by giveActionInfo(), mineLaidP1(), mineLaidP2(), missileFiredP1(), missileFiredP2(), moveBackwardP1(), moveBackwardP2(), moveForwardP1(), moveForwardP2(), resetActionsInfo(), resetP1Attack(), resetP2Attack(), resetTurretFire(), rotateLeftP1(), rotateLeftP2(), rotateRightP1(), rotateRightP2(), and setTurretFire().
bool GameManagementData::_game_state [private]
Definition at line 98 of file GameManagementData.h.
Referenced by isGameFinished(), and setGameFinished().
float GameManagementData::_game_time [private]
Definition at line 99 of file GameManagementData.h.
Referenced by getGameTime(), and setGameTime().
bool GameManagementData::_p1_respawn [private]
Definition at line 96 of file GameManagementData.h.
Referenced by disableP1Respawn(), increaseP1Score(), isP1Respawn(), and setP1Respawn().
int GameManagementData::_p1_score [private]
Definition at line 94 of file GameManagementData.h.
Referenced by getP1Score(), and increaseP1Score().
bool GameManagementData::_p2_respawn [private]
Definition at line 97 of file GameManagementData.h.
Referenced by disableP2Respawn(), increaseP2Score(), isP2Respawn(), and setP2Respawn().
int GameManagementData::_p2_score [private]
Definition at line 95 of file GameManagementData.h.
Referenced by getP2Score(), and increaseP2Score().
The documentation for this class was generated from the following files:
GameManagementData.h
GameManagementData.cpp