GameStateData Class Reference
#include <GameStateData.h>
Public Member Functions
virtual void increaseP1Score ()=0
Increment player 1's score by one.
virtual void increaseP2Score ()=0
Increment player 2's score by one.
virtual const int getP1Score ()=0
Retrieve player 1's score.
virtual const int getP2Score ()=0
Retrieve player 2's score.
virtual void setP1Respawn ()=0
Allow P1 to be respawed again.
virtual void setP2Respawn ()=0
Allow P2 to be respawned again.
virtual void disableP1Respawn ()=0
Disallow P1 to be respawned.
virtual void disableP2Respawn ()=0
Disallow P2 to be respawned again.
virtual const bool isP1Respawn ()=0
Chech to see if P1 can be respawned.
virtual const bool isP2Respawn ()=0
Check to see if P2 can be respawned.
virtual const bool isGameFinished ()=0
Check to see if the game has reached an end state.
virtual void setGameFinished ()=0
Set the game to a finnished state.
virtual void setGameTime (const float game_time)=0
Update the game time for rendering.
virtual const float getGameTime ()=0
Provide the current game time.
virtual ~GameStateData ()
Destructor.
Detailed Description
Definition at line 14 of file GameStateData.h.
Constructor & Destructor Documentation
virtual GameStateData::~GameStateData () [inline], [virtual]
Destructor.
Definition at line 46 of file GameStateData.h.
{};
Member Function Documentation
virtual void GameStateData::disableP1Respawn () [pure virtual]
Disallow P1 to be respawned.
Implemented in GameManagementData.
virtual void GameStateData::disableP2Respawn () [pure virtual]
Disallow P2 to be respawned again.
Implemented in GameManagementData.
virtual const float GameStateData::getGameTime () [pure virtual]
Provide the current game time.
Implemented in GameManagementData.
Referenced by DrawManager::manage().
virtual const int GameStateData::getP1Score () [pure virtual]
Retrieve player 1's score.
Implemented in GameManagementData.
Referenced by DrawManager::manage().
virtual const int GameStateData::getP2Score () [pure virtual]
Retrieve player 2's score.
Implemented in GameManagementData.
Referenced by DrawManager::manage().
virtual void GameStateData::increaseP1Score () [pure virtual]
Increment player 1's score by one.
Implemented in GameManagementData.
Referenced by DestructionManager::manage().
virtual void GameStateData::increaseP2Score () [pure virtual]
Increment player 2's score by one.
Implemented in GameManagementData.
Referenced by DestructionManager::manage().
virtual const bool GameStateData::isGameFinished () [pure virtual]
Check to see if the game has reached an end state.
Implemented in GameManagementData.
virtual const bool GameStateData::isP1Respawn () [pure virtual]
Chech to see if P1 can be respawned.
Implemented in GameManagementData.
virtual const bool GameStateData::isP2Respawn () [pure virtual]
Check to see if P2 can be respawned.
Implemented in GameManagementData.
virtual void GameStateData::setGameFinished () [pure virtual]
Set the game to a finnished state.
Implemented in GameManagementData.
virtual void GameStateData::setGameTime (const float game_time) [pure virtual]
Update the game time for rendering.
Implemented in GameManagementData.
virtual void GameStateData::setP1Respawn () [pure virtual]
Allow P1 to be respawed again.
Implemented in GameManagementData.
virtual void GameStateData::setP2Respawn () [pure virtual]
Allow P2 to be respawned again.
Implemented in GameManagementData.
The documentation for this class was generated from the following file:
GameStateData.h