Orientation Class Reference
#include <Orientation.h>
Public Member Functions
Orientation (float origin_x, float origin_y, float width, float height, float rotation, bool controllable)
Constructor that initialises all data members of the class.
const float getOriginX ()
Returns the entity origin x value.
const float getOriginY ()
Returns the entity origin y value.
const float getWidth ()
Returns the entity width.
const float getHeight ()
Returns the entity height.
const float getRotation ()
Returns the entity rotation.
void setWidth (const float width)
Set the Width Value.
void setHeight (const float height)
Set the Height Value.
void move (float movement_in_x, float movement_in_y)
Move the entity by a distance.
void rotate (float angle)
Rotate the entity by a supplied angle.
void setMoveDirection (const movement_direction)
Used to set the state of future collision detection.
rect_corners & getGlobalBounds ()
Retrieve Rectangular co-ordinates for collision detection.
const rect_corners & getAlignedGlobalBounds ()
Retrieve Rectangular co-ordinated for collision detection (Non-rotated)
virtual ~Orientation ()
Destructor.
bool operator== (Orientation &rhs) const
Equality operator overload for testing.
Private Member Functions
void setGlobalBounds ()
Function used to calculate the non-axis-aligned (Complex) bounding box of the orientation entity.
float getRelativeX () const
Used to determine the relative/future position of an orientation object.
float getRelativeY () const
Used to determine the relative/future position of an orientation object.
float getRelativeRotation () const
Used to determine the relative/future rotation of an orientation object.
Private Attributes
float _origin_x
float _origin_y
float _width
float _height
float _rotation
rect_corners _collison_box
bool _controllable
movement_direction _movement_direction
Detailed Description
Definition at line 20 of file Orientation.h.
Constructor & Destructor Documentation
Orientation::Orientation (float origin_x, float origin_y, float width, float height, float rotation, bool controllable)
Constructor that initialises all data members of the class.
Constructor for Orientation class.
Default constructor for the Orientation class
Parameters
origin_x :: The initial x-coordinate of the orientation object
origin_y :: The initial y-coordinate of the orientation object
width :: The sprite width which the orientation object will mimic
height :: The sprite height which the orientation object will mimic
rotation :: The initial rotation held by the orientation object
controllable :: This destinguishes what type of bounding box the orientation class should create
Definition at line 25 of file Orientation.cpp.
References _movement_direction, Move, and setGlobalBounds().
                                                                                                           
               :
    _origin_x(origin_x),
    _origin_y(origin_y),
    _width(width),
    _height(height),
    _rotation(rotation),
    _controllable(controllable)
    {
        _movement_direction = Move;
        setGlobalBounds();
    }
Orientation::~Orientation () [virtual]
Destructor.
Class destructor.
Definition at line 201 of file Orientation.cpp.
{
    //Possibly add code
}
Member Function Documentation
const rect_corners & Orientation::getAlignedGlobalBounds ()
Retrieve Rectangular co-ordinated for collision detection (Non-rotated)
Function used to calculate the axis-aligned (simplified) bounding box of the orientation entity.
The bounding box of the entity is calculated by taking its orientation components and extending four four verticies outwards from its origin
Returns
rect_corners
Definition at line 164 of file Orientation.cpp.
References _height, _width, getRelativeX(), getRelativeY(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
Referenced by Mine::getAlignedBoundingBox(), Barrier::getAlignedBoundingBox(), Turret::getAlignedBoundingBox(), Missile::getAlignedBoundingBox(), and Tank::getAlignedBoundingBox().
{
    rect_corners temp_box;
    //Bottom-left corner assignment
    temp_box.lower_left.x = (-_width/2) + getRelativeX();
    temp_box.lower_left.y = (-_height/2)+ getRelativeY();
    //Bottom-right corner assignment
    temp_box.lower_right.x = (+_width/2) + getRelativeX();
    temp_box.lower_right.y = (-_height/2)+ getRelativeY();
     //Top-left corner assignment
    temp_box.upper_left.x = (-_width/2) + getRelativeX();
    temp_box.upper_left.y = (+_height/2)+ getRelativeY();
    //Top-right corner assignment
    temp_box.upper_right.x = (+_width/2) + getRelativeX();
    temp_box.upper_right.y = (+_height/2)+ getRelativeY();
    return temp_box;
}
rect_corners & Orientation::getGlobalBounds ()
Retrieve Rectangular co-ordinates for collision detection.
Provides the non-axis-aligned bounding box of the orientation entity.
The need for an accurate bounding box is cruxial for collision detection. This function is responsible for fetching this box.
Returns
rect_corners
Definition at line 153 of file Orientation.cpp.
References _collison_box, and setGlobalBounds().
Referenced by Mine::getBoundingBox(), Barrier::getBoundingBox(), Turret::getBoundingBox(), Missile::getBoundingBox(), Tank::getBoundingBox(), Turret::getTrackingBoundingBox(), Tank::getTrackingBoundingBox(), and TEST().
{
    setGlobalBounds();
    return _collison_box;
}
const float Orientation::getHeight ()
Returns the entity height.
Get the current height of the orientation object.
Simple getter method used during drawing methods of the DrawManager to allow for easy data extraction
Returns
const float
Definition at line 72 of file Orientation.cpp.
References _height.
Referenced by operator==(), and TEST().
{
    return _height;
}
const float Orientation::getOriginX ()
Returns the entity origin x value.
Get the current x-coordinate of the orientation object.
Simple getter method with exception handling to prevent an invalid state from occuring
Returns
const float
Definition at line 41 of file Orientation.cpp.
References _origin_x.
Referenced by Turret::getDrawPositionX(), Mine::getDrawPositionX(), Barrier::getDrawPositionX(), Missile::getDrawPositionX(), Tank::getDrawPositionX(), Turret::getPositionX(), Tank::getPositionX(), Missile::Missile(), operator==(), Tank::Tank(), TEST(), and Turret::Turret().
{
    if (_origin_x < -100) throw InvalidStateOfCoordinates();
    return _origin_x;
}
const float Orientation::getOriginY ()
Returns the entity origin y value.
Get the current y-coordinate of the orientation object.
Simple getter method with exception handling to prevent an invalid state from occuring
Returns
const float
Definition at line 51 of file Orientation.cpp.
References _origin_y.
Referenced by Turret::getDrawPositionY(), Mine::getDrawPositionY(), Barrier::getDrawPositionY(), Missile::getDrawPositionY(), Tank::getDrawPositionY(), Turret::getPositionY(), Tank::getPositionY(), Missile::Missile(), operator==(), Tank::Tank(), TEST(), and Turret::Turret().
{
    if (_origin_y < -100) throw InvalidStateOfCoordinates();
    return _origin_y;
}
float Orientation::getRelativeRotation () const [private]
Used to determine the relative/future rotation of an orientation object.
In order to calculate an accurate collision occuring beforehand, the next value of the rotation needs to be provided to produce a valid bounding box.
Returns
float
Definition at line 306 of file Orientation.cpp.
References _controllable, _movement_direction, _rotation, rotateLeft, rotateRight, and TANK_ROTATION_SPEED.
Referenced by setGlobalBounds().
{
    float returnedRotation = 0.0;
    if(!_controllable)
        return _rotation;
    else
    {
        switch (_movement_direction)
        {
        case rotateLeft:
            returnedRotation = _rotation + TANK_ROTATION_SPEED;
            if (returnedRotation > 360)
                returnedRotation -= 360;
            break;
        case rotateRight:
            returnedRotation = _rotation - TANK_ROTATION_SPEED;
            if (returnedRotation < 0)
                returnedRotation += 360;
            break;
        default:
            returnedRotation = _rotation;
        }
    return returnedRotation;
    }
}
float Orientation::getRelativeX () const [private]
Used to determine the relative/future position of an orientation object.
In order to calculate an accurate collision occuring beforehand, the next value of x and y coordinated need to be provided to produce a valid bounding box.
Returns
float
Definition at line 238 of file Orientation.cpp.
References _controllable, _movement_direction, _origin_x, _rotation, moveBackward, moveForward, PI, and TANK_MOVE_SPEED.
Referenced by getAlignedGlobalBounds(), and setGlobalBounds().
{
    float angle = _rotation*(PI/180);
    float returnVal = 0.0;
    if (!_controllable)
        return _origin_x;
    else
    {
        switch(_movement_direction)
        {
        case moveForward:
            returnVal = (_origin_x + TANK_MOVE_SPEED*cos(angle));
            break;
        case moveBackward:
            returnVal = (_origin_x - TANK_MOVE_SPEED*cos(angle));
            break;
        default:
            returnVal = _origin_x;
            break;
        }
        return returnVal;
    }
}
float Orientation::getRelativeY () const [private]
Used to determine the relative/future position of an orientation object.
In order to calculate an accurate collision occuring beforehand, the next value of x and y coordinated need to be provided to produce a valid bounding box.
Returns
float
Definition at line 272 of file Orientation.cpp.
References _controllable, _movement_direction, _origin_y, _rotation, moveBackward, moveForward, PI, and TANK_MOVE_SPEED.
Referenced by getAlignedGlobalBounds(), and setGlobalBounds().
{
    float angle = _rotation*(PI/180);
    float returnVal = 0.0;
    if (!_controllable)
        return _origin_y;
    else
    {
        switch(_movement_direction)
        {
        case moveForward:
            returnVal = (_origin_y + TANK_MOVE_SPEED*sin(angle));
            break;
        case moveBackward:
            returnVal = (_origin_y - TANK_MOVE_SPEED*sin(angle));
            break;
        default:
            returnVal = _origin_y;
            break;
        }
        return returnVal;
    }
}
const float Orientation::getRotation ()
Returns the entity rotation.
Get the current rotation of the orientation object.
Simple getter method used during drawing methods of the DrawManager to allow for easy data extraction.
Returns
const float
Definition at line 82 of file Orientation.cpp.
References _rotation.
Referenced by Turret::getDrawRotation(), Mine::getDrawRotation(), Barrier::getDrawRotation(), Missile::getDrawRotation(), Tank::getDrawRotation(), Turret::getOrientation(), Tank::getOrientation(), Missile::Missile(), operator==(), Missile::rotateLeft(), Missile::rotateRight(), Tank::Tank(), TEST(), and Turret::Turret().
{
    return _rotation;
}
const float Orientation::getWidth ()
Returns the entity width.
Get the current width of the orientation object.
Simple getter method used during drawing methods of the DrawManager to allow for easy data extraction
Returns
const float
Definition at line 62 of file Orientation.cpp.
References _width.
Referenced by TEST().
{
    return _width;
}
void Orientation::move (float movement_in_x, float movement_in_y)
Move the entity by a distance.
Move the orientation object positively by (x,y) units.
This method replaces that of SF::RectInt32.move(). It takes in cartestian parameters and moves the object relative to its currect position in the positive direction specified.
Parameters
movement_in_x :: The movement direction for the x component
movement_in_y :: The movement direction for the y component
Definition at line 115 of file Orientation.cpp.
References _origin_x, and _origin_y.
Referenced by Missile::moveBackward(), Tank::moveBackward(), Missile::moveForward(), Tank::moveForward(), and TEST().
{
    _origin_x += movement_in_x;
    _origin_y += movement_in_y;
}
bool Orientation::operator== (Orientation & rhs) const
Equality operator overload for testing.
Opperator used for testing purposes of the orientation class.
This function is written to allow for comparison of created orientation objects in an efficient manner without the DRY principal being violatued.
Parameters
rhs :: an Orientation object.
Returns
bool
Definition at line 340 of file Orientation.cpp.
References _height, _origin_x, _origin_y, _rotation, _width, getHeight(), getOriginX(), getOriginY(), and getRotation().
{
    if(_origin_x != rhs.getOriginX()) return false;
    if(_origin_y != rhs.getOriginY()) return false;
    if(_rotation != rhs.getRotation()) return false;
    if(_height != rhs.getHeight()) return false;
    if(_width != rhs.getHeight()) return false;
    return true;
}
void Orientation::rotate (float angle)
Rotate the entity by a supplied angle.
Rotate the orientation object positively by (x) units.
This method replaces that of SF::RectInt32.rotate(). It takes in an angular parameters and rotates the object relative to its currect position. Conditional logic is implemented here as a means only to manintain class invariance in the positive direction specified.
Parameters
angle :: The rotation in degreees
Definition at line 128 of file Orientation.cpp.
References _rotation.
Referenced by Missile::rotateLeft(), Tank::rotateLeft(), Missile::rotateRight(), Tank::rotateRight(), Turret::rotateTurret(), and TEST().
{
    //Positive revolution
    if ((_rotation+angle) >= 360)
    {
       _rotation += angle;
       while (_rotation > 360)
       _rotation -= 360;
    }
    //Negative revolution
    else if ((_rotation+angle) < 0)
    {
        _rotation += angle;
        while (_rotation < 0)
        _rotation += 360;
    }
    else
       _rotation += angle;
}
void Orientation::setGlobalBounds () [private]
Function used to calculate the non-axis-aligned (Complex) bounding box of the orientation entity.
The bounding box of the entity is calculated by taking its orientation components and extending four four verticies outwards within the bounds of a trigometric relationship from its origin.
Returns
rect_corners
Definition at line 211 of file Orientation.cpp.
References _collison_box, _height, _width, getRelativeRotation(), getRelativeX(), getRelativeY(), rect_corners::lower_left, rect_corners::lower_right, PI, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
Referenced by getGlobalBounds(), and Orientation().
{
    float angle = getRelativeRotation()*(PI/180);
    //Bottom-left corner assignment
    _collison_box.lower_left.x = (-_width/2)*cos(angle) - (-
      _height/2)*sin(angle) + getRelativeX();
    _collison_box.lower_left.y = (-_width/2)*sin(angle) + (-
      _height/2)*cos(angle) + getRelativeY();
    //Bottom-right corner assignment
    _collison_box.lower_right.x = (+_width/2)*cos(angle) - (-
      _height/2)*sin(angle) + getRelativeX();
    _collison_box.lower_right.y = (+_width/2)*sin(angle) + (-
      _height/2)*cos(angle) + getRelativeY();
     //Top-left corner assignment
    _collison_box.upper_left.x = (-_width/2)*cos(angle) - (+
      _height/2)*sin(angle) + getRelativeX();
    _collison_box.upper_left.y = (-_width/2)*sin(angle) + (+
      _height/2)*cos(angle) + getRelativeY();
    //Top-right corner assignment
    _collison_box.upper_right.x = (+_width/2)*cos(angle) - (+
      _height/2)*sin(angle) + getRelativeX();
    _collison_box.upper_right.y = (+_width/2)*sin(angle) + (+
      _height/2)*cos(angle) + getRelativeY();
}
void Orientation::setHeight (const float height)
Set the Height Value.
Set a new value for an orientation objects height.
Simple setter method used to extract the height of an orientation object.
Parameters
height :: The new height value to be assigned to the orientation object
Returns
const float
Definition at line 103 of file Orientation.cpp.
References _height.
Referenced by Barrier::Barrier(), Mine::Mine(), Missile::Missile(), Tank::Tank(), and Turret::Turret().
{
    _height = height;
}
void Orientation::setMoveDirection (const movement_direction movement_command)
Used to set the state of future collision detection.
Function used to set the direction in which the orientation object is currently moving.
The need to know in which direction an orientation object is traveling is vitally importatnt for movable object collision detection. Based upon this value, a different bounding box will be produced for the object.
Parameters
movement_command :: an Enum defining the four cardinal directions
Definition at line 192 of file Orientation.cpp.
References _movement_direction.
Referenced by Missile::setMovementDirection(), and Tank::setMovementDirection().
{
    _movement_direction = movement_command;
}
void Orientation::setWidth (const float width)
Set the Width Value.
Set a new value for an orientation objects width.
Simple setter method used to extract the width of an orientation. object
Parameters
width :: The new width value to be assigned to the orientation object
Definition at line 92 of file Orientation.cpp.
References _width.
Referenced by Barrier::Barrier(), Mine::Mine(), Missile::Missile(), Tank::Tank(), and Turret::Turret().
{
    _width = width;
}
Member Data Documentation
rect_corners Orientation::_collison_box [private]
Definition at line 61 of file Orientation.h.
Referenced by getGlobalBounds(), and setGlobalBounds().
bool Orientation::_controllable [private]
Definition at line 62 of file Orientation.h.
Referenced by getRelativeRotation(), getRelativeX(), and getRelativeY().
float Orientation::_height [private]
Definition at line 59 of file Orientation.h.
Referenced by getAlignedGlobalBounds(), getHeight(), operator==(), setGlobalBounds(), and setHeight().
movement_direction Orientation::_movement_direction [private]
Definition at line 63 of file Orientation.h.
Referenced by getRelativeRotation(), getRelativeX(), getRelativeY(), Orientation(), and setMoveDirection().
float Orientation::_origin_x [private]
Definition at line 56 of file Orientation.h.
Referenced by getOriginX(), getRelativeX(), move(), and operator==().
float Orientation::_origin_y [private]
Definition at line 57 of file Orientation.h.
Referenced by getOriginY(), getRelativeY(), move(), and operator==().
float Orientation::_rotation [private]
Definition at line 60 of file Orientation.h.
Referenced by getRelativeRotation(), getRelativeX(), getRelativeY(), getRotation(), operator==(), and rotate().
float Orientation::_width [private]
Definition at line 58 of file Orientation.h.
Referenced by getAlignedGlobalBounds(), getWidth(), operator==(), setGlobalBounds(), and setWidth().
The documentation for this class was generated from the following files:
Orientation.h
Orientation.cpp