Tank Class Reference
#include <Tank.h>
Public Member Functions
Tank (float positionX, float positionY, float rotation, entity_type tankOwner)
Default Tank object constructor.
virtual const entity_type & getType () const
Provided ownership.
virtual void moveForward ()
Forward movement for a tank entity.
virtual void moveBackward ()
Backward movement for a tank entity.
virtual void rotateLeft ()
Left rotation for a tank entity.
virtual void rotateRight ()
Right rotation for a tank entity.
virtual const rect_corners & getBoundingBox ()
Provide the bounding box for the tank entity.
virtual const rect_corners & getAlignedBoundingBox ()
Get Axis Aligned bounding box of entity.
virtual const int setBlocked (const blocked_status obstruction_type)
Instruct the tank entity that it cannot move.
virtual void setUnblocked ()
Instruct the tank entity that it can move.
virtual void setCollided ()
Instruct the tank entity that it has collided with another object.
virtual const blocked_status isBlocked ()
Determine the blocked state of the tank entity.
virtual bool const isDeleted ()
Boolean state of the tank entity's life.
virtual const float getPositionX ()
Get the current x co-ordinate of Trackable object.
virtual const float getPositionY ()
Get the current y co-ordinate of Trackable object.
virtual const float getOrientation ()
Get the current orientation of Trackable object.
virtual const rect_corners & getTrackingBoundingBox ()
Get the bounding box relevant for line-of-fire detection.
virtual const float getDrawPositionX ()
Retrieve the Tank x Position.
virtual const float getDrawPositionY ()
Retrieve the Tank y Position.
virtual const float getDrawRotation ()
Recieve the Tank rotation.
virtual void setMovementDirection (const movement_direction Movement_input)
Set the movement direction of the entity.
virtual ~Tank ()
Tank object destructor.
Private Attributes
blocked_status _blockedStatus
Movability of the Tank entity: 1 for blocked, 0 for free.
bool _collidedStatus
Collision state of the Tank Entity: 1 for collided, 0 for not.
float _rotation
The angle of rotation for the Tank entity.
Orientation _tank
Co-ordinate system for the Tank.
entity_type _type
Enumeration type defining the tank.
SpriteDimensions _sprite_dimensions
Tank Sprite Dimensions.
Additional Inherited Members
Detailed Description
Definition at line 29 of file Tank.h.
Constructor & Destructor Documentation
Tank::Tank (float positionX, float positionY, float rotation, entity_type tankOwner)
Default Tank object constructor.
Constuctor of the Tank Class.
This constructor utilises excetion handling and seeks to ensure that its state is invariant.
Parameters
positionX :: The initial x-axis to construct the tank on.
positionY :: The initial y-axis to construct the tank on
rotation :: The initial rotation to construct the tank with
tankOwner :: used to set the owner of the tank as either p1 or p2
Definition at line 20 of file Tank.cpp.
References _blockedStatus, _collidedStatus, _sprite_dimensions, _tank, _type, Orientation::getOriginX(), Orientation::getOriginY(), Orientation::getRotation(), p1_tank, p2_tank, Orientation::setHeight(), Orientation::setWidth(), SpriteDimensions::tank_sprite_x, SpriteDimensions::tank_sprite_y, and unblocked.
                                                                                 :
    _rotation(rotation),
    _type(tankOwner),
    _tank(positionX,positionY,0,0,rotation, true),
    _sprite_dimensions()
{
    //Error input checking
    if (_tank.getOriginX() < 0) throw
      InvalidConstructorArgumentsTank();
    if (_tank.getOriginY() < 0) throw
      InvalidConstructorArgumentsTank();
    if (_tank.getRotation() < 0) throw
      InvalidConstructorArgumentsTank();
    if ((_type != p1_tank) && (_type != p2_tank)) throw
      InvalidConstructorArgumentsTank();
    _tank.setWidth(_sprite_dimensions.
      tank_sprite_x);
    _tank.setHeight(_sprite_dimensions.
      tank_sprite_y);
    _blockedStatus = unblocked;
    _collidedStatus = 0;
}
Tank::~Tank () [virtual]
Tank object destructor.
Definition at line 186 of file Tank.cpp.
{
}
Member Function Documentation
const rect_corners & Tank::getAlignedBoundingBox () [virtual]
Get Axis Aligned bounding box of entity.
Implements Collidable.
Definition at line 156 of file Tank.cpp.
References _tank, and Orientation::getAlignedGlobalBounds().
 {
     return _tank.getAlignedGlobalBounds();
 }
const rect_corners & Tank::getBoundingBox () [virtual]
Provide the bounding box for the tank entity.
Retrieves the tanks bounding box.
This function is used in conjunction with collision detection
Implements Collidable.
Definition at line 91 of file Tank.cpp.
References _tank, and Orientation::getGlobalBounds().
{
    return _tank.getGlobalBounds();
}
const float Tank::getDrawPositionX () [virtual]
Retrieve the Tank x Position.
Retrieve the x Tank Position.
Implements Deletable.
Definition at line 162 of file Tank.cpp.
References _tank, and Orientation::getOriginX().
Referenced by TEST().
{
    return _tank.getOriginX();
}
const float Tank::getDrawPositionY () [virtual]
Retrieve the Tank y Position.
Retrieve the y Tank Position.
Implements Deletable.
Definition at line 168 of file Tank.cpp.
References _tank, and Orientation::getOriginY().
Referenced by TEST().
{
    return _tank.getOriginY();
}
const float Tank::getDrawRotation () [virtual]
Recieve the Tank rotation.
Implements Deletable.
Definition at line 174 of file Tank.cpp.
References _tank, and Orientation::getRotation().
Referenced by TEST().
{
    return _tank.getRotation();
}
const float Tank::getOrientation () [virtual]
Get the current orientation of Trackable object.
Implements Trackable.
Definition at line 145 of file Tank.cpp.
References _tank, and Orientation::getRotation().
Referenced by TEST().
{
    return _tank.getRotation();
}
const float Tank::getPositionX () [virtual]
Get the current x co-ordinate of Trackable object.
Get the current x co-ordinates of Trackable object.
Implements Trackable.
Definition at line 133 of file Tank.cpp.
References _tank, and Orientation::getOriginX().
Referenced by TEST().
{
    return _tank.getOriginX();
}
const float Tank::getPositionY () [virtual]
Get the current y co-ordinate of Trackable object.
Get the current y co-ordinates of Trackable object.
Implements Trackable.
Definition at line 139 of file Tank.cpp.
References _tank, and Orientation::getOriginY().
Referenced by TEST().
{
    return _tank.getOriginY();
}
const rect_corners & Tank::getTrackingBoundingBox () [virtual]
Get the bounding box relevant for line-of-fire detection.
Implements Trackable.
Definition at line 151 of file Tank.cpp.
References _tank, and Orientation::getGlobalBounds().
 {
    return _tank.getGlobalBounds();
 }
const entity_type & Tank::getType () const [virtual]
Provided ownership.
Returns the owner of the tank.
This is function is used in many logic instanses where the owner of the tank needs to be determined.
Returns
entity_type
Implements Deletable.
Definition at line 44 of file Tank.cpp.
References _type.
Referenced by TEST().
 {
     return _type;
 }
const blocked_status Tank::isBlocked () [virtual]
Determine the blocked state of the tank entity.
Implements Movable.
Definition at line 121 of file Tank.cpp.
References _blockedStatus.
Referenced by TEST().
{
    return _blockedStatus;
}
const bool Tank::isDeleted () [virtual]
Boolean state of the tank entity's life.
Implements Deletable.
Definition at line 127 of file Tank.cpp.
References _collidedStatus.
Referenced by TEST().
{
    return _collidedStatus;
}
void Tank::moveBackward () [virtual]
Backward movement for a tank entity.
Moves the tank forward by a constant value.
This method uses trigonometry to move the tank negatively in any 360 degree direction within the game world
Implements Movable.
Definition at line 63 of file Tank.cpp.
References _rotation, _tank, Movable::_tankMovementSpeed, Orientation::move(), and PI.
Referenced by TEST().
{
    _tank.move(-_tankMovementSpeed*cos((_rotation*
      PI)/180.0), -_tankMovementSpeed*sin((_rotation*PI)/180.0));
}
void Tank::moveForward () [virtual]
Forward movement for a tank entity.
Moves the tank forward by a constant value.
This method uses trigonometry to move the tank positively in any 360 degree direction within the game world
Implements Movable.
Definition at line 53 of file Tank.cpp.
References _rotation, _tank, Movable::_tankMovementSpeed, Orientation::move(), and PI.
Referenced by TEST().
{
    _tank.move(_tankMovementSpeed*cos((_rotation*
      PI)/180.0), _tankMovementSpeed*sin((_rotation*PI)/180.0));
}
void Tank::rotateLeft () [virtual]
Left rotation for a tank entity.
Rotates the tank left by a constant value.
This method uses trigonometry to move the tank positively in any degree if rotation
Implements Movable.
Definition at line 71 of file Tank.cpp.
References _rotation, _tank, Movable::_tankRotationSpeed, and Orientation::rotate().
Referenced by TEST().
{
    _rotation += _tankRotationSpeed;
    _tank.rotate(_tankRotationSpeed);
}
void Tank::rotateRight () [virtual]
Right rotation for a tank entity.
Rotates the tank right by a constant value.
This method uses trigonometry to move the tank negatively in any degree if rotation
Implements Movable.
Definition at line 81 of file Tank.cpp.
References _rotation, _tank, Movable::_tankRotationSpeed, and Orientation::rotate().
Referenced by TEST().
{
    _rotation -= _tankRotationSpeed;
    _tank.rotate(-_tankRotationSpeed);
}
const int Tank::setBlocked (const blocked_status obstruction_type) [virtual]
Instruct the tank entity that it cannot move.
Set the movement state of the Tank to be blocked.
This function sets a boolean value and returns an int describing how manay more times it can be blocked
Parameters
obstruction_type :: this is the direction in which the tank becomes blocked
Implements Collidable.
Definition at line 101 of file Tank.cpp.
References _blockedStatus.
Referenced by TEST().
{
    _blockedStatus = obstruction_type;
    //Tank intity can be blocked infinitely.
    return 1;
}
void Tank::setCollided () [virtual]
Instruct the tank entity that it has collided with another object.
Implements Collidable.
Definition at line 115 of file Tank.cpp.
References _collidedStatus.
Referenced by TEST().
{
    _collidedStatus = 1;
}
void Tank::setMovementDirection (const movement_direction Movement_input) [virtual]
Set the movement direction of the entity.
Implements Movable.
Definition at line 180 of file Tank.cpp.
References _tank, and Orientation::setMoveDirection().
{
    _tank.setMoveDirection(Movement_input);
}
void Tank::setUnblocked () [virtual]
Instruct the tank entity that it can move.
Implements Collidable.
Definition at line 109 of file Tank.cpp.
References _blockedStatus, and unblocked.
Referenced by TEST().
{
    _blockedStatus = unblocked;
}
Member Data Documentation
blocked_status Tank::_blockedStatus [private]
Movability of the Tank entity: 1 for blocked, 0 for free.
Definition at line 81 of file Tank.h.
Referenced by isBlocked(), setBlocked(), setUnblocked(), and Tank().
bool Tank::_collidedStatus [private]
Collision state of the Tank Entity: 1 for collided, 0 for not.
Definition at line 83 of file Tank.h.
Referenced by isDeleted(), setCollided(), and Tank().
float Tank::_rotation [private]
The angle of rotation for the Tank entity.
Definition at line 85 of file Tank.h.
Referenced by moveBackward(), moveForward(), rotateLeft(), and rotateRight().
SpriteDimensions Tank::_sprite_dimensions [private]
Tank Sprite Dimensions.
Definition at line 91 of file Tank.h.
Referenced by Tank().
Orientation Tank::_tank [private]
Co-ordinate system for the Tank.
Definition at line 87 of file Tank.h.
Referenced by getAlignedBoundingBox(), getBoundingBox(), getDrawPositionX(), getDrawPositionY(), getDrawRotation(), getOrientation(), getPositionX(), getPositionY(), getTrackingBoundingBox(), moveBackward(), moveForward(), rotateLeft(), rotateRight(), setMovementDirection(), and Tank().
entity_type Tank::_type [private]
Enumeration type defining the tank.
Definition at line 89 of file Tank.h.
Referenced by getType(), and Tank().
The documentation for this class was generated from the following files:
Tank.h
Tank.cpp