CollisionManager Class Reference
Manager class responsible for managing collisions.
#include <CollisionManager.h>
Public Member Functions
CollisionManager ()
void manage ()
Checks and sets the collision status of all game entities.
void addNewEntity (std::weak_ptr< Collidable > new_entity)
Add new entity to collidables.
virtual ~CollisionManager ()
Private Member Functions
const blocked_status getResultingBlockedStatus (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Set the collision or blocked states for a barrier collision.
void reviewCollisionStates (std::shared_ptr< Collidable > entity_sp, std::shared_ptr< Collidable > obstacle_sp, bool &entity_blocked_status)
Checks to see if two objects have collided base upon their bounding box locations and type.
void setCollisionStates (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Set collision state based on the types of entities that have collided.
void tankCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Implement logic when a tank has collided with a game entity.
void missileCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Implement logic when a missile has collided with a game entity.
void mineCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Implement logic when a mine has collided with a game entity.
void barrierCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Implement logic when a barrier has been collided with a game entity.
void turretCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Implement logic when a turret has collided with a game entity.
void turretMissileCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2)
Implement logic when a turret missile has collided with a game entity.
void resetBlockedState (std::shared_ptr< Collidable > &entity)
Resets the blocked states of blocks that were previously blocked, but are not colliding with anything.
void removeGarbage ()
Helper function to remove 'Dead' entities from collision manager.
Private Attributes
std::vector< std::weak_ptr
*
< Collidable > > _collidables
Pointers to all collidable entities within the game world.
Detailed Description
Manager class responsible for managing collisions.
Definition at line 20 of file CollisionManager.h.
Constructor & Destructor Documentation
CollisionManager::CollisionManager ()
Definition at line 15 of file CollisionManager.cpp.
{
}
CollisionManager::~CollisionManager () [virtual]
Definition at line 431 of file CollisionManager.cpp.
{
}
Member Function Documentation
void CollisionManager::addNewEntity (std::weak_ptr< Collidable > new_entity)
Add new entity to collidables.
A new entity is added to the private collidables vector, which is used in the main manage function.
Parameters
new_entity :: Entity to be added to collidables vector
Definition at line 109 of file CollisionManager.cpp.
References _collidables.
Referenced by Game::addCollidable(), main(), and TEST().
{
    _collidables.push_back(new_entity);
}
void CollisionManager::barrierCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Implement logic when a barrier has been collided with a game entity.
Parameters
entity_1 :: First entity that will have its status changed
entity_2 :: Second entity that will have its status changed
Definition at line 149 of file CollisionManager.cpp.
References blocked, getResultingBlockedStatus(), p1_mine, p1_missile, p1_tank, p2_mine, p2_missile, and p2_tank.
Referenced by setCollisionStates().
{
    switch(entity_2->getType())
    {
    case p1_tank:
        entity_2->setBlocked(blocked); // tank does not move
        break;
    case p2_tank:
        entity_2->setBlocked(blocked); // tank does not move
        break;
    case p1_missile:
        {
            entity_2->setBlocked(getResultingBlockedStatus(entity_2, entity_1));
      // missile rebounds
        }
        break;
    case p2_missile:
        {
            entity_2->setBlocked(getResultingBlockedStatus(entity_2, entity_1));
      // missile rebounds
        }
        break;
    case p1_mine:
        entity_2->setCollided();
        break;
    case p2_mine:
        entity_2->setCollided();
        break;
    default:
        break;
    }//Switch
}
const blocked_status CollisionManager::getResultingBlockedStatus (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Set the collision or blocked states for a barrier collision.
Parameters
entity_1 :: First entity that will have its status changed
entity_2 :: Second entity that will have its status changed
Returns
blocked_status
Definition at line 352 of file CollisionManager.cpp.
References GeometryEngine::getRelativePosition().
Referenced by barrierCollisionReaction(), and missileCollisionReaction().
{
    auto entity_collision_box = entity_1->getAlignedBoundingBox();
    auto object_collision_box = entity_2->getAlignedBoundingBox();
    GeometryEngine geometry_engine;
    return (geometry_engine.getRelativePosition(entity_collision_box,
      object_collision_box));
}
void CollisionManager::manage ()
Checks and sets the collision status of all game entities.
This is the main function of the CollisionManager. The manager iterates through all of the collidables and checks it against every other collidable to see if a collision has taken place. If an entity that needs to be compared to another entity is blocked, it's status is temporarily set as false so that a proper comparison can be made. This entity is the entity of the outer for loop.
Definition at line 27 of file CollisionManager.cpp.
References _collidables, removeGarbage(), and reviewCollisionStates().
Referenced by main(), Game::runAllManagers(), and TEST().
{
    //Clear all deleted entities from the _collidables vector
    removeGarbage();
    //Iterator at initial position within vector
    auto i = _collidables.begin();
    for (; i != _collidables.end(); ++i)
    {
        bool entity_blocked = false;
        std::weak_ptr<Collidable> entity_wp = (*i);
        //Convert weak_ptr to shared_ptr
        std::shared_ptr<Collidable> entity_sp = entity_wp.lock();
        //Loop through vector of itterators again
        auto j = _collidables.begin();
        for (; j != _collidables.end(); ++j)
        {
            if (i != j)
            {
                std::weak_ptr<Collidable> obstacle_wp = (*j);
                //Convert weak_ptr to shared_ptr
                std::shared_ptr<Collidable> obstacle_sp = obstacle_wp.lock();
                reviewCollisionStates(entity_sp, obstacle_sp, entity_blocked);
            }// if
        }//inner-for
    }//outer-for
}//Manage function
void CollisionManager::mineCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Implement logic when a mine has collided with a game entity.
Parameters
entity_1 :: First entity that will have its status changed
entity_2 :: Second entity that will have its status changed
Definition at line 191 of file CollisionManager.cpp.
References barrier, p1_mine, p1_tank, p2_mine, p2_tank, and turret.
Referenced by setCollisionStates().
{
    switch(entity_2->getType())
    {
    case p1_tank:
        entity_1->setCollided(); // mine
        entity_2->setCollided(); // tank
        break;
    case p2_tank:
        entity_1->setCollided(); // mine
        entity_2->setCollided(); // tank
        break;
    case barrier:
        entity_1->setCollided(); //mine
        break;
    case turret:
        entity_1->setCollided();
        break;
    case p1_mine:
        entity_1->setCollided();
    case p2_mine:
        entity_1->setCollided();
    default:
        break;
    }
}
void CollisionManager::missileCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Implement logic when a missile has collided with a game entity.
Parameters
entity_1 :: First entity that will have its status changed
entity_2 :: Second entity that will have its status changed
Definition at line 228 of file CollisionManager.cpp.
References barrier, getResultingBlockedStatus(), p1_missile, p1_tank, p2_missile, p2_tank, and turret.
Referenced by setCollisionStates().
{
    switch(entity_2->getType())
    {
    case p1_tank:
        entity_1->setCollided(); // missile
        entity_2->setCollided(); // tank
        break;
    case p2_tank:
        entity_1->setCollided(); // missile
        entity_2->setCollided(); // tank
        break;
    case turret:
        entity_1->setCollided(); // turret
        entity_2->setCollided(); // missile
    case p1_missile:
        entity_1->setCollided(); // missile
        entity_2->setCollided(); // missile
        break;
    case p2_missile:
        entity_1->setCollided(); // missile
        entity_2->setCollided(); // missile
        break;
    case barrier:
        if (entity_1->setBlocked(getResultingBlockedStatus(entity_1, entity_2)) <=
       0) // missile
            entity_1->setCollided();
        break;
    default:
        break;
    }
}
void CollisionManager::removeGarbage () [private]
Helper function to remove 'Dead' entities from collision manager.
Definition at line 411 of file CollisionManager.cpp.
References _collidables.
Referenced by manage().
{
    auto removal = _collidables.begin();
    for (; removal != _collidables.end();)
    {
        std::weak_ptr<Collidable> removal_wp = (*removal);
        //Convert weak_ptr to shared_ptr
        std::shared_ptr<Collidable> removal_sp = removal_wp.lock();
        //Test if pointer still valid
        if(removal_sp)
        {
            removal++;
        }
        else
        {
            _collidables.erase(removal);
        }
    }
}
void CollisionManager::resetBlockedState (std::shared_ptr< Collidable > & entity) [private]
Resets the blocked states of blocks that were previously blocked, but are not colliding with anything.
Parameters
entity :: entity whose blocked state will be changed
Definition at line 99 of file CollisionManager.cpp.
Referenced by reviewCollisionStates().
{
    entity->setUnblocked();
}
void CollisionManager::reviewCollisionStates (std::shared_ptr< Collidable > entity_sp, std::shared_ptr< Collidable > obstacle_sp, bool & entity_blocked_status) [private]
Checks to see if two objects have collided base upon their bounding box locations and type.
This function excludes barriers. All other entities will have their collision states reviewed. The points of the four corners of each entity are used to test if there is a collision.
Parameters
entity_sp :: Shared pointer to one entity
obstacle_sp :: Shared pointer to the other entity
entity_blocked_status :: blocked status of entity that is being compared to every other entity
Definition at line 121 of file CollisionManager.cpp.
References barrier, GeometryEngine::isCollision(), resetBlockedState(), and setCollisionStates().
Referenced by manage().
{
    //This excludes comparing barrier collisions
    if ((obstacle_sp->getType() != barrier) || (entity_sp->getType() !=
      barrier))
    {
        const rect_corners& entity_box = (entity_sp)->getBoundingBox();
        const rect_corners& obstacle_box = (obstacle_sp)->getBoundingBox();
        GeometryEngine geometry_engine;// utilise the geometry engine
        if (geometry_engine.isCollision(entity_box, obstacle_box))
        {
            entity_blocked_status = true;
            setCollisionStates(entity_sp, obstacle_sp);
        }
        if (!entity_blocked_status)
        {
            resetBlockedState(entity_sp);
        }
    }//Barrier comparison if
}
void CollisionManager::setCollisionStates (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Set collision state based on the types of entities that have collided.
Different rules for collision apply to different game entities. Different collision functions are run based on what entities have collided. Rules for collision can be changed or added here.
Parameters
entity_1 :: First entity whose collision state will be set
entity_2 :: Second entity whose collision state will be set
Definition at line 64 of file CollisionManager.cpp.
References barrier, barrierCollisionReaction(), mineCollisionReaction(), missileCollisionReaction(), p1_mine, p1_missile, p1_tank, p2_mine, p2_missile, p2_tank, tankCollisionReaction(), turret, turret_missile, turretCollisionReaction(), and turretMissileCollisionReaction().
Referenced by reviewCollisionStates().
{
    if ((entity_1->getType() == p1_tank) || (entity_1->getType() ==
      p2_tank))
    {
        tankCollisionReaction(entity_1,entity_2);
    }
    else if ((entity_1->getType() == p1_missile) ||(entity_1->getType() ==
      p2_missile))
    {
        missileCollisionReaction(entity_1,entity_2);
    }
    else if ((entity_1->getType() == p1_mine) || (entity_1->getType() ==
      p2_mine))
    {
        mineCollisionReaction(entity_1,entity_2);
    }
    else if (entity_1->getType() == barrier)
    {
        barrierCollisionReaction(entity_1,entity_2);
    }//Else
    else if (entity_1->getType() == turret)
    {
        turretCollisionReaction(entity_1,entity_2);
    }//Else
        else if (entity_1->getType() == turret_missile)
    {
        turretMissileCollisionReaction(entity_1,entity_2);
    }//Else
}//Function
void CollisionManager::tankCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Implement logic when a tank has collided with a game entity.
Parameters
entity_1 :: First entity that will have its status changed
entity_2 :: Second entity that will have its status changed
Definition at line 270 of file CollisionManager.cpp.
References barrier, blocked, p1_mine, p1_missile, p1_tank, p2_mine, p2_missile, p2_tank, and turret.
Referenced by setCollisionStates().
{
    switch(entity_2->getType())
    {
    case p1_tank:
        entity_1->setBlocked(blocked); // tank
        break;
    case p2_tank:
        entity_1->setBlocked(blocked); // tank
        break;
    case turret:
        entity_1->setBlocked(blocked);
        break;
    case p1_missile:
        entity_1->setCollided(); // tank
        entity_2->setCollided(); // missile
        break;
    case p2_missile:
        entity_1->setCollided(); // tank
        entity_2->setCollided(); // missile
        break;
    case p1_mine:
        entity_1->setCollided(); // tank
        entity_2->setCollided(); // mine
        break;
    case p2_mine:
        entity_1->setCollided(); // tank
        entity_2->setCollided(); // mine
        break;
    case barrier:
        entity_1->setBlocked(blocked); // tank
        break;
    default:
        break;
    }
}
void CollisionManager::turretCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Implement logic when a turret has collided with a game entity.
Parameters
entity_1 :: First entity that will have its status changed
entity_2 :: Second entity that will have its status changed
Definition at line 319 of file CollisionManager.cpp.
References blocked, p1_missile, p1_tank, p2_missile, and p2_tank.
Referenced by setCollisionStates().
{
    switch(entity_2->getType())
    {
    case p1_tank:
        entity_2->setBlocked(blocked); // tank does not move
        break;
    case p2_tank:
        entity_2->setBlocked(blocked); // tank does not move
        break;
    case p1_missile:
        entity_1->setCollided();
        entity_2->setCollided();
        break;
    case p2_missile:
        entity_1->setCollided();
        entity_2->setCollided();
        break;
    default:
        break;
    }//Switch
}
void CollisionManager::turretMissileCollisionReaction (std::shared_ptr< Collidable > entity_1, std::shared_ptr< Collidable > entity_2) [private]
Implement logic when a turret missile has collided with a game entity.
Parameters
entity_1 :: First entity that will have its status changed
entity_2 :: Second entity that will have its status changed
Definition at line 364 of file CollisionManager.cpp.
References barrier, p1_mine, p1_missile, p1_tank, p2_mine, p2_missile, p2_tank, and turret_missile.
Referenced by setCollisionStates().
{
    switch(entity_2->getType())
    {
    case p1_tank:
        entity_1->setCollided();
        entity_2->setCollided();
        break;
    case p2_tank:
        entity_1->setCollided();
        entity_2->setCollided();
        break;
    case p1_missile:
        entity_1->setCollided();
        entity_2->setCollided();
        break;
    case p2_missile:
        entity_1->setCollided();
        entity_2->setCollided();
        break;
    case barrier:
        entity_1->setCollided();
        break;
    case p1_mine:
        break; //Do nothing
    case p2_mine:
        break; //Do nothing
    case turret_missile:
        entity_1->setCollided();
        entity_2->setCollided();
        break;
    default:
        break;
    }//Switch
}
Member Data Documentation
std::vector<std::weak_ptr<Collidable> > CollisionManager::_collidables [private]
Pointers to all collidable entities within the game world.
Definition at line 30 of file CollisionManager.h.
Referenced by addNewEntity(), manage(), and removeGarbage().
The documentation for this class was generated from the following files:
CollisionManager.h
CollisionManager.cpp