Barrier Class Reference
#include <Barrier.h>
Public Member Functions
Barrier (float positionX, float positionY, entity_type barrierTypeSet)
Barrier entity constructor.
virtual const entity_type & getType () const
Barrier is able to provide its identification.
virtual const rect_corners & getBoundingBox ()
Provide the bounding box for the Barrier entity.
virtual const rect_corners & getAlignedBoundingBox ()
Get Axis Aligned bounding box of entity.
virtual const int setBlocked (const blocked_status obstruction_type)
This function is not used by barrier.
virtual void setUnblocked ()
This function is not used by barrier.
virtual void setCollided ()
This function may be implmented later**.
virtual const bool isDeleted ()
Boolean state of the barrier entities life.
virtual const float getDrawPositionX ()
Retrieve the Barrier x Position.
virtual const float getDrawPositionY ()
Retrieve the Barrier y Position.
virtual const float getDrawRotation ()
Recieve the Barrier rotation.
virtual ~Barrier ()
Destructor for the Barrrier entity.
Private Attributes
Orientation _barrier
Co-cordinate system for Barrier entity.
entity_type _type
Enumeration type defining the Barrier.
SpriteDimensions _sprite_dimensions
Dimensions of Barrier.
Detailed Description
Definition at line 25 of file Barrier.h.
Constructor & Destructor Documentation
Barrier::Barrier (float positionX, float positionY, entity_type barrierTypeSet)
Barrier entity constructor.
Constructor for Barrier class.
Default constructor for the Orientation class
Parameters
positionX :: The initial x-coordinate of the barrier object
positionY :: The initial y-coordinate of the barrier object
barrierTypeSet :: An Enum to provide the barrier a specific classification.
Definition at line 20 of file Barrier.cpp.
References _barrier, _sprite_dimensions, _type, barrier, SpriteDimensions::barrier_sprite_x, SpriteDimensions::barrier_sprite_y, Orientation::setHeight(), and Orientation::setWidth().
                                                                            :
    _sprite_dimensions(),
    _barrier(positionX,positionY,0,0,0.0,false)
{
    if(positionX < 0) throw InvalidConstructorArgumentsBarrier();
    if(positionY < 0) throw InvalidConstructorArgumentsBarrier();
    if(barrierTypeSet != barrier) throw
      InvalidConstructorArgumentsBarrier();
    _barrier.setWidth(_sprite_dimensions.
      barrier_sprite_x);
    _barrier.setHeight(_sprite_dimensions.
      barrier_sprite_y);
    _type = barrierTypeSet;
}
Barrier::~Barrier () [virtual]
Destructor for the Barrrier entity.
Destructor for Barrier.
Default destructor
Definition at line 131 of file Barrier.cpp.
{
}
Member Function Documentation
const rect_corners & Barrier::getAlignedBoundingBox () [virtual]
Get Axis Aligned bounding box of entity.
Function used to calculate the axis-aligned (simplified) bounding box of the Barrier entity.
The bounding box of the entity is calculated by taking its orientation components and extending four four verticies outwards from its origin
Returns
const rect_corners
Implements Collidable.
Definition at line 58 of file Barrier.cpp.
References _barrier, and Orientation::getAlignedGlobalBounds().
{
    return _barrier.getAlignedGlobalBounds();
}
const rect_corners & Barrier::getBoundingBox () [virtual]
Provide the bounding box for the Barrier entity.
Function used to calculate the non-axis-aligned (complex) bounding box of the Barrier entity.
The bounding box of the entity is calculated by extending its origin by the value of of its width and height projected along trigonometric co-ordinates
Returns
const rect_corners
Implements Collidable.
Definition at line 48 of file Barrier.cpp.
References _barrier, and Orientation::getGlobalBounds().
Referenced by TEST().
{
    return _barrier.getGlobalBounds();
}
const float Barrier::getDrawPositionX () [virtual]
Retrieve the Barrier x Position.
Retrieve the x-coordinate of the barrier object.
This function is used by the DrawManager to gather the barriers x draw ordinal information
Returns
const float
Implements Deletable.
Definition at line 105 of file Barrier.cpp.
References _barrier, and Orientation::getOriginX().
Referenced by TEST().
{
    return _barrier.getOriginX();
}
const float Barrier::getDrawPositionY () [virtual]
Retrieve the Barrier y Position.
Retrieve the y-coordinate of the barrier object.
This function is used by the DrawManager to gather the barriers y draw ordinal information
Returns
const float
Implements Deletable.
Definition at line 114 of file Barrier.cpp.
References _barrier, and Orientation::getOriginY().
Referenced by TEST().
{
    return _barrier.getOriginY();
}
const float Barrier::getDrawRotation () [virtual]
Recieve the Barrier rotation.
Retrieve the barrier objects rotation.
This function is used by the DrawManager to record the rotation of a barrier sprite it creates
Returns
const float
Implements Deletable.
Definition at line 123 of file Barrier.cpp.
References _barrier, and Orientation::getRotation().
Referenced by TEST().
{
    return _barrier.getRotation();
}
const entity_type & Barrier::getType () const [virtual]
Barrier is able to provide its identification.
Return the entity type of the Barrier object.
This function is used extensively by managers to distinguish various clustered entities from one another.
Returns
entity_type :: An Enum representing the barrier type in this instance
Implements Deletable.
Definition at line 38 of file Barrier.cpp.
References _type.
Referenced by TEST().
{
    return _type;
}
const bool Barrier::isDeleted () [virtual]
Boolean state of the barrier entities life.
Function used to delete a barrier.
Barriers currently are not deleted within the game main management loop, however this function provides the scope to do so with destructable barriers.
Returns
const bool
Implements Deletable.
Definition at line 96 of file Barrier.cpp.
{
    return 0;
}
const int Barrier::setBlocked (const blocked_status obstruction_type) [virtual]
This function is not used by barrier.
This function is not currently used by the Barrier class.
Scope exists within this fucnction to add damaging effects to barriers as this method is called within the collision manager
Parameters
obstruction_type :: an Enum describing the direction in which the barrier is blocked
Returns
const int
Implements Collidable.
Definition at line 69 of file Barrier.cpp.
{
    return 1;
}
void Barrier::setCollided () [virtual]
This function may be implmented later**.
This function is not currently used by the Barrier class.
This can be used to assign a fatal state to a barrier after it has recieved critical damage
Implements Collidable.
Definition at line 86 of file Barrier.cpp.
{
}
void Barrier::setUnblocked () [virtual]
This function is not used by barrier.
This function is not currently used by the Barrier class.
Barriers currently cannot become blocked but this function can be implemented to add an effect of regenerative barriers which can be broken over time
Implements Collidable.
Definition at line 78 of file Barrier.cpp.
{
}
Member Data Documentation
Orientation Barrier::_barrier [private]
Co-cordinate system for Barrier entity.
Definition at line 58 of file Barrier.h.
Referenced by Barrier(), getAlignedBoundingBox(), getBoundingBox(), getDrawPositionX(), getDrawPositionY(), and getDrawRotation().
SpriteDimensions Barrier::_sprite_dimensions [private]
Dimensions of Barrier.
Definition at line 62 of file Barrier.h.
Referenced by Barrier().
entity_type Barrier::_type [private]
Enumeration type defining the Barrier.
Definition at line 60 of file Barrier.h.
Referenced by Barrier(), and getType().
The documentation for this class was generated from the following files:
Barrier.h
Barrier.cpp