GameStateManager Class Reference
Manager class responsible for managing state of the game.
#include <GameStateManager.h>
Public Member Functions
GameStateManager ()
Constructor for GameStateManager.
void manage (GameManagementData &game_data_container)
Main manage function.
~GameStateManager ()
Private Member Functions
void manageAttackTimers (ActionData &action_data_container)
Manage the timers that keep track of firing and laying mines intervals.
bool timeRunOut (StopWatch &timer)
Checks timeout for specific timer.
Private Attributes
StopWatch _game_timer
Keeps track of the overall game time.
StopWatch _p1_fire_timer
Keep tracks of time between firing of missiles for player 1.
StopWatch _p2_fire_timer
Keep tracks of time between firing of missiles for player 2.
StopWatch _p1_lay_mine_timer
Keeps track of time between laying mines for player 1.
StopWatch _p2_lay_mine_timer
Keeps track of time between laying mines for player 2.
const double _game_runtime = 120.0
The time in seconds of how long the game will last.
const double _attack_time_limit = 0.5
Time limit between firing or laying mines for tanks.
Detailed Description
Manager class responsible for managing state of the game.
Definition at line 23 of file GameStateManager.h.
Constructor & Destructor Documentation
GameStateManager::GameStateManager ()
Constructor for GameStateManager.
Initialises the timer for the whole game.
Definition at line 17 of file GameStateManager.cpp.
References _game_timer, and StopWatch::start().
{
    _game_timer.start();
}
GameStateManager::~GameStateManager ()
Definition at line 105 of file GameStateManager.cpp.
{
}
Member Function Documentation
void GameStateManager::manage (GameManagementData & game_data_container)
Main manage function.
The amount of elapsed time is obtained by getting the timer value and subtracting that from the game runtime variable. Once that timer runs out, the game state will be set to finished. Otherwise the current game time is set. Attack timers are also run.
Parameters
game_data_container :: Information that holds the game time which will be changed accordingly
Definition at line 28 of file GameStateManager.cpp.
References _game_runtime, _game_timer, StopWatch::getTimerValue(), StopWatch::isRunning(), manageAttackTimers(), GameManagementData::setGameFinished(), GameManagementData::setGameTime(), StopWatch::start(), and StopWatch::stop().
Referenced by Game::runAllManagers(), and TEST().
{
    if (!_game_timer.isRunning())
        _game_timer.start();
    double current_time = _game_runtime - _game_timer.
      getTimerValue();// makes the timer countdown
    if (current_time <= 0)
    {
        _game_timer.stop();
        game_data_container.setGameFinished(); // finish the game
    }
    else
        game_data_container.setGameTime(current_time);
    manageAttackTimers(game_data_container);
}
void GameStateManager::manageAttackTimers (ActionData & game_data_container) [private]
Manage the timers that keep track of firing and laying mines intervals.
Both players' timers are checked. If their time for firing has run out then thay may fire another missile, or lay another mine.
Parameters
game_data_container :: Information about whhat attacks the players' desire
Definition at line 51 of file GameStateManager.cpp.
References _p1_fire_timer, _p1_lay_mine_timer, _p2_fire_timer, _p2_lay_mine_timer, fire_missile, ActionData::giveActionInfo(), lay_mine, ActionData::resetP1Attack(), ActionData::resetP2Attack(), and timeRunOut().
Referenced by manage().
{
    auto actions = game_data_container.giveActionInfo();
    if (actions.attack_1 == fire_missile)
    {
        if (!timeRunOut(_p1_fire_timer))
            game_data_container.resetP1Attack();
    }
    if (actions.attack_2 == fire_missile)
    {
        if (!timeRunOut(_p2_fire_timer))
            game_data_container.resetP2Attack();
    }
    if (actions.attack_1 == lay_mine)
    {
        if (!timeRunOut(_p1_lay_mine_timer))
            game_data_container.resetP1Attack();
    }
    if (actions.attack_2 == lay_mine)
    {
        if (!timeRunOut(_p2_lay_mine_timer))
            game_data_container.resetP2Attack();
    }
}
bool GameStateManager::timeRunOut (StopWatch & timer) [private]
Checks timeout for specific timer.
If the timer is not running yet, then it is started. If it has started, the attack time is calculated.
Parameters
timer :: timer to be checked
Returns
bool
Definition at line 87 of file GameStateManager.cpp.
References _attack_time_limit, StopWatch::getTimerValue(), StopWatch::isRunning(), StopWatch::reset(), and StopWatch::start().
Referenced by manageAttackTimers().
{
    if (!timer.isRunning())
    {
        timer.start();
        return true;
    }
    double timer_time = _attack_time_limit - timer.
      getTimerValue();
    if (timer_time <= 0)
    {
        timer.reset();
        return true;
    }
    else return false;
}
Member Data Documentation
const double GameStateManager::_attack_time_limit = 0.5 [private]
Time limit between firing or laying mines for tanks.
Definition at line 44 of file GameStateManager.h.
Referenced by timeRunOut().
const double GameStateManager::_game_runtime = 120.0 [private]
The time in seconds of how long the game will last.
Definition at line 42 of file GameStateManager.h.
Referenced by manage().
StopWatch GameStateManager::_game_timer [private]
Keeps track of the overall game time.
Definition at line 32 of file GameStateManager.h.
Referenced by GameStateManager(), and manage().
StopWatch GameStateManager::_p1_fire_timer [private]
Keep tracks of time between firing of missiles for player 1.
Definition at line 34 of file GameStateManager.h.
Referenced by manageAttackTimers().
StopWatch GameStateManager::_p1_lay_mine_timer [private]
Keeps track of time between laying mines for player 1.
Definition at line 38 of file GameStateManager.h.
Referenced by manageAttackTimers().
StopWatch GameStateManager::_p2_fire_timer [private]
Keep tracks of time between firing of missiles for player 2.
Definition at line 36 of file GameStateManager.h.
Referenced by manageAttackTimers().
StopWatch GameStateManager::_p2_lay_mine_timer [private]
Keeps track of time between laying mines for player 2.
Definition at line 40 of file GameStateManager.h.
Referenced by manageAttackTimers().
The documentation for this class was generated from the following files:
GameStateManager.h
GameStateManager.cpp