MoveManager Class Reference
#include <MoveManager.h>
Public Member Functions
MoveManager ()
Constructor.
void manage (const ActionData &action_data_container)
Move all movable entities within the world.
void addNewEntity (std::weak_ptr< Movable > new_entity)
Add Movable-type shared_ptr's to the MoveManagers internal data members.
virtual ~MoveManager ()
Destructor for MoveManager.
Private Member Functions
void removeGarbage ()
Removes all deleted entities from move manager.
Private Attributes
std::vector< std::weak_ptr
*
< Movable > > _movables
Detailed Description
Definition at line 21 of file MoveManager.h.
Constructor & Destructor Documentation
MoveManager::MoveManager ()
Constructor.
This constructor is minimal. Entities are associated to MoveManager through the addNewEntities function
Definition at line 18 of file MoveManager.cpp.
{
}
MoveManager::~MoveManager () [virtual]
Destructor for MoveManager.
Destructor.
No further implementation defined
Definition at line 26 of file MoveManager.cpp.
{
}
Member Function Documentation
void MoveManager::addNewEntity (std::weak_ptr< Movable > new_entity)
Add Movable-type shared_ptr's to the MoveManagers internal data members.
Used to add new weak pointer instances to the MoveManager private vector.
This function allows for new entities to be passed and managed by the MovementManager by adding the weak pointers of created Movable objects to the classes private vector.
Definition at line 229 of file MoveManager.cpp.
References _movables.
Referenced by Game::addMovable(), main(), and TEST().
{
    _movables.push_back(new_entity);
}
void MoveManager::manage (const ActionData & action_data_container)
Move all movable entities within the world.
The MoveManager Logical Management function.
The function works by evaluating the private vector of weak_pointers stored within MoveManager and determining if each one can move or not. A 'blocked' status wil result in an object not being able to move (or it will be reflected in the case of a missile)
Parameters
action_data_contatiner :: a data container with all relevant move info for the current management cycle.
Definition at line 38 of file MoveManager.cpp.
References _movables, blocked_horizontally, blocked_vertically, actions_info::change_1, actions_info::change_2, do_nothing, forward, ActionData::giveActionInfo(), actions_info::move_1, actions_info::move_2, moveBackward, moveForward, p1_missile, p1_tank, p2_missile, p2_tank, removeGarbage(), reverse, rotate_left, rotate_right, rotateLeft, rotateRight, turret_missile, and unblocked.
Referenced by main(), Game::runAllManagers(), and TEST().
{
    actions_info managerInstructions = action_data_container.
      giveActionInfo();
    //Remove any "corpses" found within the movable vector
    removeGarbage();
    auto moveables_iterator = _movables.begin();
    for(; moveables_iterator != _movables.end(); moveables_iterator++)
    {
        //Convert iterator to Weak pointer
        std::weak_ptr<Movable> entity_mov_wp = (*moveables_iterator);
        //Lock as Shared Pointer
        std::shared_ptr<Movable> entity_mov_sp = entity_mov_wp.lock();
        //Make changes to player 1's tank if movement has been captured
        if ((managerInstructions.change_1 == true) && (entity_mov_sp->getType() ==
      p1_tank))
        {
            if(entity_mov_sp->isBlocked() == unblocked)
            {
                switch(managerInstructions.move_1)
                {
                    case forward:
                        entity_mov_sp->moveForward();
                        entity_mov_sp->setMovementDirection(moveForward);
                        break;
                    case reverse:
                        entity_mov_sp->moveBackward();
                        entity_mov_sp->setMovementDirection(moveBackward);
                        break;
                    case rotate_left:
                        entity_mov_sp->rotateLeft();
                        entity_mov_sp->setMovementDirection(rotateLeft);
                        break;
                    case rotate_right:
                        entity_mov_sp->rotateRight();
                        entity_mov_sp->setMovementDirection(rotateRight);
                        break;
                    case do_nothing:
                        break;
                }
            }
            else //if the object is blocked
            {
                switch(managerInstructions.move_1)
                {
                    case forward:
                        entity_mov_sp->setMovementDirection(moveForward);
                    break;
                    case reverse:
                        entity_mov_sp->setMovementDirection(moveBackward);
                        break;
                    case rotate_left:
                        entity_mov_sp->setMovementDirection(rotateLeft);
                        break;
                    case rotate_right:
                        entity_mov_sp->setMovementDirection(rotateRight);
                    case do_nothing:
                        break;
                }
            }
        } // If for P1 tank
         //Make changes to player 2's tank if movement has been captured
        if ((managerInstructions.change_2 == true) && (entity_mov_sp->getType() ==
      p2_tank))
        {
            if(entity_mov_sp->isBlocked() == unblocked)
            {
                switch(managerInstructions.move_2)
                {
                  case forward:
                        entity_mov_sp->moveForward();
                        entity_mov_sp->setMovementDirection(moveForward);
                        break;
                    case reverse:
                        entity_mov_sp->moveBackward();
                        entity_mov_sp->setMovementDirection(moveBackward);
                        break;
                    case rotate_left:
                        entity_mov_sp->rotateLeft();
                        entity_mov_sp->setMovementDirection(rotateLeft);
                        break;
                    case rotate_right:
                        entity_mov_sp->rotateRight();
                        entity_mov_sp->setMovementDirection(rotateRight);
                        break;
                    case do_nothing:
                        break;
                }
            }
            else //if the object is blocked
            {
                switch(managerInstructions.move_2)
                {
                   case forward:
                        entity_mov_sp->setMovementDirection(moveForward);
                    break;
                    case reverse:
                        entity_mov_sp->setMovementDirection(moveBackward);
                        break;
                    case rotate_left:
                        entity_mov_sp->setMovementDirection(rotateLeft);
                        break;
                    case rotate_right:
                        entity_mov_sp->setMovementDirection(rotateRight);
                    case do_nothing:
                        break;
                }
            }
        }
        //Missiles will always move along their trajectory each management cycle
        //Exception if a missile hits a barrier
        //Missile has hit a barrier
        if (((entity_mov_sp->getType() == p1_missile) ||
            (entity_mov_sp->getType() == p2_missile) ||
            (entity_mov_sp->getType() == turret_missile))
             && (entity_mov_sp->isBlocked() == blocked_horizontally))
        {
            entity_mov_sp->rotateLeft();
            entity_mov_sp->moveForward();
        }
         if (((entity_mov_sp->getType() == p1_missile) ||
            (entity_mov_sp->getType() == p2_missile) ||
            (entity_mov_sp->getType() == turret_missile))
             && (entity_mov_sp->isBlocked() == blocked_vertically))
        {
            entity_mov_sp->rotateRight();
            entity_mov_sp->moveForward();
        }
        //Missile moves forward
        else if (((entity_mov_sp->getType() == p1_missile) ||
                 (entity_mov_sp->getType() == p2_missile) ||
                 (entity_mov_sp->getType() == turret_missile))
                 && (entity_mov_sp->isBlocked() == unblocked))
        {
            entity_mov_sp->moveForward();
        }
    }//Range-based for
}//Function
void MoveManager::removeGarbage () [private]
Removes all deleted entities from move manager.
This function uses the MoveManagers vector of weak pointers which are asked to lock to determine whether or not they still point to an existing object. It the object does not exist, it is erased from the MoveManager vector
Definition at line 204 of file MoveManager.cpp.
References _movables.
Referenced by manage().
{
    auto removable = _movables.begin();
    for (; removable != _movables.end();)
    {
        //Convert iterator to Weak pointer
        std::weak_ptr<Movable> removable_wp = (*removable);
        //Lock as Shared Pointer
        std::shared_ptr<Movable> removable_sp = removable_wp.lock();
        //Test to see if the shared pointer exists
        if (removable_sp)
        {
            removable++;
        }
        else
        {
            _movables.erase(removable);
        }
    }
}
Member Data Documentation
std::vector<std::weak_ptr<Movable> > MoveManager::_movables [private]
Definition at line 38 of file MoveManager.h.
Referenced by addNewEntity(), manage(), and removeGarbage().
The documentation for this class was generated from the following files:
MoveManager.h
MoveManager.cpp