Game Class Reference
Main class which runs the program loop.
#include <Game.h>
Public Member Functions
Game ()
Game object constructor.
void runWorld (std::shared_ptr< Display > display)
Main program loop.
~Game ()
Private Member Functions
void setupInitialMap ()
Sets up the game wolrd map.
void getMapData (std::vector< std::vector< char >> &map_vector, std::ifstream &map_grid_file)
Reads map data from text file.
void readMapData (const std::vector< std::vector< char >> &map_vector)
Reads the map data from the vector.
void checkKeyboardInput (ActionData &action_data_container)
Checks through all pressed control keys.
void runAllManagers (GameManagementData &game_data_container, std::shared_ptr< Display > display)
All managers manage.
void addNewWorldEntity (GameManagementData &game_data_container)
Any new game entity is added here.
void addNewTank (entity_type player_tank, float tank_positionX, float tank_positionY, float rotation)
Adds a new tank object.
void addNewMissile (std::shared_ptr< Deletable > missile_del_sp)
Adds a new missile object.
void addNewMine (std::shared_ptr< Deletable > mine_del_sp)
Adds a new mine object.
void addNewTurret (float turret_positionX, float turret_postionY, float rotation)
Adds a new turret object.
void manageRespawns (GameManagementData &game_data_container)
Manages when a respawn needs to take place.
void createBarrier (int x, int y)
Adds a new barrier object.
void addDeletable (std::shared_ptr< Deletable > deletable_sp)
Adds entity to deletables vector.
void addCollidable (std::shared_ptr< Deletable > collidable_sp)
Adds entity to collidables.
void addMovable (std::shared_ptr< Deletable > movable_sp)
Adds entity to movables.
void addTrackable (std::shared_ptr< Deletable > trackable_sp)
Adds entity to trackables.
void addTurretable (std::shared_ptr< Deletable > trackable_sp)
Adds entity to turrets.
Private Attributes
float _player1_startX
Player 1 starting x position.
float _player1_startY
Player 1 starting y position.
float _player2_startX
Player 2 starting x position.
float _player2_startY
Player 2 starting y position.
float _turret_startX
Turret starting x position.
float _turret_startY
Turret starting y position.
MoveManager _move_manager
Private object of the MoveManager.
CollisionManager _collision_manager
Private object of the CollisionManager.
TrackingManager _tracking_manager
Private object of the TrackingManager.
DrawManager _draw_manager
Private object of the DrawManager.
DestructionManager _destruction_manager
Private object of the DestructionManager.
GameStateManager _state_manager
Private object of the GameStateManager.
TurretManager _turret_manager
Private object of the TurretManager.
GameManagementData _game_management_data
Game runtime data.
SpriteDimensions _game_sprite_dimensions
Dimensions of all game sprites.
std::vector< std::weak_ptr
*
< Deletable > > _world_entities
Container for all entities on the game world.
std::string map_grid_filename = `map_grid.txt`
File name for the map grid text file.
Detailed Description
Main class which runs the program loop.
Definition at line 50 of file Game.h.
Constructor & Destructor Documentation
Game::Game ()
Game object constructor.
All private class objects are initialised here, including all the managers.
Definition at line 19 of file Game.cpp.
References _collision_manager, _destruction_manager, _draw_manager, _move_manager, _state_manager, _tracking_manager, and _turret_manager.
          :
    _game_sprite_dimensions(),
    _game_management_data()
{
    MoveManager _move_manager;
    CollisionManager _collision_manager;
    TrackingManager _tracking_manager;
    DrawManager _draw_manager;
    DestructionManager _destruction_manager;
    GameStateManager _state_manager;
    TurretManager _turret_manager;
}
Game::~Game ()
Definition at line 478 of file Game.cpp.
{
}
Member Function Documentation
void Game::addCollidable (std::shared_ptr< Deletable > deletable_sp) [private]
Adds entity to collidables.
Shared pointers are cast as weak pointers. These are then pushed back to the CollisionManager vector.
Parameters
deletable_sp :: Shared pointer to be cast as weak pointer
Definition at line 439 of file Game.cpp.
References _collision_manager, and CollisionManager::addNewEntity().
Referenced by addNewMine(), addNewMissile(), addNewTank(), addNewTurret(), and createBarrier().
{
    std::weak_ptr<Collidable> collidable_wp = std::dynamic_pointer_cast<
      Collidable>(deletable_sp);
    _collision_manager.addNewEntity(collidable_wp);
}
void Game::addDeletable (std::shared_ptr< Deletable > deletable_sp) [private]
Adds entity to deletables vector.
Shared pointers are cast as weak pointers. These are then pushed back to the DrawManager vector.
Parameters
deletable_sp :: Shared pointer to be cast as weak pointer
Definition at line 427 of file Game.cpp.
References _draw_manager, _world_entities, and DrawManager::addNewEntity().
Referenced by addNewMine(), addNewMissile(), addNewTank(), addNewTurret(), and createBarrier().
{
    std::weak_ptr<Deletable> deletable_wp = deletable_sp;
    _world_entities.push_back(deletable_wp);
    _draw_manager.addNewEntity(deletable_wp);
}
void Game::addMovable (std::shared_ptr< Deletable > movable_sp) [private]
Adds entity to movables.
Shared pointers are cast as weak pointers. These are then pushed back to the MoveManager vector.
Parameters
movable_sp :: Shared pointer to be cast as weak pointer
Definition at line 450 of file Game.cpp.
References _move_manager, and MoveManager::addNewEntity().
Referenced by addNewMissile(), and addNewTank().
{
    std::weak_ptr<Movable> movable_wp = std::dynamic_pointer_cast<Movable>(movable_sp);
    _move_manager.addNewEntity(movable_wp);
}
void Game::addNewMine (std::shared_ptr< Deletable > mine_del_sp) [private]
Adds a new mine object.
Tank objects are created as Deletables. Each mine is added to the DestructionManager vector. They exists here as shared pointers.
Parameters
mine_del_sp :: Shared pointer that points to the mine object
Definition at line 399 of file Game.cpp.
References _destruction_manager, addCollidable(), addDeletable(), and DestructionManager::addNewEntity().
Referenced by addNewWorldEntity().
{
    _destruction_manager.addNewEntity(mine_del_sp);
    addDeletable(mine_del_sp);
    addCollidable(mine_del_sp);
}
void Game::addNewMissile (std::shared_ptr< Deletable > missile_del_sp) [private]
Adds a new missile object.
Tank objects are created as Deletables. Each missile is added to the DestructionManager vector. They exists here as shared pointers.
Parameters
missile_del_sp :: Shared pointer that points to the missile object
Definition at line 385 of file Game.cpp.
References _destruction_manager, addCollidable(), addDeletable(), addMovable(), and DestructionManager::addNewEntity().
Referenced by addNewWorldEntity().
{
    _destruction_manager.addNewEntity(missile_del_sp);
    addDeletable(missile_del_sp);
    addCollidable(missile_del_sp);
    addMovable(missile_del_sp);
}
void Game::addNewTank (entity_type player_tank, float tank_positionX, float tank_positionY, float rotation) [private]
Adds a new tank object.
Tank objects are created as Deletables. Each tank is added to the _destruction_manager vector. They exists here as shared pointers.
Parameters
player_tank :: Information about which players tank is being created.
tank_positionX :: Tank x position
tank_positionY :: Tank y position
rotation :: Tanks current rotation angle
Definition at line 351 of file Game.cpp.
References _destruction_manager, addCollidable(), addDeletable(), addMovable(), DestructionManager::addNewEntity(), and addTrackable().
Referenced by manageRespawns(), and readMapData().
{
    std::shared_ptr<Deletable> new_tank_del_sp(new Tank(tank_positionX, tank_positionY,rotation,
      player_tank));
    _destruction_manager.addNewEntity(new_tank_del_sp);
    addDeletable(new_tank_del_sp);
    addCollidable(new_tank_del_sp);
    addMovable(new_tank_del_sp);
    addTrackable(new_tank_del_sp);
}
void Game::addNewTurret (float turret_postionX, float turret_positionY, float rotation) [private]
Adds a new turret object.
Tank objects are created as Deletables. Each turret is added to the _destruction_manager vector. They exists here as shared pointers.
Parameters
turret_postionX :: Turret x position
turret_positionY :: Turret y position
rotation :: Turrets current rotation angle
Definition at line 369 of file Game.cpp.
References _destruction_manager, addCollidable(), addDeletable(), DestructionManager::addNewEntity(), addTrackable(), and addTurretable().
Referenced by readMapData().
{
    std::shared_ptr<Deletable> new_turret_del_sp(new Turret(turret_postionX, turret_positionY,
      rotation));
    _destruction_manager.addNewEntity(new_turret_del_sp);
    addDeletable(new_turret_del_sp);
    addCollidable(new_turret_del_sp);
    addTrackable(new_turret_del_sp);
    addTurretable(new_turret_del_sp);
}
void Game::addNewWorldEntity (GameManagementData & game_data_container) [private]
Any new game entity is added here.
This also includes respawns of tanks that have been destroyed. This function checks all actions that a user has executed and creates a new entity accordinly. For example, firing a missile or laying a tank would cause a new entity to be created. This function requires a lot of refactoring as it is too long and there are repetitions in several instances.
Parameters
game_data_container :: Data about what is happening at this point in the game.
Definition at line 244 of file Game.cpp.
References _game_sprite_dimensions, _tracking_manager, addNewMine(), addNewMissile(), actions_info::attack_1, actions_info::attack_2, actions_info::change_1, actions_info::change_2, fire_missile, TrackingManager::getP1PositionX(), TrackingManager::getP1PositionY(), TrackingManager::getP1Rotation(), TrackingManager::getP2PositionX(), TrackingManager::getP2PositionY(), TrackingManager::getP2Rotation(), TrackingManager::getTurretPositionsX(), TrackingManager::getTurretPositionsY(), TrackingManager::getTurretRotations(), GameManagementData::giveActionInfo(), lay_mine, manageRespawns(), SpriteDimensions::mine_creation_offset, SpriteDimensions::missile_creation_offset, p1_mine, p1_missile, p2_mine, p2_missile, PI, GameManagementData::resetTurretFire(), SpriteDimensions::tank_sprite_y, actions_info::turret_fire, and turret_missile.
Referenced by runWorld().
{
    actions_info actions = game_data_container.giveActionInfo();
    manageRespawns(game_data_container);
    //Offset for creating a missile
    const float missile_offset = _game_sprite_dimensions.
      tank_sprite_y/2 + _game_sprite_dimensions.
      missile_creation_offset;
    //Offset for creating a mine
    const float mine_offset = _game_sprite_dimensions.
      tank_sprite_y/2 + _game_sprite_dimensions.
      mine_creation_offset;
    if (actions.turret_fire)
    {
        auto turret_xPos_vec = _tracking_manager.
      getTurretPositionsX();
        auto turret_yPos_vec = _tracking_manager.
      getTurretPositionsY();
        auto turret_rotation_vec = _tracking_manager.
      getTurretRotations();
        for(int i = 0; i!= turret_xPos_vec.size(); i++)
        {
            const float tur_x_component = cos((turret_rotation_vec[i]*PI)/180);
            const float tur_y_component = sin((turret_rotation_vec[i]*PI)/180);
            std::shared_ptr<Deletable> tur_missile_del_sp(new Missile(turret_xPos_vec[i] +
      tur_x_component*missile_offset,
                                                                    turret_yPos_vec[i] + tur_y_component*
      missile_offset,
                                                                    turret_rotation_vec[i],
      turret_missile));
            addNewMissile(tur_missile_del_sp);
        }
        game_data_container.resetTurretFire();
    }
    if (actions.change_1 == true)
    {
        const float p1_x_component = cos((_tracking_manager.
      getP1Rotation()*PI)/180);
        const float p1_y_component = sin((_tracking_manager.
      getP1Rotation()*PI)/180);
        if (actions.attack_1 == fire_missile)
        { // will use addNewMissile
            std::shared_ptr<Deletable> p1_missile_del_sp(new Missile(
      _tracking_manager.getP1PositionX() + p1_x_component*missile_offset,
                                                                    
      _tracking_manager.getP1PositionY() + p1_y_component*missile_offset,
                                                                    
      _tracking_manager.getP1Rotation(), p1_missile));
            addNewMissile(p1_missile_del_sp);
        }
        if (actions.attack_1 == lay_mine)
        { // will use addNewMine
            std::shared_ptr<Deletable> p1_mine_del_sp(new Mine(
      _tracking_manager.getP1PositionX() - p1_x_component*mine_offset,
                                                               _tracking_manager.
      getP1PositionY() - p1_y_component*mine_offset,
                                                               p1_mine));
            addNewMine(p1_mine_del_sp);
        }
    }
    if (actions.change_2 == true)
    {
        const float p2_x_component = cos((_tracking_manager.
      getP2Rotation()*PI)/180);
        const float p2_y_component = sin((_tracking_manager.
      getP2Rotation()*PI)/180);
        if (actions.attack_2 == fire_missile)
        { // will use addNewMissile
            std::shared_ptr<Deletable> p2_missile_del_sp(new Missile(
      _tracking_manager.getP2PositionX() + p2_x_component*missile_offset,
                                                                    
      _tracking_manager.getP2PositionY() + p2_y_component*missile_offset,
                                                                    
      _tracking_manager.getP2Rotation(), p2_missile));
            addNewMissile(p2_missile_del_sp);
        }
        if (actions.attack_2 == lay_mine)
        { // will use addNewMine
            std::shared_ptr<Deletable> p2_mine_del_sp(new Mine(
      _tracking_manager.getP2PositionX() - p2_x_component*mine_offset,
                                                               _tracking_manager.
      getP2PositionY() - p2_y_component*mine_offset,
                                                               p2_mine));
            addNewMine(p2_mine_del_sp);
        }
    }
    return;
}
void Game::addTrackable (std::shared_ptr< Deletable > trackable_sp) [private]
Adds entity to trackables.
Shared pointers are cast as weak pointers. These are then pushed back to the TrackingManager vector.
Parameters
trackable_sp :: Shared pointer to be cast as weak pointer
Definition at line 461 of file Game.cpp.
References _tracking_manager, and TrackingManager::addNewEntity().
Referenced by addNewTank(), and addNewTurret().
{
    std::weak_ptr<Trackable> trackable_wp = std::dynamic_pointer_cast<Trackable>(trackable_sp);
    _tracking_manager.addNewEntity(trackable_wp);
}
void Game::addTurretable (std::shared_ptr< Deletable > turret_sp) [private]
Adds entity to turrets.
Shared pointers are cast as weak pointers. These are then pushed back to the TurretManager vector.
Parameters
turret_sp :: Shared pointer to be cast as weak pointer
Definition at line 472 of file Game.cpp.
References _turret_manager, and TurretManager::addNewEntity().
Referenced by addNewTurret().
{
    std::weak_ptr<Turret> turret_wp = std::dynamic_pointer_cast<Turret>(turret_sp);
    _turret_manager.addNewEntity(turret_wp);
}
void Game::checkKeyboardInput (ActionData & action_data_container) [private]
Checks through all pressed control keys.
The keyboard class serves as an interface with Game.cpp and any other keyboard library. Should a different keyboard library be desired, adjustments should be made to the keyboard enum as well. The action data is changed based on user input. This covers both player 1 and player 2 controls.
Parameters
action_data_container :: Information passed by reference about what actions the player has taken.
Definition at line 72 of file Game.cpp.
References A, D, Down, Keyboard::isKeyPressed(), LAlt, LControl, Left, ActionData::mineLaidP1(), ActionData::mineLaidP2(), ActionData::missileFiredP1(), ActionData::missileFiredP2(), ActionData::moveBackwardP1(), ActionData::moveBackwardP2(), ActionData::moveForwardP1(), ActionData::moveForwardP2(), RAlt, RControl, Right, ActionData::rotateLeftP1(), ActionData::rotateLeftP2(), ActionData::rotateRightP1(), ActionData::rotateRightP2(), S, Up, and W.
Referenced by runWorld().
{
    Keyboard keyboard;
    // input for tank 1
    if (keyboard.isKeyPressed(Right))
    {
        action_data_container.rotateLeftP1(); // tank 1 rotate left
    }
    if (keyboard.isKeyPressed(Left))
    {
        action_data_container.rotateRightP1(); // tank 1 rotate right
    }
    if (keyboard.isKeyPressed(Up))
    {
        action_data_container.moveForwardP1(); // tank 1 move forward
    }
    if (keyboard.isKeyPressed(Down))
    {
        action_data_container.moveBackwardP1(); // tank 1 move backward
    }
    if (keyboard.isKeyPressed(RAlt))
    {
        action_data_container.mineLaidP1(); // tank 1 plant mine
    }
    if (keyboard.isKeyPressed(RControl))
    {
        action_data_container.missileFiredP1(); // tank 1 fire missile
    }
    // input for tank 2
    if (keyboard.isKeyPressed(D))
    {
        action_data_container.rotateLeftP2(); // tank 2 rotate left
    }
    if (keyboard.isKeyPressed(A))
    {
        action_data_container.rotateRightP2(); // tank 2 rotate right
    }
    if (keyboard.isKeyPressed(W))
    {
        action_data_container.moveForwardP2(); // tank 2 move forward
    }
    if (keyboard.isKeyPressed(S))
    {
        action_data_container.moveBackwardP2(); // tank 2 move backward
    }
    if (keyboard.isKeyPressed(LAlt))
    {
        action_data_container.mineLaidP2(); // tank 2 plant mine
    }
    if (keyboard.isKeyPressed(LControl))
    {
        action_data_container.missileFiredP2(); // tank 2 fire missile
    }
    return;
}
void Game::createBarrier (int x, int y) [private]
Adds a new barrier object.
Tank objects are created as Deletables. Each barrier is added to the DestructionManager vector. They exists here as shared pointers.
Parameters
x :: Barrier x pos
y :: Barrier y pos
Definition at line 413 of file Game.cpp.
References _destruction_manager, addCollidable(), addDeletable(), DestructionManager::addNewEntity(), and barrier.
Referenced by readMapData().
{
    std::shared_ptr<Deletable> new_barrier_del_sp(new Barrier(x, y,
      barrier));
    _destruction_manager.addNewEntity(new_barrier_del_sp);
    addDeletable(new_barrier_del_sp);
    addCollidable(new_barrier_del_sp);
}
void Game::getMapData (std::vector< std::vector< char >> & map_vector, std::ifstream & map_grid_file) [private]
Reads map data from text file.
The data is read from a textfile and saved to the vector. The file is read line by line and saved to a primary vector. This primary vector is then saved to a secondary vector which holds each line or horizontal set of map block. Each symbol corresponds to a single game entity.
Parameters
map_vector :: Vector that contains the map, which is written to here.
map_grid_file :: Reference to the map file object
Definition at line 154 of file Game.cpp.
Referenced by setupInitialMap().
{
    std::vector<char> grid_line;
    if (map_grid_file.is_open())
    {
        std::string line;
        while (getline(map_grid_file,line))
        {
            std::istringstream ss(line);
            char symbol;
            while (ss >> symbol)
            {
                grid_line.push_back(symbol);
            }
            map_vector.push_back(grid_line);
            grid_line.clear();
        }
        map_grid_file.close();
    }
    else std::cout << "Unable to open map file";
}
void Game::manageRespawns (GameManagementData & game_data_container) [private]
Manages when a respawn needs to take place.
Turrets are not respawned in this version. Doing so would reuqired changing GameManagementData. Tanks are respawned at their starting positions. No provision is made in this version for counteracting spawn raids.
Parameters
game_data_container :: Data the holds information about what tanks need to be respawned
Definition at line 328 of file Game.cpp.
References _player1_startX, _player1_startY, _player2_startX, _player2_startY, addNewTank(), GameManagementData::disableP1Respawn(), GameManagementData::disableP2Respawn(), GameManagementData::isP1Respawn(), GameManagementData::isP2Respawn(), p1_tank, and p2_tank.
Referenced by addNewWorldEntity().
{
    if (game_data_container.isP1Respawn())
    {
        addNewTank(p1_tank, _player1_startX,
      _player1_startY, 0);
        game_data_container.disableP1Respawn();
    }
    if (game_data_container.isP2Respawn())
    {
        addNewTank(p2_tank, _player2_startX,
      _player2_startY, 180);
        game_data_container.disableP2Respawn();
    }
}
void Game::readMapData (const std::vector< std::vector< char >> & map_vector) [private]
Reads the map data from the vector.
The map data is read from the vector and a game entity's position is set accordingly. Any other entities that wish to be added should have a unique symbol that is included in the map. If many symbols are needed then a vector of symbols may be used.
Parameters
map_vector :: Map vector is read only.
Definition at line 184 of file Game.cpp.
References _game_sprite_dimensions, _player1_startX, _player1_startY, _player2_startX, _player2_startY, _turret_startX, _turret_startY, addNewTank(), addNewTurret(), SpriteDimensions::barrier_sprite_x, SpriteDimensions::barrier_sprite_y, createBarrier(), p1_tank, p2_tank, SpriteDimensions::turret_sprite_x, and SpriteDimensions::turret_sprite_y.
Referenced by setupInitialMap().
{
    for (int i = 0; i < map_vector.size(); i++)
    {
        auto temp_vector = map_vector[i];
        for (int j = 0; j < temp_vector.size(); j++)
        {
            switch(temp_vector[j])
            {
            case '#':
                createBarrier(j*_game_sprite_dimensions.
      barrier_sprite_x, i*_game_sprite_dimensions.
      barrier_sprite_y);
                break;
            case '1':
                _player1_startX = j*_game_sprite_dimensions.
      barrier_sprite_x;
                _player1_startY = i*_game_sprite_dimensions.
      barrier_sprite_y;
                addNewTank(p1_tank, _player1_startX,
      _player1_startY, 0);
                break;
            case '2':
                _player2_startX = j*_game_sprite_dimensions.
      barrier_sprite_x;
                _player2_startY = i*_game_sprite_dimensions.
      barrier_sprite_y;
                addNewTank(p2_tank, _player2_startX,
      _player2_startY, 180);
                break;
            case 'T':
                _turret_startX = j*_game_sprite_dimensions.
      turret_sprite_x;
                _turret_startY = i*_game_sprite_dimensions.
      turret_sprite_y;
                addNewTurret(_turret_startX,
      _turret_startY, 0);
                break;
            }
        }
    }
}
void Game::runAllManagers (GameManagementData & game_data_container, std::shared_ptr< Display > display) [private]
All managers manage.
Any new manager added should be added here. Note that the only manager that has access to the display is the draw manager.
Parameters
game_data_container :: Tempory game data required by the managers.
display :: Display object required by the draw manager.
Definition at line 225 of file Game.cpp.
References _collision_manager, _destruction_manager, _draw_manager, _move_manager, _state_manager, _tracking_manager, _turret_manager, TurretManager::manage(), CollisionManager::manage(), DestructionManager::manage(), GameStateManager::manage(), DrawManager::manage(), MoveManager::manage(), and TrackingManager::manage().
Referenced by runWorld().
{
    _turret_manager.manage();
    _collision_manager.manage();
    _move_manager.manage(game_data_container);
    _tracking_manager.manage(game_data_container);
    _destruction_manager.manage(game_data_container);
    _state_manager.manage(game_data_container);
    _draw_manager.manage(game_data_container, display);
}
void Game::runWorld (std::shared_ptr< Display > display)
Main program loop.
The game begins running within this function. Once the initial map is set up the main game loop begins. Firstly, thsi function checks if the game window is still open. If it is and the game state has not been set as finished, then all main game functions are called. Once the game finishes, the end game screen is displayed in an infinite loop. This runs until the game window is closed.
Parameters
display :: The display object for drawing and displaying all game entities.
Definition at line 40 of file Game.cpp.
References _game_management_data, addNewWorldEntity(), checkKeyboardInput(), GameManagementData::isGameFinished(), GameManagementData::resetActionsInfo(), runAllManagers(), and setupInitialMap().
Referenced by main().
{
    setupInitialMap();
    while(display->isOpen()) // main game loop
    {
        if (!_game_management_data.isGameFinished())
        {
            _game_management_data.resetActionsInfo();
            display->pollEvents();
            checkKeyboardInput(_game_management_data);
            runAllManagers(_game_management_data, display);
            addNewWorldEntity(_game_management_data);
        }
        else
        {
            display->pollEvents();
            display->drawEndScreen();
            display->display();
        }
    }
    return;
}
void Game::setupInitialMap () [private]
Sets up the game wolrd map.
Maps are read from a textfile. The textfile name can be changed by changing the map_grid_filename string in the header. The map is stored as a vector of a vector of chars. This vector is used later on from which the map is drawn. Layout of the game world can be adjusted by changing the map grid file.
Definition at line 137 of file Game.cpp.
References getMapData(), map_grid_filename, and readMapData().
Referenced by runWorld().
{
    std::ifstream map_grid_file(map_grid_filename);
    std::vector<std::vector<char>> map_vector;
    getMapData(map_vector, map_grid_file);
    readMapData(map_vector);
}
Member Data Documentation
CollisionManager Game::_collision_manager [private]
Private object of the CollisionManager.
Definition at line 75 of file Game.h.
Referenced by addCollidable(), Game(), and runAllManagers().
DestructionManager Game::_destruction_manager [private]
Private object of the DestructionManager.
Definition at line 81 of file Game.h.
Referenced by addNewMine(), addNewMissile(), addNewTank(), addNewTurret(), createBarrier(), Game(), and runAllManagers().
DrawManager Game::_draw_manager [private]
Private object of the DrawManager.
Definition at line 79 of file Game.h.
Referenced by addDeletable(), Game(), and runAllManagers().
GameManagementData Game::_game_management_data [private]
Game runtime data.
Definition at line 88 of file Game.h.
Referenced by runWorld().
SpriteDimensions Game::_game_sprite_dimensions [private]
Dimensions of all game sprites.
Definition at line 90 of file Game.h.
Referenced by addNewWorldEntity(), and readMapData().
MoveManager Game::_move_manager [private]
Private object of the MoveManager.
Definition at line 73 of file Game.h.
Referenced by addMovable(), Game(), and runAllManagers().
float Game::_player1_startX [private]
Player 1 starting x position.
Definition at line 60 of file Game.h.
Referenced by manageRespawns(), and readMapData().
float Game::_player1_startY [private]
Player 1 starting y position.
Definition at line 62 of file Game.h.
Referenced by manageRespawns(), and readMapData().
float Game::_player2_startX [private]
Player 2 starting x position.
Definition at line 64 of file Game.h.
Referenced by manageRespawns(), and readMapData().
float Game::_player2_startY [private]
Player 2 starting y position.
Definition at line 66 of file Game.h.
Referenced by manageRespawns(), and readMapData().
GameStateManager Game::_state_manager [private]
Private object of the GameStateManager.
Definition at line 83 of file Game.h.
Referenced by Game(), and runAllManagers().
TrackingManager Game::_tracking_manager [private]
Private object of the TrackingManager.
Definition at line 77 of file Game.h.
Referenced by addNewWorldEntity(), addTrackable(), Game(), and runAllManagers().
TurretManager Game::_turret_manager [private]
Private object of the TurretManager.
Definition at line 85 of file Game.h.
Referenced by addTurretable(), Game(), and runAllManagers().
float Game::_turret_startX [private]
Turret starting x position.
Definition at line 68 of file Game.h.
Referenced by readMapData().
float Game::_turret_startY [private]
Turret starting y position.
Definition at line 70 of file Game.h.
Referenced by readMapData().
std::vector<std::weak_ptr<Deletable> > Game::_world_entities [private]
Container for all entities on the game world.
Definition at line 93 of file Game.h.
Referenced by addDeletable().
std::string Game::map_grid_filename = `map_grid.txt` [private]
File name for the map grid text file.
Definition at line 96 of file Game.h.
Referenced by setupInitialMap().
The documentation for this class was generated from the following files:
Game.h
Game.cpp