ClassTests.cpp File Reference
Unit tests for all classes. Included in single file for regression testing purposes.
#include <gtest/gtest.h>
*
#include `Structures.h`
*
#include `Orientation.h`
*
#include `GameManagementData.h`
*
#include `GameStateData.h`
*
#include `Manager.h`
*
#include `GameStateManager.h`
*
#include `CollisionManager.h`
*
#include `TrackingManager.h`
*
#include `MoveManager.h`
*
#include `DestructionManager.h`
*
#include `TurretManager.h`
*
#include `Tank.h`
*
#include `Missile.h`
*
#include `Barrier.h`
*
#include `Mine.h`
*
#include `GeometryEngine.h`
*
#include `Turret.h`
*
Macros
#define MISSILE_SPEED 8
#define TANK_SPEED 3
#define MISSILE_ROT_SPEED 45
#define TANK_ROT_SPEED 5
#define TURRET_ROTATION_SPEED -2
#define PI 3.141592653589793238462643383279502884L
Functions
TEST (Orientation, constructorCorrectlyAssignsInitialParameters)
*==============Tests for Orientation Class=======*/
TEST (Orientation, equalityOpperatorCorresctlyReturnsValues)
TEST (Orientation, moveFunctionCorrectlyChangesCoodinates)
TEST (Orientation, rotateFunctionCorrectlyChangesCoordinates)
TEST (Orientation, getGlobalBoundsCorrectlyReturnsBoundingBox)
TEST (Orientation, throwsExceptionForInvalidStateOfCoordinateData)
TEST (Tank, ifInvalidCoOrdinatesThrowsException)
*================================================*/
TEST (Tank, returnsCorrectEntityType)
TEST (Tank, returnsCorrectCoordinatesFromGetPosition)
TEST (Tank, returnsCorrectCoordinatesFromGetDrawPosition)
TEST (Tank, returnsCorrectOrientationValue)
TEST (Tank, returnsCorrectDrawRotationValue)
TEST (Tank, movesForwardCorrectly)
TEST (Tank, movesBackwardCorrectly)
TEST (Tank, rotatesLeftAndRightCorrectly)
TEST (Tank, booleanVariablesAreCorrectlySetAndRetrieved)
TEST (Missile, ifInvalidCoOrdinatesThrowsException)
*===================================================*/
TEST (Missile, returnsCorrectEntityType)
TEST (Missile, returnsCorrectCoordinatesFromGetDrawPosition)
TEST (Missile, returnsCorrectDrawRotationValue)
TEST (Missile, movesForwardCorrectly)
TEST (Missile, movesBackwardsCorrectly)
TEST (Missile, rotatesLeftAndRightCorrectly)
TEST (Missile, booleanVariablesAreCorrectlySetAndRetrieved)
TEST (Barrier, ifInvalidCoOrdinatesThrowsException)
*================Tests for Barrier Class============*/
TEST (Barrier, returnsCorrectEntityType)
TEST (Barrier, returnCorrectRectangleVertices)
TEST (Barrier, returnsCorrectCoordinatesFromGetDrawPosition)
TEST (Barrier, returnsCorrectDrawRotationValue)
TEST (Mine, throwsExceptionIfInvalidCoordinatesGiven)
*===================================================*/
TEST (Mine, returnsCorrectEntityType)
TEST (Mine, booleanVariablesAreCorrectlySetAndRetrieved)
TEST (Turret, throwsExceptionIfInvalidCoordinatesGiven)
*===================================================*/
TEST (Turret, correctlyRotatesThroughCommand)
TEST (GeometryEngine, returnsTrueIfRectanglesCollided)
*===================================================*/
TEST (GeometryEngine, returnsFalseIfRectanglesAreNotCollided)
TEST (GeometryEngine, returnsTrueIfOverlapOnAllAxes)
TEST (GeometryEngine, returnsFalseIfNoOverlapOnAxisOne)
TEST (GeometryEngine, returnsFalseIfNoOverlapOnAxisTwo)
TEST (GeometryEngine, returnsFalseIfNoOverlapOnAxisThree)
TEST (GeometryEngine, returnsFalseIfNoOverlapOnAxisFour)
TEST (GeometryEngine, returnsFalseIfTankNotInLineOfFireOfTurret)
TEST (GeometryEngine, correctlyIdentifiesRelativePositionsOfBoundingBoxes_Above)
TEST (GeometryEngine, correctlyIdentifiesRelativePositionsOfBoundingBoxes_Below)
TEST (GeometryEngine, correctlyIdentifiesRelativePositionsOfBoundingBoxes_Left)
TEST (GeometryEngine, correctlyIdentifiesRelativePositionsOfBoundingBoxes_Right)
TEST (GeometryEngine, throwsExceptionIfInvalidRectEntityPassed)
TEST (GeometryEngine, returnsTrueIfTankInLineOfFire)
TEST (GeometryEngine, returnsTrueIfTankNotInLineOfFire)
TEST (GeometryEngine, returnsFalseIfTankBehindTurretAndNotInLineOfFire)
TEST (GeometryEngine, returnsFalseIfTankBehindTurretWithSameOriginAndNotInLineOfFire)
TEST (GeometryEngine, calculatesCorrectVectorLength)
TEST (TrackingManager, correctlyTracksTankEntityForP1)
*===================================================*/
TEST (TrackingManager, correctlyTracksTankEntityForP2)
TEST (TrackingManager, correctlyTracksTurretEntity)
TEST (TrackingManager, enablesTurretFireWhenTankAndTurretAreInRange)
TEST (MoveManager, correctlyMovesTankEntityForP1)
*===================================================*/
TEST (MoveManager, correctlyMovesTankEntityForP2)
TEST (MoveManager, correctlyMovesMissileEntityForP1)
TEST (MoveManager, correctlyMovesMissileEntityForP2)
TEST (MoveManager, doesNotMoveTankIfBlocked_P1)
TEST (MoveManager, doesNotMoveTankIfBlocked_P2)
TEST (MoveManager, missileReflectsCorrectlyIfBlockedHorizontally)
TEST (MoveManager, missileReflectsCorrectlyIfBlockedVertically)
TEST (DestructionManager, correctlyDeletesTankEntityFromGame)
*===================================================*/
TEST (DestructionManager, correctlyDeletesMissileEntityFromGame)
TEST (DestructionManager, correctlyDeletesMineEntityFromGame)
TEST (DestructionManager, correctlyDeletesTurretEntityFromGame)
TEST (DestructionManager, correctlyIncreasesPlayerScoresUponTheirDeath)
TEST (GameStateManager, doesNotAllowCreationOfMissileBeforeTimerExpiers)
*==============================================================*/
TEST (GameStateManager, doesNotAllowCreationOfMineBeforeTimerExpiers)
TEST (TurretManager, CorrectlyRotatesTurretEntity)
*==============================================================*/
TEST (CollisionManager, correctlyBlocksTanksAndBarriers)
*==============================================================*/
TEST (CollisionManager, correctlyBlocksTanksAndTanks)
TEST (CollisionManager, correctlyBlocksMissilesAndBarriers)
TEST (CollisionManager, indicatesCollisionHasTakenPlace)
TEST (CollisionManager, correctlyCollidesTanksAndMissiles)
TEST (CollisionManager, correctlyCollidesMissilesAndMissiles)
TEST (CollisionManager, correctlyCollidesTanksAndMines)
Detailed Description
Unit tests for all classes. Included in single file for regression testing purposes.
Author
Daniel Holmes & Jonathan Gerrand
Date
18 September 2014
Definition in file ClassTests.cpp.
Macro Definition Documentation
#define MISSILE_ROT_SPEED 45
Definition at line 34 of file ClassTests.cpp.
#define MISSILE_SPEED 8
Definition at line 32 of file ClassTests.cpp.
Referenced by TEST().
#define PI 3.141592653589793238462643383279502884L
Definition at line 37 of file ClassTests.cpp.
Referenced by Game::addNewWorldEntity(), Missile::moveBackward(), Tank::moveBackward(), Missile::moveForward(), Tank::moveForward(), and TEST().
#define TANK_ROT_SPEED 5
Definition at line 35 of file ClassTests.cpp.
Referenced by TEST().
#define TANK_SPEED 3
Definition at line 33 of file ClassTests.cpp.
Referenced by TEST().
#define TURRET_ROTATION_SPEED -2
Definition at line 36 of file ClassTests.cpp.
Referenced by TEST().
Function Documentation
TEST (Orientation , constructorCorrectlyAssignsInitialParameters)
*==============Tests for Orientation Class=======*/
Definition at line 43 of file ClassTests.cpp.
References Orientation::getHeight(), Orientation::getOriginX(), Orientation::getOriginY(), Orientation::getRotation(), and Orientation::getWidth().
{
    float originX = 10.0;
    float originY = 12.0;
    float rotation = 20.0;
    float height = 5;
    float width = 10;
    Orientation orientationTest(originX,originY,width,height,rotation, true);
    EXPECT_EQ(orientationTest.getOriginX(), originX);
    EXPECT_EQ(orientationTest.getOriginY(), originY);
    EXPECT_EQ(orientationTest.getRotation(), rotation);
    EXPECT_EQ(orientationTest.getHeight(), height);
    EXPECT_EQ(orientationTest.getWidth(), width);
}
TEST (Orientation , equalityOpperatorCorresctlyReturnsValues)
Definition at line 60 of file ClassTests.cpp.
{
    Orientation orientationTest1(10,10,10,10,10, true);
    Orientation orientationTest2(10,10,10,10,10, true);
    Orientation orientationTest3(0,10,10,10,10, true);
    EXPECT_TRUE(orientationTest1 == orientationTest2);
    EXPECT_FALSE(orientationTest1 == orientationTest3);
}
TEST (Orientation , moveFunctionCorrectlyChangesCoodinates)
Definition at line 70 of file ClassTests.cpp.
References Orientation::move().
{
    Orientation orientationTest1(10,10,10,10,10, true);
    Orientation orientationTest2(20,20,10,10,10, true);
    orientationTest1.move(10,10);
    EXPECT_TRUE(orientationTest1 == orientationTest2);
    orientationTest1.move(-10,-10);
    orientationTest2.move(-10,-10);
    EXPECT_TRUE(orientationTest1 == orientationTest2);
}
TEST (Orientation , rotateFunctionCorrectlyChangesCoordinates)
Definition at line 86 of file ClassTests.cpp.
References Orientation::rotate().
{
    Orientation orientationTest1(10,10,10,10,10,true);
    Orientation orientationTest2(10,10,10,10,20,true);
    orientationTest1.rotate(10);
    EXPECT_TRUE(orientationTest1 == orientationTest2);
    orientationTest2.rotate(360);
    EXPECT_TRUE(orientationTest1 == orientationTest2);
}
TEST (Orientation , getGlobalBoundsCorrectlyReturnsBoundingBox)
Definition at line 100 of file ClassTests.cpp.
References Orientation::getGlobalBounds(), and Orientation::move().
{
    Orientation orientationTest1(10,10,10,10,10,true);
    Orientation orientationTest2(10,10,10,10,10,true);
    auto boundBox1 = orientationTest1.getGlobalBounds();
    auto boundBox2 = orientationTest2.getGlobalBounds();
    EXPECT_EQ(boundBox1.upper_left.x, boundBox2.upper_left.x);
    EXPECT_EQ(boundBox1.upper_left.y, boundBox2.upper_left.y);
    orientationTest1.move(10,10);
    boundBox1 = orientationTest1.getGlobalBounds();
    EXPECT_NE(boundBox1.upper_left.x, boundBox2.upper_left.x);
    EXPECT_NE(boundBox1.upper_left.y, boundBox2.upper_left.y);
    orientationTest2.move(10,10);
    boundBox2 = orientationTest2.getGlobalBounds();
    EXPECT_EQ(boundBox1.lower_left.x, boundBox2.lower_left.x);
    EXPECT_EQ(boundBox1.lower_left.y, boundBox2.lower_left.y);
}
TEST (Orientation , throwsExceptionForInvalidStateOfCoordinateData)
Definition at line 126 of file ClassTests.cpp.
References Orientation::getOriginX().
{
    Orientation testOrientation(-101,-101,-360,10,10, true);
    EXPECT_THROW(testOrientation.getOriginX(),InvalidStateOfCoordinates);
    EXPECT_NO_THROW({Orientation TestOrientation(10,10,10,10,10, true);});
}
TEST (Tank , ifInvalidCoOrdinatesThrowsException)
*================================================*/
*================Tests for Tank Class============*/
Definition at line 141 of file ClassTests.cpp.
References p1_missile, and p1_tank.
{
    EXPECT_ANY_THROW({Tank TestTank1(-10,10,10,p1_tank);});
    EXPECT_ANY_THROW({Tank TestTank1(10,-10,10,p1_tank);});
    EXPECT_ANY_THROW({Tank TestTank1(10,10,-10,p1_tank);});
    EXPECT_NO_THROW({Tank TestTank1(10,10,10,p1_tank);});
    EXPECT_THROW({Tank TestTank1(10,10,10,p1_missile);},
      InvalidConstructorArgumentsTank);
}
TEST (Tank , returnsCorrectEntityType)
Definition at line 150 of file ClassTests.cpp.
References Tank::getType(), p1_tank, and p2_tank.
{
    Tank TestTank1(10,10,10,p1_tank);
    Tank TestTank2(10,10,10,p2_tank);
    EXPECT_EQ(TestTank1.getType(),p1_tank);
    EXPECT_EQ(TestTank2.getType(),p2_tank);
}
TEST (Tank , returnsCorrectCoordinatesFromGetPosition)
Definition at line 159 of file ClassTests.cpp.
References Tank::getPositionX(), Tank::getPositionY(), p1_tank, and p2_tank.
{
    Tank TestTank1(10,10,10,p1_tank);
    Tank TestTank2(20,20,10,p2_tank);
    EXPECT_EQ(TestTank1.getPositionX(),10);
    EXPECT_EQ(TestTank1.getPositionY(),10);
    EXPECT_EQ(TestTank2.getPositionX(),20);
    EXPECT_EQ(TestTank2.getPositionY(),20);
}
TEST (Tank , returnsCorrectCoordinatesFromGetDrawPosition)
Definition at line 171 of file ClassTests.cpp.
References Tank::getDrawPositionX(), Tank::getDrawPositionY(), p1_tank, and p2_tank.
{
    Tank TestTank1(10,10,10,p1_tank);
    Tank TestTank2(20,20,10,p2_tank);
    EXPECT_EQ(TestTank1.getDrawPositionX(),10);
    EXPECT_EQ(TestTank1.getDrawPositionY(),10);
    EXPECT_EQ(TestTank2.getDrawPositionX(),20);
    EXPECT_EQ(TestTank2.getDrawPositionY(),20);
}
TEST (Tank , returnsCorrectOrientationValue)
Definition at line 183 of file ClassTests.cpp.
References Tank::getOrientation(), and p1_tank.
{
    Tank TestTank1(10,10,10,p1_tank);
    EXPECT_EQ(TestTank1.getOrientation(),10);
}
TEST (Tank , returnsCorrectDrawRotationValue)
Definition at line 189 of file ClassTests.cpp.
References Tank::getDrawRotation(), and p1_tank.
{
    Tank TestTank1(10,10,10,p1_tank);
    EXPECT_EQ(TestTank1.getDrawRotation(),10);
}
TEST (Tank , movesForwardCorrectly)
Definition at line 195 of file ClassTests.cpp.
References Tank::getPositionX(), Tank::getPositionY(), Tank::moveForward(), p1_tank, PI, TANK_MOVE_SPEED, and TANK_SPEED.
{
    float rotation = 0;
    Tank TestTank1(10,10,rotation,p1_tank);
    TestTank1.moveForward();
    EXPECT_EQ(TestTank1.getPositionX(),10 + TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank1.getPositionY(),10 + TANK_MOVE_SPEED*sin((rotation*
      PI)/180.0));
    rotation = 90;
    Tank TestTank2(10,10,rotation,p1_tank);
    TestTank2.moveForward();
    EXPECT_EQ(TestTank2.getPositionX(),10 + TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank2.getPositionY(),10 + TANK_SPEED*sin((rotation*
      PI)/180.0));
    rotation = 180;
    Tank TestTank3(10,10,rotation,p1_tank);
    TestTank3.moveForward();
    EXPECT_EQ(TestTank3.getPositionX(),10 + TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank3.getPositionY(),10 + TANK_SPEED*sin((rotation*
      PI)/180.0));
    rotation = 270;
    Tank TestTank4(10,10,rotation,p1_tank);
    TestTank4.moveForward();
    EXPECT_EQ(TestTank4.getPositionX(),10 + TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank4.getPositionY(),10 + TANK_SPEED*sin((rotation*
      PI)/180.0));
}
TEST (Tank , movesBackwardCorrectly)
Definition at line 222 of file ClassTests.cpp.
References Tank::getPositionX(), Tank::getPositionY(), Tank::moveBackward(), p1_tank, PI, and TANK_SPEED.
{
    float rotation = 0;
    Tank TestTank1(10,10,rotation,p1_tank);
    TestTank1.moveBackward();
    EXPECT_EQ(TestTank1.getPositionX(),10 - TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank1.getPositionY(),10 - TANK_SPEED*sin((rotation*
      PI)/180.0));
    rotation = 90;
    Tank TestTank2(10,10,rotation,p1_tank);
    TestTank2.moveBackward();
    EXPECT_EQ(TestTank2.getPositionX(),10 - TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank2.getPositionY(),10 - TANK_SPEED*sin((rotation*
      PI)/180.0));
    rotation = 180;
    Tank TestTank3(10,10,rotation,p1_tank);
    TestTank3.moveBackward();
    EXPECT_EQ(TestTank3.getPositionX(),10 - TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank3.getPositionY(),10 - TANK_SPEED*sin((rotation*
      PI)/180.0));
    rotation = 270;
    Tank TestTank4(10,10,rotation,p1_tank);
    TestTank4.moveBackward();
    EXPECT_EQ(TestTank4.getPositionX(),10 - TANK_SPEED*cos((rotation*
      PI)/180.0));
    EXPECT_EQ(TestTank4.getPositionY(),10 - TANK_SPEED*sin((rotation*
      PI)/180.0));
}
TEST (Tank , rotatesLeftAndRightCorrectly)
Definition at line 249 of file ClassTests.cpp.
References Tank::getOrientation(), p1_tank, Tank::rotateLeft(), Tank::rotateRight(), and TANK_ROT_SPEED.
{
    Tank TestTank1(10,10,0,p1_tank);
    TestTank1.rotateLeft();
    EXPECT_EQ(TestTank1.getOrientation(), 0 + TANK_ROT_SPEED);
    TestTank1.rotateRight();
    TestTank1.rotateRight();
    EXPECT_EQ(TestTank1.getOrientation(), 360 - TANK_ROT_SPEED);
    Tank TestTank2(10,10,358,p1_tank);
    TestTank2.rotateLeft();
    TestTank2.rotateLeft();
    EXPECT_EQ(TestTank2.getOrientation(), 8);
}
TEST (Tank , booleanVariablesAreCorrectlySetAndRetrieved)
Definition at line 265 of file ClassTests.cpp.
References blocked, Tank::isBlocked(), Tank::isDeleted(), p1_tank, Tank::setBlocked(), Tank::setCollided(), Tank::setUnblocked(), and unblocked.
{
    Tank TestTank1(10,10,0,p1_tank);
    TestTank1.setBlocked(blocked);
    TestTank1.setCollided();
    EXPECT_EQ(TestTank1.isBlocked(),blocked);
    EXPECT_TRUE(TestTank1.isDeleted());
    TestTank1.setUnblocked();
    EXPECT_EQ(TestTank1.isBlocked(), unblocked);
}
TEST (Missile , ifInvalidCoOrdinatesThrowsException)
*===================================================*/
*================Tests for Missile Class============*/
Definition at line 284 of file ClassTests.cpp.
References p1_missile, and p1_tank.
{
    EXPECT_ANY_THROW({Missile TestTank1(-10,10,10,p1_missile);});
    EXPECT_ANY_THROW({Missile TestTank1(10,-10,10,p1_missile);});
    EXPECT_ANY_THROW({Missile TestTank1(10,10,-10,p1_missile);});
    EXPECT_NO_THROW({Missile TestTank1(10,10,10,p1_missile);});
    EXPECT_THROW({Missile TestTank1(10,10,10,p1_tank);},
      InvalidConstructorArgumentsMissile);
}
TEST (Missile , returnsCorrectEntityType)
Definition at line 294 of file ClassTests.cpp.
References Missile::getType(), p1_missile, p2_missile, and turret_missile.
{
    Missile TestMissile1(10,10,10,p1_missile);
    Missile TestMissile2(10,10,10,p2_missile);
    Missile TestMissile3(10,10,10,turret_missile);
    EXPECT_EQ(TestMissile1.getType(),p1_missile);
    EXPECT_EQ(TestMissile2.getType(),p2_missile);
    EXPECT_EQ(TestMissile3.getType(),turret_missile);
}
TEST (Missile , returnsCorrectCoordinatesFromGetDrawPosition)
Definition at line 305 of file ClassTests.cpp.
References Missile::getDrawPositionX(), Missile::getDrawPositionY(), p1_missile, and p2_missile.
{
    Missile TestMissile1(10,10,10,p1_missile);
    Missile TestMissile2(20,20,10,p2_missile);
    EXPECT_EQ(TestMissile1.getDrawPositionX(),10);
    EXPECT_EQ(TestMissile1.getDrawPositionY(),10);
    EXPECT_EQ(TestMissile2.getDrawPositionX(),20);
    EXPECT_EQ(TestMissile2.getDrawPositionY(),20);
}
TEST (Missile , returnsCorrectDrawRotationValue)
Definition at line 317 of file ClassTests.cpp.
References Missile::getDrawRotation(), and p1_missile.
{
    Missile TestMissile1(10,10,10,p1_missile);
    EXPECT_EQ(TestMissile1.getDrawRotation(),10);
}
TEST (Missile , movesForwardCorrectly)
Definition at line 323 of file ClassTests.cpp.
References Missile::getDrawPositionX(), Missile::getDrawPositionY(), MISSILE_SPEED, Missile::moveForward(), and p1_missile.
{
    float rotation = 0;
    Missile TestMissile1(10,10,rotation,p1_missile);
    TestMissile1.moveForward();
    EXPECT_EQ(TestMissile1.getDrawPositionX(),10 + MISSILE_SPEED);
    EXPECT_EQ(TestMissile1.getDrawPositionY(),10);
    rotation = 90;
    Missile TestMissile2(10,10,rotation,p1_missile);
    TestMissile2.moveForward();
    EXPECT_EQ(TestMissile2.getDrawPositionX(),10);
    EXPECT_EQ(TestMissile2.getDrawPositionY(),10 + MISSILE_SPEED);
    rotation = 180;
    Missile TestMissile3(10,10,rotation,p1_missile);
    TestMissile3.moveForward();
    EXPECT_EQ(TestMissile3.getDrawPositionX(),10 - MISSILE_SPEED);
    EXPECT_EQ(TestMissile3.getDrawPositionY(),10);
    rotation = 270;
    Missile TestMissile4(10,10,rotation,p1_missile);
    TestMissile4.moveForward();
    EXPECT_EQ(TestMissile4.getDrawPositionX(),10);
    EXPECT_EQ(TestMissile4.getDrawPositionY(),10 - MISSILE_SPEED);
}
TEST (Missile , movesBackwardsCorrectly)
Definition at line 350 of file ClassTests.cpp.
References Missile::getDrawPositionX(), Missile::getDrawPositionY(), MISSILE_SPEED, Missile::moveBackward(), and p1_missile.
{
    float rotation = 0;
    Missile TestMissile1(10,10,rotation,p1_missile);
    TestMissile1.moveBackward();
    EXPECT_EQ(TestMissile1.getDrawPositionX(),10 - MISSILE_SPEED);
    EXPECT_EQ(TestMissile1.getDrawPositionY(),10);
    rotation = 90;
    Missile TestMissile2(10,10,rotation,p1_missile);
    TestMissile2.moveBackward();
    EXPECT_EQ(TestMissile2.getDrawPositionX(),10);
    EXPECT_EQ(TestMissile2.getDrawPositionY(),10 - MISSILE_SPEED);
    rotation = 180;
    Missile TestMissile3(10,10,rotation,p1_missile);
    TestMissile3.moveBackward();
    EXPECT_EQ(TestMissile3.getDrawPositionX(),10 + MISSILE_SPEED);
    EXPECT_EQ(TestMissile3.getDrawPositionY(),10);
    rotation = 270;
    Missile TestMissile4(10,10,rotation,p1_missile);
    TestMissile4.moveBackward();
    EXPECT_EQ(TestMissile4.getDrawPositionX(),10);
    EXPECT_EQ(TestMissile4.getDrawPositionY(),10 + MISSILE_SPEED);
}
TEST (Missile , rotatesLeftAndRightCorrectly)
Definition at line 377 of file ClassTests.cpp.
References Missile::getDrawRotation(), p1_missile, and Missile::rotateLeft().
{
    Missile TestMissile1(10,10,0,p1_missile);
    TestMissile1.rotateLeft();
    EXPECT_EQ(TestMissile1.getDrawRotation(), 180);
    Missile TestMissile2(10,10,315,p1_missile);
    TestMissile2.rotateRight();
    EXPECT_EQ(TestMissile2.getDrawRotation(), 45);
    Missile TestMissile3(10,10,135,p1_missile);
    TestMissile3.rotateLeft();
    EXPECT_EQ(TestMissile3.getDrawRotation(), 45);
    Missile TestMissile4(10,10,170,p1_missile);
    TestMissile4.rotateLeft();
    EXPECT_EQ(TestMissile4.getDrawRotation(), 10);
}
TEST (Missile , booleanVariablesAreCorrectlySetAndRetrieved)
Definition at line 396 of file ClassTests.cpp.
References blocked, Missile::isBlocked(), Missile::isDeleted(), p1_missile, Missile::setBlocked(), Missile::setCollided(), Missile::setUnblocked(), and unblocked.
{
    Missile TestMissile1(10,10,0,p1_missile);
    TestMissile1.setBlocked(blocked);
    TestMissile1.setCollided();
    EXPECT_EQ(TestMissile1.isBlocked(), blocked);
    EXPECT_TRUE(TestMissile1.isDeleted());
    TestMissile1.setUnblocked();
    EXPECT_EQ(TestMissile1.isBlocked(), unblocked);
}
TEST (Barrier , ifInvalidCoOrdinatesThrowsException)
*================Tests for Barrier Class============*/
Definition at line 415 of file ClassTests.cpp.
References barrier, and p1_mine.
{
    EXPECT_THROW({Barrier TestBarrier(-10,10,barrier);},
      InvalidConstructorArgumentsBarrier);
    EXPECT_THROW({Barrier TestBarrier(10,-10,barrier);},
      InvalidConstructorArgumentsBarrier);
    EXPECT_NO_THROW({Barrier TestBarrier(10,10,barrier);});
    EXPECT_THROW({Barrier TestBarrier(10,10,p1_mine);},
      InvalidConstructorArgumentsBarrier);
}
TEST (Barrier , returnsCorrectEntityType)
Definition at line 423 of file ClassTests.cpp.
References barrier, and Barrier::getType().
{
    Barrier TestBarrier(10,10,barrier);
    EXPECT_EQ(TestBarrier.getType(),barrier);
}
TEST (Barrier , returnCorrectRectangleVertices)
Definition at line 430 of file ClassTests.cpp.
References barrier, SpriteDimensions::barrier_sprite_x, SpriteDimensions::barrier_sprite_y, Barrier::getBoundingBox(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    SpriteDimensions _dimensions;
    float origin_x = 100;
    float origin_y = 100;
    Barrier TestBarrier(origin_x,origin_y,barrier);
    rect_corners rect;
    rect.upper_left.x = origin_x - _dimensions.barrier_sprite_x/2;
    rect.upper_left.y = origin_y + _dimensions.barrier_sprite_y/2;
    rect.upper_right.x = origin_x + _dimensions.barrier_sprite_x/2;
    rect.upper_right.y = origin_y + _dimensions.barrier_sprite_y/2;
    rect.lower_left.x = origin_x - _dimensions.barrier_sprite_x/2;
    rect.lower_left.y = origin_y + _dimensions.barrier_sprite_y/2;
    rect.lower_right.x = origin_x + _dimensions.barrier_sprite_x/2;
    rect.lower_right.y = origin_y + _dimensions.barrier_sprite_y/2;
    EXPECT_EQ(TestBarrier.getBoundingBox().upper_left.x,rect.upper_left.
      x);
    EXPECT_EQ(TestBarrier.getBoundingBox().upper_left.y,rect.upper_left.
      y);
    EXPECT_EQ(TestBarrier.getBoundingBox().upper_right.x,rect.upper_right.
      x);
    EXPECT_EQ(TestBarrier.getBoundingBox().upper_right.y,rect.upper_right.
      y);
}
TEST (Barrier , returnsCorrectCoordinatesFromGetDrawPosition)
Definition at line 454 of file ClassTests.cpp.
References barrier, Barrier::getDrawPositionX(), and Barrier::getDrawPositionY().
{
    Barrier TestBarrier1(10,10,barrier);
    Barrier TestBarrier2(20,20,barrier);
    EXPECT_EQ(TestBarrier1.getDrawPositionX(),10);
    EXPECT_EQ(TestBarrier1.getDrawPositionY(),10);
    EXPECT_EQ(TestBarrier2.getDrawPositionX(),20);
    EXPECT_EQ(TestBarrier2.getDrawPositionY(),20);
}
TEST (Barrier , returnsCorrectDrawRotationValue)
Definition at line 466 of file ClassTests.cpp.
References barrier, and Barrier::getDrawRotation().
{
    Barrier TestBarrier(10,10,barrier);
    EXPECT_EQ(TestBarrier.getDrawRotation(),0);
}
TEST (Mine , throwsExceptionIfInvalidCoordinatesGiven)
*===================================================*/
*================Tests for Mine Class============*/
Definition at line 476 of file ClassTests.cpp.
References p1_mine, and p1_missile.
{
    double orign_x = 10;
    double origin_y = 10;
    EXPECT_THROW({Mine TestMine(-orign_x,origin_y,p1_mine);},
      InvalidConstructorArgumentsMine);
    EXPECT_THROW({Mine TestMine(orign_x,-origin_y,p1_mine);},
      InvalidConstructorArgumentsMine);
    EXPECT_NO_THROW({Mine TestMine(orign_x,origin_y, p1_mine);});
    EXPECT_THROW({Mine TestMine(orign_x,origin_y,p1_missile);},
      InvalidConstructorArgumentsMine);
}
TEST (Mine , returnsCorrectEntityType)
Definition at line 486 of file ClassTests.cpp.
References Mine::getType(), p1_mine, and p2_mine.
{
    Mine TestMine1(10,10,p1_mine);
    Mine TestMine2(10,10,p2_mine);
    EXPECT_EQ(TestMine1.getType(),p1_mine);
    EXPECT_EQ(TestMine2.getType(),p2_mine);
    EXPECT_NE(TestMine1.getType(),p2_mine);
}
TEST (Mine , booleanVariablesAreCorrectlySetAndRetrieved)
Definition at line 496 of file ClassTests.cpp.
References Mine::isDeleted(), p1_mine, and Mine::setCollided().
{
    Mine TestMine1(10,10,p1_mine);
    TestMine1.setCollided();
    EXPECT_TRUE(TestMine1.isDeleted());
}
TEST (Turret , throwsExceptionIfInvalidCoordinatesGiven)
*===================================================*/
*================Tests for Turret Class============*/
Definition at line 509 of file ClassTests.cpp.
{
    double orign_x = 10;
    double origin_y = 10;
    double rotation = 10;
    EXPECT_ANY_THROW({Turret TestTurret(-orign_x,origin_y,rotation);});
    EXPECT_ANY_THROW({Turret TestTurret(orign_x,-origin_y, rotation);});
    EXPECT_NO_THROW({Turret TestTurret(orign_x,origin_y, rotation);});
    EXPECT_ANY_THROW({Turret TestTurret(orign_x,origin_y,-rotation);});
}
TEST (Turret , correctlyRotatesThroughCommand)
Definition at line 520 of file ClassTests.cpp.
References Turret::getOrientation(), and Turret::rotateTurret().
{
    double orign_x = 10;
    double origin_y = 10;
    double rotation = 2;
    double TurrRotationRate = -2;
    Turret testTurret1(orign_x,origin_y,rotation);
    EXPECT_EQ(testTurret1.getOrientation(), 2);
    testTurret1.rotateTurret();
    EXPECT_EQ(testTurret1.getOrientation(), 0);
    testTurret1.rotateTurret();
    EXPECT_NE(testTurret1.getOrientation(), 0);
}
TEST (GeometryEngine , returnsTrueIfRectanglesCollided)
*===================================================*/
*================Tests for GeometryEngine Class============*/
Definition at line 548 of file ClassTests.cpp.
References GeometryEngine::isCollision(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 2.0;
    rect_B.upper_left.y = 9.0;
    rect_B.upper_right.x = 6.0;
    rect_B.upper_right.y = 9.0;
    rect_B.lower_left.x = 2.0;
    rect_B.lower_left.y = 2.0;
    rect_B.lower_right.x = 6.0;
    rect_B.lower_right.y = 2.0;
    GeometryEngine CollisionTest;
    EXPECT_TRUE(CollisionTest.isCollision(rect_A, rect_B));
}
TEST (GeometryEngine , returnsFalseIfRectanglesAreNotCollided)
Definition at line 576 of file ClassTests.cpp.
References GeometryEngine::isCollision(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 12.0;
    rect_B.upper_left.y = 19.0;
    rect_B.upper_right.x = 16.0;
    rect_B.upper_right.y = 19.0;
    rect_B.lower_left.x = 12.0;
    rect_B.lower_left.y = 12.0;
    rect_B.lower_right.x = 16.0;
    rect_B.lower_right.y = 12.0;
    GeometryEngine CollisionTest;
    EXPECT_FALSE(CollisionTest.isCollision(rect_A, rect_B));
}
TEST (GeometryEngine , returnsTrueIfOverlapOnAllAxes)
Definition at line 604 of file ClassTests.cpp.
References GeometryEngine::isRectangleOverlapForAxis(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 2.0;
    rect_B.upper_left.y = 9.0;
    rect_B.upper_right.x = 6.0;
    rect_B.upper_right.y = 8.0;
    rect_B.lower_left.x = 2.0;
    rect_B.lower_left.y = 2.0;
    rect_B.lower_right.x = 6.0;
    rect_B.lower_right.y = 2.0;
    coordinate axis;
    GeometryEngine CollisionTest;
    axis.x = rect_A.upper_right.x - rect_A.upper_left.x;
    axis.y = rect_A.upper_right.y - rect_A.upper_left.y;
    EXPECT_TRUE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
    axis.x = rect_A.upper_right.x - rect_A.lower_right.x;
    axis.y = rect_A.upper_right.y - rect_A.lower_right.y;
    EXPECT_TRUE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
    axis.x = rect_B.upper_left.x - rect_B.lower_left.x;
    axis.y = rect_B.upper_left.y - rect_B.lower_left.y;
    EXPECT_TRUE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
    axis.x = rect_B.upper_left.x - rect_B.upper_right.x;
    axis.y = rect_B.upper_left.y - rect_B.upper_right.y;
    EXPECT_TRUE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
}
TEST (GeometryEngine , returnsFalseIfNoOverlapOnAxisOne)
Definition at line 647 of file ClassTests.cpp.
References GeometryEngine::isRectangleOverlapForAxis(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 12.0;
    rect_B.upper_left.y = 19.0;
    rect_B.upper_right.x = 16.0;
    rect_B.upper_right.y = 19.0;
    rect_B.lower_left.x = 12.0;
    rect_B.lower_left.y = 12.0;
    rect_B.lower_right.x = 16.0;
    rect_B.lower_right.y = 12.0;
    coordinate axis;
    GeometryEngine CollisionTest;
    //Axis 1
    axis.x = rect_A.upper_right.x - rect_A.upper_left.x;
    axis.y = rect_A.upper_right.y - rect_A.upper_left.y;
    EXPECT_FALSE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
}
TEST (GeometryEngine , returnsFalseIfNoOverlapOnAxisTwo)
Definition at line 679 of file ClassTests.cpp.
References GeometryEngine::isRectangleOverlapForAxis(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 12.0;
    rect_B.upper_left.y = 19.0;
    rect_B.upper_right.x = 16.0;
    rect_B.upper_right.y = 19.0;
    rect_B.lower_left.x = 12.0;
    rect_B.lower_left.y = 12.0;
    rect_B.lower_right.x = 16.0;
    rect_B.lower_right.y = 12.0;
    coordinate axis;
    GeometryEngine CollisionTest;
    //Axis 2
    axis.x = rect_A.upper_right.x - rect_A.lower_right.x;
    axis.y = rect_A.upper_right.y - rect_A.lower_right.y;
    EXPECT_FALSE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
}
TEST (GeometryEngine , returnsFalseIfNoOverlapOnAxisThree)
Definition at line 711 of file ClassTests.cpp.
References GeometryEngine::isRectangleOverlapForAxis(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 12.0;
    rect_B.upper_left.y = 19.0;
    rect_B.upper_right.x = 16.0;
    rect_B.upper_right.y = 19.0;
    rect_B.lower_left.x = 12.0;
    rect_B.lower_left.y = 12.0;
    rect_B.lower_right.x = 16.0;
    rect_B.lower_right.y = 12.0;
    coordinate axis;
    GeometryEngine CollisionTest;
    //Axis 3
    axis.x = rect_B.upper_left.x - rect_B.lower_left.x;
    axis.y = rect_B.upper_left.y - rect_B.lower_left.y;
    EXPECT_FALSE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
}
TEST (GeometryEngine , returnsFalseIfNoOverlapOnAxisFour)
Definition at line 743 of file ClassTests.cpp.
References GeometryEngine::isRectangleOverlapForAxis(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 12.0;
    rect_B.upper_left.y = 19.0;
    rect_B.upper_right.x = 16.0;
    rect_B.upper_right.y = 19.0;
    rect_B.lower_left.x = 12.0;
    rect_B.lower_left.y = 12.0;
    rect_B.lower_right.x = 16.0;
    rect_B.lower_right.y = 12.0;
    coordinate axis;
    GeometryEngine CollisionTest;
    //Axis 4
    axis.x = rect_B.upper_left.x - rect_B.upper_right.x;
    axis.y = rect_B.upper_left.y - rect_B.upper_right.y;
    EXPECT_FALSE(CollisionTest.isRectangleOverlapForAxis(axis, rect_A, rect_B));
}
TEST (GeometryEngine , returnsFalseIfTankNotInLineOfFireOfTurret)
Definition at line 775 of file ClassTests.cpp.
References GeometryEngine::isInLineOfFire(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    float rotation = 45.0;
    rect_corners shooter;
    rect_corners target;
    shooter.upper_left.x = 1.0;
    shooter.upper_left.y = 8.0;
    shooter.upper_right.x = 5.0;
    shooter.upper_right.y = 8.0;
    shooter.lower_left.x = 1.0;
    shooter.lower_left.y = 1.0;
    shooter.lower_right.x = 5.0;
    shooter.lower_right.y = 1.0;
    target.upper_left.x = 11.0;
    target.upper_left.y = 8.0;
    target.upper_right.x = 15.0;
    target.upper_right.y = 8.0;
    target.lower_left.x = 11.0;
    target.lower_left.y = 1.0;
    target.lower_right.x = 15.0;
    target.lower_right.y = 1.0;
    GeometryEngine lineOfFireTest;
    EXPECT_FALSE(lineOfFireTest.isInLineOfFire(rotation, shooter, target, 4, 4));
}
TEST (GeometryEngine , correctlyIdentifiesRelativePositionsOfBoundingBoxes_Above)
Definition at line 804 of file ClassTests.cpp.
References blocked_vertically, GeometryEngine::getRelativePosition(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners entity;
    rect_corners relative_entity;
    //Set box
    relative_entity.upper_left.x = 100.0;
    relative_entity.upper_left.y = 100.0;
    relative_entity.upper_right.x = 200.0;
    relative_entity.upper_right.y = 100.0;
    relative_entity.lower_left.x = 100.0;
    relative_entity.lower_left.y = 50.0;
    relative_entity.lower_right.x = 200.0;
    relative_entity.lower_right.y = 50.0;
    //Entity Above box
    entity.upper_left.x = 110.0;
    entity.upper_left.y = 110.0;
    entity.upper_right.x = 120.0;
    entity.upper_right.y = 110.0;
    entity.lower_left.x = 110.0;
    entity.lower_left.y = 90.0;
    entity.lower_right.x = 120.0;
    entity.lower_right.y = 90.0;
    GeometryEngine relativePositionTest;
    EXPECT_EQ(relativePositionTest.getRelativePosition(entity,relative_entity),
      blocked_vertically);
    EXPECT_EQ(relativePositionTest.getRelativePosition(entity,relative_entity),
      blocked_vertically);
}
TEST (GeometryEngine , correctlyIdentifiesRelativePositionsOfBoundingBoxes_Below)
Definition at line 835 of file ClassTests.cpp.
References blocked_vertically, GeometryEngine::getRelativePosition(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners entity;
    rect_corners relative_entity;
    //Set box
    relative_entity.upper_left.x = 100.0;
    relative_entity.upper_left.y = 100.0;
    relative_entity.upper_right.x = 200.0;
    relative_entity.upper_right.y = 100.0;
    relative_entity.lower_left.x = 100.0;
    relative_entity.lower_left.y = 50.0;
    relative_entity.lower_right.x = 200.0;
    relative_entity.lower_right.y = 50.0;
    //Entity Below box
    entity.upper_left.x = 110.0;
    entity.upper_left.y = 60.0;
    entity.upper_right.x = 120.0;
    entity.upper_right.y = 60.0;
    entity.lower_left.x = 110.0;
    entity.lower_left.y = 30.0;
    entity.lower_right.x = 120.0;
    entity.lower_right.y = 30.0;
    GeometryEngine relativePositionTest;
    EXPECT_EQ(relativePositionTest.getRelativePosition(entity,relative_entity),
      blocked_vertically);
}
TEST (GeometryEngine , correctlyIdentifiesRelativePositionsOfBoundingBoxes_Left)
Definition at line 865 of file ClassTests.cpp.
References blocked_horizontally, GeometryEngine::getRelativePosition(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners entity;
    rect_corners relative_entity;
    //Set box
    relative_entity.upper_left.x = 100.0;
    relative_entity.upper_left.y = 100.0;
    relative_entity.upper_right.x = 200.0;
    relative_entity.upper_right.y = 100.0;
    relative_entity.lower_left.x = 100.0;
    relative_entity.lower_left.y = 50.0;
    relative_entity.lower_right.x = 200.0;
    relative_entity.lower_right.y = 50.0;
    //Entity left of box
    entity.upper_left.x = 80.0;
    entity.upper_left.y = 90.0;
    entity.upper_right.x = 110.0;
    entity.upper_right.y = 90.0;
    entity.lower_left.x = 80.0;
    entity.lower_left.y = 60.0;
    entity.lower_right.x = 110.0;
    entity.lower_right.y = 60.0;
    GeometryEngine relativePositionTest;
    EXPECT_EQ(relativePositionTest.getRelativePosition(entity,relative_entity),
      blocked_horizontally);
}
TEST (GeometryEngine , correctlyIdentifiesRelativePositionsOfBoundingBoxes_Right)
Definition at line 895 of file ClassTests.cpp.
References blocked_horizontally, GeometryEngine::getRelativePosition(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners entity;
    rect_corners relative_entity;
    //Set box
    relative_entity.upper_left.x = 100.0;
    relative_entity.upper_left.y = 100.0;
    relative_entity.upper_right.x = 200.0;
    relative_entity.upper_right.y = 100.0;
    relative_entity.lower_left.x = 100.0;
    relative_entity.lower_left.y = 50.0;
    relative_entity.lower_right.x = 200.0;
    relative_entity.lower_right.y = 50.0;
    //Entity left of box
    entity.upper_left.x = 190.0;
    entity.upper_left.y = 90.0;
    entity.upper_right.x = 230.0;
    entity.upper_right.y = 90.0;
    entity.lower_left.x = 190.0;
    entity.lower_left.y = 60.0;
    entity.lower_right.x = 230.0;
    entity.lower_right.y = 60.0;
    GeometryEngine relativePositionTest;
    EXPECT_EQ(relativePositionTest.getRelativePosition(entity,relative_entity),
      blocked_horizontally);
}
TEST (GeometryEngine , throwsExceptionIfInvalidRectEntityPassed)
Definition at line 925 of file ClassTests.cpp.
References GeometryEngine::isCollision(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners entity;
    rect_corners relative_entity;
    relative_entity.upper_left.x = -200.0;
    relative_entity.upper_left.y = 100.0;
    relative_entity.upper_right.x = 200.0;
    relative_entity.upper_right.y = 100.0;
    relative_entity.lower_left.x = 100.0;
    relative_entity.lower_left.y = 50.0;
    relative_entity.lower_right.x = 200.0;
    relative_entity.lower_right.y = 50.0;
    entity.upper_left.x = 110.0;
    entity.upper_left.y = 60.0;
    entity.upper_right.x = 120.0;
    entity.upper_right.y = 60.0;
    entity.lower_left.x = 110.0;
    entity.lower_left.y = 30.0;
    entity.lower_right.x = 120.0;
    entity.lower_right.y = 30.0;
    GeometryEngine geometryTest;
    EXPECT_THROW({geometryTest.isCollision(entity,relative_entity);},
      InvalidRectEntityProvided);
    relative_entity.upper_left.x = 100.0;
    EXPECT_NO_THROW({geometryTest.isCollision(entity,relative_entity);});
}
TEST (GeometryEngine , returnsTrueIfTankInLineOfFire)
Definition at line 957 of file ClassTests.cpp.
References GeometryEngine::isInLineOfFire(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    float rotation = 0.0;
    float shooter_y = 10.0;
    float target_y = 12.0;
    rect_corners shooter;
    rect_corners target;
    target.upper_left.x = 16.0;
    target.upper_left.y = 14.0;
    target.upper_right.x = 18.0;
    target.upper_right.y = 12.0;
    target.lower_left.x = 14.0;
    target.lower_left.y = 12.0;
    target.lower_right.x = 16.0;
    target.lower_right.y = 10.0;
    shooter.upper_left.x = 9.0;
    shooter.upper_left.y = 11.0;
    shooter.upper_right.x = 11.0;
    shooter.upper_right.y = 11.0;
    shooter.lower_left.x = 9.0;
    shooter.lower_left.y = 9.0;
    shooter.lower_right.x = 11.0;
    shooter.lower_right.y = 9.0;
    GeometryEngine lineOfFireTest;
    EXPECT_TRUE(lineOfFireTest.isInLineOfFire(rotation, shooter, target, shooter_y, target_y)
      );
}
TEST (GeometryEngine , returnsTrueIfTankNotInLineOfFire)
Definition at line 988 of file ClassTests.cpp.
References GeometryEngine::isInLineOfFire(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    float rotation = 45.0;
    float shooter_y = 10.0;
    float target_y = 12.0;
    rect_corners shooter;
    rect_corners target;
    target.upper_left.x = 16.0;
    target.upper_left.y = 14.0;
    target.upper_right.x = 18.0;
    target.upper_right.y = 12.0;
    target.lower_left.x = 14.0;
    target.lower_left.y = 12.0;
    target.lower_right.x = 16.0;
    target.lower_right.y = 10.0;
    shooter.upper_left.x = 10.0;
    shooter.upper_left.y = 12.0;
    shooter.upper_right.x = 12.0;
    shooter.upper_right.y = 10.0;
    shooter.lower_left.x = 8.0;
    shooter.lower_left.y = 10.0;
    shooter.lower_right.x = 10.0;
    shooter.lower_right.y = 8.0;
    GeometryEngine lineOfFireTest;
    EXPECT_FALSE(lineOfFireTest.isInLineOfFire(rotation, shooter, target, shooter_y, target_y
      ));
}
TEST (GeometryEngine , returnsFalseIfTankBehindTurretAndNotInLineOfFire)
Definition at line 1019 of file ClassTests.cpp.
References GeometryEngine::isInLineOfFire(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    float rotation = 135.0;
    float shooter_y = 10.0;
    float target_y = 9.5;
    rect_corners shooter;
    rect_corners target;
    target.upper_left.x = 12.0;
    target.upper_left.y = 10.0;
    target.upper_right.x = 13.0;
    target.upper_right.y = 10.0;
    target.lower_left.x = 12.0;
    target.lower_left.y = 9.0;
    target.lower_right.x = 13.0;
    target.lower_right.y = 9.0;
    shooter.upper_left.x = 8.0;
    shooter.upper_left.y = 12.0;
    shooter.upper_right.x = 12.0;
    shooter.upper_right.y = 12.0;
    shooter.lower_left.x = 8.0;
    shooter.lower_left.y = 8.0;
    shooter.lower_right.x = 12.0;
    shooter.lower_right.y = 8.0;
    GeometryEngine lineOfFireTest;
    EXPECT_FALSE(lineOfFireTest.isInLineOfFire(rotation, shooter, target, shooter_y, target_y
      ));
}
TEST (GeometryEngine , returnsFalseIfTankBehindTurretWithSameOriginAndNotInLineOfFire)
Definition at line 1050 of file ClassTests.cpp.
References GeometryEngine::isInLineOfFire(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    float rotation = 180.0;
    float shooter_y = 10.0;
    float target_y = 10.0;
    rect_corners shooter;
    rect_corners target;
    shooter.upper_left.x = 12.0;
    shooter.upper_left.y = 11.0;
    shooter.upper_right.x = 14.0;
    shooter.upper_right.y = 11.0;
    shooter.lower_left.x = 12.0;
    shooter.lower_left.y = 9.0;
    shooter.lower_right.x = 14.0;
    shooter.lower_right.y = 9.0;
    shooter.upper_left.x = 9.0;
    shooter.upper_left.y = 11.0;
    shooter.upper_right.x = 11.0;
    shooter.upper_right.y = 11.0;
    shooter.lower_left.x = 9.0;
    shooter.lower_left.y = 9.0;
    shooter.lower_right.x = 11.0;
    shooter.lower_right.y = 9.0;
    GeometryEngine lineOfFireTest;
    EXPECT_FALSE(lineOfFireTest.isInLineOfFire(rotation, shooter, target, shooter_y, target_y
      ));
}
TEST (GeometryEngine , calculatesCorrectVectorLength)
Definition at line 1081 of file ClassTests.cpp.
References GeometryEngine::calculateVectorLength().
{
    float x_coord_1 = 1.0;
    float y_coord_1 = 4.0;
    float x_coord_2 = 1.0;
    float y_coord_2 = 2.0;
    GeometryEngine test;
    float test_ans = test.calculateVectorLength(x_coord_1, y_coord_1, x_coord_2,
      y_coord_2);
    EXPECT_EQ(test_ans, 2.0);
}
TEST (TrackingManager , correctlyTracksTankEntityForP1)
*===================================================*/
*================Tests for TrackingManager Class============*/
Definition at line 1100 of file ClassTests.cpp.
References TrackingManager::addNewEntity(), TrackingManager::getP1PositionX(), TrackingManager::getP1PositionY(), TrackingManager::getP1Rotation(), TrackingManager::manage(), p1_tank, and TANK_SPEED.
{
    TrackingManager trackingManager;
    GameManagementData data;
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p1_tank));
    std::weak_ptr<Trackable> tank_track_wp = std::dynamic_pointer_cast<Trackable>(tank_del_sp);
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    trackingManager.addNewEntity(tank_track_wp);
    trackingManager.manage(data);
    EXPECT_EQ(trackingManager.getP1PositionX(), 30);
    EXPECT_EQ(trackingManager.getP1PositionY(), 30);
    EXPECT_EQ(trackingManager.getP1Rotation(), 0);
    tank_mov_sp->moveForward();
    trackingManager.manage(data);
    EXPECT_EQ(trackingManager.getP1PositionX(), 30 + TANK_SPEED);
    EXPECT_EQ(trackingManager.getP1PositionY(), 30);
    EXPECT_EQ(trackingManager.getP1Rotation(), 0);
    tank_mov_sp->moveForward();
    trackingManager.manage(data);
    EXPECT_NE(trackingManager.getP1PositionX(), 30 + TANK_SPEED);
}
TEST (TrackingManager , correctlyTracksTankEntityForP2)
Definition at line 1130 of file ClassTests.cpp.
References TrackingManager::addNewEntity(), TrackingManager::getP2PositionX(), TrackingManager::getP2PositionY(), TrackingManager::getP2Rotation(), TrackingManager::manage(), p2_tank, and TANK_SPEED.
{
    TrackingManager trackingManager;
    GameManagementData data;
    std::shared_ptr<Deletable> tank_del_sp(new Tank(40,40,0,p2_tank));
    std::weak_ptr<Trackable> tank_track_wp = std::dynamic_pointer_cast<Trackable>(tank_del_sp);
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    trackingManager.addNewEntity(tank_track_wp);
    trackingManager.manage(data);
    EXPECT_EQ(trackingManager.getP2PositionX(), 40);
    EXPECT_EQ(trackingManager.getP2PositionY(), 40);
    EXPECT_EQ(trackingManager.getP2Rotation(), 0);
    tank_mov_sp->moveForward();
    trackingManager.manage(data);
    EXPECT_EQ(trackingManager.getP2PositionX(), 40 + TANK_SPEED);
    EXPECT_EQ(trackingManager.getP2PositionY(), 40);
    EXPECT_EQ(trackingManager.getP2Rotation(), 0);
    tank_mov_sp->moveForward();
    trackingManager.manage(data);
    EXPECT_NE(trackingManager.getP2PositionX(), 30 + TANK_SPEED);
}
TEST (TrackingManager , correctlyTracksTurretEntity)
Definition at line 1161 of file ClassTests.cpp.
References TrackingManager::addNewEntity(), TrackingManager::getTurretPositionsX(), TrackingManager::getTurretPositionsY(), and TrackingManager::manage().
{
    TrackingManager trackingManager;
    GameManagementData data;
    std::shared_ptr<Deletable> turret_del_sp(new Turret(40,40,0));
    std::weak_ptr<Trackable> turret_track_wp = std::dynamic_pointer_cast<
      Trackable>(turret_del_sp);
    trackingManager.addNewEntity(turret_track_wp);
    trackingManager.manage(data);
    const std::vector<float>& turretVectorX = trackingManager.
      getTurretPositionsX();
    const std::vector<float>& turretVectorY = trackingManager.
      getTurretPositionsY();
// auto turrXPosIt = turretVectorX.begin();
// float turrXPos = *turrXPosIt;
// float turrYPos = turretVectorY[0];
// EXPECT_EQ(turrXPos, 1);
// EXPECT_EQ(turrXPos, 40);
// EXPECT_EQ(turrYPos, 40);
    //Test not finnished as gtest seems that it cannot handle vectors - due to its use of malloc perhaps?
}
TEST (TrackingManager , enablesTurretFireWhenTankAndTurretAreInRange)
Definition at line 1188 of file ClassTests.cpp.
References TrackingManager::addNewEntity(), GameManagementData::giveActionInfo(), TrackingManager::manage(), p1_tank, GameManagementData::resetActionsInfo(), and actions_info::turret_fire.
{
    TrackingManager trackingManager;
    GameManagementData data;
    data.resetActionsInfo();
    actions_info testActions = data.giveActionInfo();
    EXPECT_EQ(testActions.turret_fire, false);
    //Add a Turret to the manager
    std::shared_ptr<Deletable> turret_del_sp(new Turret(550,100,358));
    std::weak_ptr<Trackable> turret_track_wp = std::dynamic_pointer_cast<
      Trackable>(turret_del_sp);
    trackingManager.addNewEntity(turret_track_wp);
    //Add Tank to the manager
    std::shared_ptr<Deletable> tank_del_sp(new Tank(850,350,0,p1_tank));
    std::weak_ptr<Trackable> tank_track_wp = std::dynamic_pointer_cast<Trackable>(tank_del_sp);
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    trackingManager.addNewEntity(tank_track_wp);
    tank_mov_sp->moveForward();
    trackingManager.manage(data);
    testActions = data.giveActionInfo();
    EXPECT_EQ(testActions.turret_fire, false);
    tank_mov_sp->moveForward();
    trackingManager.manage(data);
    testActions = data.giveActionInfo();
    EXPECT_EQ(testActions.turret_fire, false);
}
TEST (MoveManager , correctlyMovesTankEntityForP1)
*===================================================*/
*================Tests for MoveManager Class============*/
Definition at line 1224 of file ClassTests.cpp.
References MoveManager::addNewEntity(), MoveManager::manage(), GameManagementData::moveForwardP1(), p1_tank, GameManagementData::resetActionsInfo(), and TANK_SPEED.
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p1_tank));
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    std::shared_ptr<Trackable> tank_track_sp = std::dynamic_pointer_cast<
      Trackable>(tank_del_sp);
    moveManager.addNewEntity(tank_mov_sp);
    moveManager.manage(data);
    EXPECT_NE(tank_track_sp->getPositionX(), 30 + TANK_SPEED);
    data.moveForwardP1();
    moveManager.manage(data);
    EXPECT_EQ(tank_track_sp->getPositionX(), 30 + TANK_SPEED);
    EXPECT_NE(tank_track_sp->getPositionY(), 30 + TANK_SPEED);
}
TEST (MoveManager , correctlyMovesTankEntityForP2)
Definition at line 1246 of file ClassTests.cpp.
References MoveManager::addNewEntity(), MoveManager::manage(), GameManagementData::moveForwardP2(), p2_tank, GameManagementData::resetActionsInfo(), and TANK_SPEED.
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p2_tank));
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    std::shared_ptr<Trackable> tank_track_sp = std::dynamic_pointer_cast<
      Trackable>(tank_del_sp);
    moveManager.addNewEntity(tank_mov_sp);
    moveManager.manage(data);
    EXPECT_NE(tank_track_sp->getPositionX(), 30 + TANK_SPEED);
    data.moveForwardP2();
    moveManager.manage(data);
    EXPECT_EQ(tank_track_sp->getPositionX(), 30 + TANK_SPEED);
    EXPECT_NE(tank_track_sp->getPositionY(), 30 + TANK_SPEED);
}
TEST (MoveManager , correctlyMovesMissileEntityForP1)
Definition at line 1268 of file ClassTests.cpp.
References MoveManager::addNewEntity(), MoveManager::manage(), MISSILE_SPEED, p1_missile, and GameManagementData::resetActionsInfo().
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> missile_del_sp(new Missile(30,30,0,
      p1_missile));
    std::shared_ptr<Movable> missile_mov_sp = std::dynamic_pointer_cast<Movable>(missile_del_sp);
    moveManager.addNewEntity(missile_mov_sp);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawPositionX(), 30 + MISSILE_SPEED);
    EXPECT_NE(missile_del_sp->getDrawPositionY(), 30 + MISSILE_SPEED);
    moveManager.manage(data);
    moveManager.manage(data);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawPositionX(), 30 + 4*MISSILE_SPEED);
    EXPECT_EQ(missile_del_sp->getDrawPositionY(), 30);
}
TEST (MoveManager , correctlyMovesMissileEntityForP2)
Definition at line 1291 of file ClassTests.cpp.
References MoveManager::addNewEntity(), MoveManager::manage(), MISSILE_SPEED, p2_missile, and GameManagementData::resetActionsInfo().
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> missile_del_sp(new Missile(30,30,0,
      p2_missile));
    std::shared_ptr<Movable> missile_mov_sp = std::dynamic_pointer_cast<Movable>(missile_del_sp);
    moveManager.addNewEntity(missile_mov_sp);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawPositionX(), 30 + MISSILE_SPEED);
    EXPECT_NE(missile_del_sp->getDrawPositionY(), 30 + MISSILE_SPEED);
    moveManager.manage(data);
    moveManager.manage(data);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawPositionX(), 30 + 4*MISSILE_SPEED);
    EXPECT_EQ(missile_del_sp->getDrawPositionY(), 30);
}
TEST (MoveManager , doesNotMoveTankIfBlocked_P1)
Definition at line 1314 of file ClassTests.cpp.
References MoveManager::addNewEntity(), blocked, MoveManager::manage(), MISSILE_SPEED, p1_tank, and GameManagementData::resetActionsInfo().
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p1_tank));
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    std::shared_ptr<Collidable> tank_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank_del_sp);
    moveManager.addNewEntity(tank_mov_sp);
    tank_collide_sp->setBlocked(blocked);
    moveManager.manage(data);
    EXPECT_NE(tank_del_sp->getDrawPositionX(), 30 + MISSILE_SPEED);
    EXPECT_EQ(tank_del_sp->getDrawPositionY(), 30);
    moveManager.manage(data);
    moveManager.manage(data);
    moveManager.manage(data);
    EXPECT_EQ(tank_del_sp->getDrawPositionX(), 30);
    EXPECT_EQ(tank_del_sp->getDrawPositionY(), 30);
}
TEST (MoveManager , doesNotMoveTankIfBlocked_P2)
Definition at line 1340 of file ClassTests.cpp.
References MoveManager::addNewEntity(), blocked, MoveManager::manage(), MISSILE_SPEED, p2_tank, and GameManagementData::resetActionsInfo().
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p2_tank));
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    std::shared_ptr<Collidable> tank_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank_del_sp);
    moveManager.addNewEntity(tank_mov_sp);
    tank_collide_sp->setBlocked(blocked);
    moveManager.manage(data);
    EXPECT_NE(tank_del_sp->getDrawPositionX(), 30 + MISSILE_SPEED);
    EXPECT_EQ(tank_del_sp->getDrawPositionY(), 30);
    moveManager.manage(data);
    moveManager.manage(data);
    moveManager.manage(data);
    EXPECT_EQ(tank_del_sp->getDrawPositionX(), 30);
    EXPECT_EQ(tank_del_sp->getDrawPositionY(), 30);
}
TEST (MoveManager , missileReflectsCorrectlyIfBlockedHorizontally)
Definition at line 1366 of file ClassTests.cpp.
References MoveManager::addNewEntity(), blocked_horizontally, MoveManager::manage(), MISSILE_SPEED, p1_missile, and GameManagementData::resetActionsInfo().
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> missile_del_sp(new Missile(30,30,0,
      p1_missile));
    std::shared_ptr<Movable> missile_mov_sp = std::dynamic_pointer_cast<Movable>(missile_del_sp);
    std::shared_ptr<Collidable> missile_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile_del_sp);
    moveManager.addNewEntity(missile_mov_sp);
    missile_collide_sp->setBlocked(blocked_horizontally);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawRotation(), 180);
    EXPECT_EQ(missile_del_sp->getDrawPositionX(), 30 - MISSILE_SPEED);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawRotation(), 0);
    EXPECT_EQ(missile_del_sp->getDrawPositionX(), 30);
}
TEST (MoveManager , missileReflectsCorrectlyIfBlockedVertically)
Definition at line 1388 of file ClassTests.cpp.
References MoveManager::addNewEntity(), blocked_vertically, MoveManager::manage(), MISSILE_SPEED, p1_missile, and GameManagementData::resetActionsInfo().
{
    MoveManager moveManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> missile_del_sp(new Missile(30,30,90,
      p1_missile));
    std::shared_ptr<Movable> missile_mov_sp = std::dynamic_pointer_cast<Movable>(missile_del_sp);
    std::shared_ptr<Collidable> missile_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile_del_sp);
    moveManager.addNewEntity(missile_mov_sp);
    missile_collide_sp->setBlocked(blocked_vertically);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawRotation(), 270);
    EXPECT_EQ(missile_del_sp->getDrawPositionY(), 30 - MISSILE_SPEED);
    moveManager.manage(data);
    EXPECT_EQ(missile_del_sp->getDrawRotation(), 90);
    EXPECT_EQ(missile_del_sp->getDrawPositionY(), 30);
}
TEST (DestructionManager , correctlyDeletesTankEntityFromGame)
*===================================================*/
*================Tests for DestructionManager Class============*/
Definition at line 1414 of file ClassTests.cpp.
References DestructionManager::addNewEntity(), DestructionManager::manage(), p1_tank, and p2_tank.
{
    DestructionManager destructionManager;
    GameManagementData data;
    std::shared_ptr<Deletable> tank1_del_sp(new Tank(10,10,0,p1_tank));
    std::shared_ptr<Collidable> tank1_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank1_del_sp);
    std::shared_ptr<Deletable> tank2_del_sp(new Tank(10,10,0,p2_tank));
    std::shared_ptr<Collidable> tank2_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank2_del_sp);
    destructionManager.addNewEntity(tank1_del_sp);
    destructionManager.addNewEntity(tank2_del_sp);
    //Check number of shared pointers for each entity - this should be 3 now
    EXPECT_EQ(tank1_del_sp.use_count(), 3);
    EXPECT_EQ(tank2_del_sp.use_count(), 3);
    tank1_collide_sp->setCollided();
    tank2_collide_sp->setCollided();
    destructionManager.manage(data);
    //Check number of shared pointers for each entity - this should be 2 now
    EXPECT_EQ(tank1_del_sp.use_count(), 2);
    EXPECT_EQ(tank2_del_sp.use_count(), 2);
}
TEST (DestructionManager , correctlyDeletesMissileEntityFromGame)
Definition at line 1440 of file ClassTests.cpp.
References DestructionManager::addNewEntity(), DestructionManager::manage(), p1_missile, and p2_missile.
{
    DestructionManager destructionManager;
    GameManagementData data;
    std::shared_ptr<Deletable> missile1_del_sp(new Missile(10,10,0,
      p1_missile));
    std::shared_ptr<Collidable> missile1_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile1_del_sp);
    std::shared_ptr<Deletable> missile2_del_sp(new Missile(10,10,0,
      p2_missile));
    std::shared_ptr<Collidable> missile2_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile2_del_sp);
    destructionManager.addNewEntity(missile1_del_sp);
    destructionManager.addNewEntity(missile2_del_sp);
    //Check number of shared pointers for each entity - this should be 3 now
    EXPECT_EQ(missile1_del_sp.use_count(), 3);
    EXPECT_EQ(missile2_del_sp.use_count(), 3);
    missile1_collide_sp->setCollided();
    missile2_collide_sp->setCollided();
    destructionManager.manage(data);
    //Check number of shared pointers for each entity - this should be 2 now
    EXPECT_EQ(missile1_del_sp.use_count(), 2);
    EXPECT_EQ(missile2_del_sp.use_count(), 2);
}
TEST (DestructionManager , correctlyDeletesMineEntityFromGame)
Definition at line 1466 of file ClassTests.cpp.
References DestructionManager::addNewEntity(), DestructionManager::manage(), p1_mine, and p2_mine.
{
    DestructionManager destructionManager;
    GameManagementData data;
    std::shared_ptr<Deletable> mine1_del_sp(new Mine(10,10,p1_mine));
    std::shared_ptr<Collidable> mine1_collide_sp = std::dynamic_pointer_cast<
      Collidable>(mine1_del_sp);
    std::shared_ptr<Deletable> mine2_del_sp(new Mine(10,10,p2_mine));
    std::shared_ptr<Collidable> mine2_collide_sp = std::dynamic_pointer_cast<
      Collidable>(mine2_del_sp);
    destructionManager.addNewEntity(mine1_del_sp);
    destructionManager.addNewEntity(mine2_del_sp);
    //Check number of shared pointers for each entity - this should be 3 now
    EXPECT_EQ(mine1_del_sp.use_count(), 3);
    EXPECT_EQ(mine2_del_sp.use_count(), 3);
    mine1_collide_sp->setCollided();
    mine2_collide_sp->setCollided();
    destructionManager.manage(data);
    //Check number of shared pointers for each entity - this should be 2 now
    EXPECT_EQ(mine1_del_sp.use_count(), 2);
    EXPECT_EQ(mine2_del_sp.use_count(), 2);
}
TEST (DestructionManager , correctlyDeletesTurretEntityFromGame)
Definition at line 1492 of file ClassTests.cpp.
References DestructionManager::addNewEntity(), and DestructionManager::manage().
{
    DestructionManager destructionManager;
    GameManagementData data;
    std::shared_ptr<Deletable> turret_del_sp(new Turret(10,10,0));
    std::shared_ptr<Collidable> turret_collide_sp = std::dynamic_pointer_cast<
      Collidable>(turret_del_sp);
    destructionManager.addNewEntity(turret_del_sp);
    //Check number of shared pointers for each entity - this should be 3 now
    EXPECT_EQ(turret_del_sp.use_count(), 3);
    turret_collide_sp->setCollided();
    destructionManager.manage(data);
    //Check number of shared pointers for each entity - this should be 2 now
    EXPECT_EQ(turret_del_sp.use_count(), 2);
}
TEST (DestructionManager , correctlyIncreasesPlayerScoresUponTheirDeath)
Definition at line 1513 of file ClassTests.cpp.
References DestructionManager::addNewEntity(), GameManagementData::getP1Score(), GameManagementData::getP2Score(), DestructionManager::manage(), p1_tank, p2_tank, and GameManagementData::resetActionsInfo().
{
    DestructionManager destructionManager;
    GameManagementData data;
    data.resetActionsInfo();
    std::shared_ptr<Deletable> tank1_del_sp(new Tank(10,10,0,p1_tank));
    std::shared_ptr<Collidable> tank1_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank1_del_sp);
    std::shared_ptr<Deletable> tank2_del_sp(new Tank(10,10,0,p2_tank));
    std::shared_ptr<Collidable> tank2_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank2_del_sp);
    destructionManager.addNewEntity(tank1_del_sp);
    destructionManager.addNewEntity(tank2_del_sp);
    //Check number of shared pointers for each entity - this should be 3 now
    EXPECT_EQ(data.getP1Score(), 0);
    EXPECT_EQ(data.getP2Score(), 0);
    tank1_collide_sp->setCollided();
    tank2_collide_sp->setCollided();
    destructionManager.manage(data);
    //Check number of shared pointers for each entity - this should be 2 now
    EXPECT_EQ(data.getP1Score(), 1);
    EXPECT_EQ(data.getP2Score(), 1);
}
TEST (GameStateManager , doesNotAllowCreationOfMissileBeforeTimerExpiers)
*==============================================================*/
*================Tests for StateManager Class============*/
Definition at line 1542 of file ClassTests.cpp.
References actions_info::attack_1, actions_info::attack_2, do_nothing, fire_missile, GameManagementData::giveActionInfo(), GameStateManager::manage(), GameManagementData::missileFiredP1(), and GameManagementData::missileFiredP2().
{
    GameStateManager gameMan;
    GameManagementData data;
    data.missileFiredP1();
    data.missileFiredP2();
    gameMan.manage(data);
    actions_info actionsBox = data.giveActionInfo();
    EXPECT_EQ(actionsBox.attack_1, fire_missile);
    EXPECT_EQ(actionsBox.attack_2, fire_missile);
    gameMan.manage(data);
    actionsBox = data.giveActionInfo();
    EXPECT_EQ(actionsBox.attack_1, do_nothing);
    EXPECT_EQ(actionsBox.attack_2, do_nothing);
}
TEST (GameStateManager , doesNotAllowCreationOfMineBeforeTimerExpiers)
Definition at line 1564 of file ClassTests.cpp.
References actions_info::attack_1, actions_info::attack_2, do_nothing, GameManagementData::giveActionInfo(), lay_mine, GameStateManager::manage(), GameManagementData::mineLaidP1(), and GameManagementData::mineLaidP2().
{
    GameStateManager gameMan;
    GameManagementData data;
    data.mineLaidP1();
    data.mineLaidP2();
    gameMan.manage(data);
    actions_info actionsBox = data.giveActionInfo();
    EXPECT_EQ(actionsBox.attack_1, lay_mine);
    EXPECT_EQ(actionsBox.attack_2, lay_mine);
    gameMan.manage(data);
    actionsBox = data.giveActionInfo();
    EXPECT_EQ(actionsBox.attack_1, do_nothing);
    EXPECT_EQ(actionsBox.attack_2, do_nothing);
}
TEST (TurretManager , CorrectlyRotatesTurretEntity)
*==============================================================*/
*================Tests for TurretManager Class============*/
Definition at line 1591 of file ClassTests.cpp.
References TurretManager::addNewEntity(), TurretManager::manage(), and TURRET_ROTATION_SPEED.
{
    TurretManager turManager;
    std::shared_ptr<Deletable> turret_del_sp(new Turret(30,30,2));
    std::weak_ptr<Turret> turret_tur_sp = std::dynamic_pointer_cast<Turret>(turret_del_sp);
    turManager.addNewEntity(turret_tur_sp);
    EXPECT_EQ(turret_del_sp->getDrawRotation(), 2);
    turManager.manage();
    EXPECT_EQ(turret_del_sp->getDrawRotation(), 2 + TURRET_ROTATION_SPEED);
    turManager.manage();
    turManager.manage();
    turManager.manage();
    EXPECT_EQ(turret_del_sp->getDrawRotation(), 360 + 3*TURRET_ROTATION_SPEED);
}
TEST (CollisionManager , correctlyBlocksTanksAndBarriers)
*==============================================================*/
*================Tests for CollisioniManager Class============*/
Definition at line 1615 of file ClassTests.cpp.
References CollisionManager::addNewEntity(), barrier, blocked, CollisionManager::manage(), p1_tank, and unblocked.
{
    CollisionManager colisionManager;
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p1_tank));
    std::shared_ptr<Collidable> tank_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank_del_sp);
    std::shared_ptr<Movable> tank_mov_sp = std::dynamic_pointer_cast<Movable>(tank_del_sp);
    colisionManager.addNewEntity(tank_collide_sp);
    std::shared_ptr<Deletable> barrier_del_sp(new Barrier(50,50,barrier));
    std::shared_ptr<Collidable> barrier_collide_sp = std::dynamic_pointer_cast<
      Collidable>(barrier_del_sp);
    std::shared_ptr<Movable> barrier_mov_sp = std::dynamic_pointer_cast<Movable>(barrier_del_sp);
    colisionManager.addNewEntity(barrier_collide_sp);
    EXPECT_EQ(tank_mov_sp->isBlocked(), unblocked);
    colisionManager.manage();
    EXPECT_EQ(tank_mov_sp->isBlocked(), blocked);
}
TEST (CollisionManager , correctlyBlocksTanksAndTanks)
Definition at line 1638 of file ClassTests.cpp.
References CollisionManager::addNewEntity(), blocked, CollisionManager::manage(), p1_tank, p2_tank, and unblocked.
{
    CollisionManager colisionManager;
    std::shared_ptr<Deletable> tank1_del_sp(new Tank(30,30,0,p1_tank));
    std::shared_ptr<Collidable> tank1_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank1_del_sp);
    std::shared_ptr<Movable> tank1_mov_sp = std::dynamic_pointer_cast<Movable>(tank1_del_sp);
    colisionManager.addNewEntity(tank1_collide_sp);
    std::shared_ptr<Deletable> tank2_del_sp(new Tank(50,50,0,p2_tank));
    std::shared_ptr<Collidable> tank2_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank2_del_sp);
    std::shared_ptr<Movable> tank2_mov_sp = std::dynamic_pointer_cast<Movable>(tank2_del_sp);
    colisionManager.addNewEntity(tank2_collide_sp);
    EXPECT_EQ(tank1_mov_sp->isBlocked(), unblocked);
    EXPECT_EQ(tank2_mov_sp->isBlocked(), unblocked);
    colisionManager.manage();
    EXPECT_EQ(tank2_mov_sp->isBlocked(), blocked);
    EXPECT_EQ(tank1_mov_sp->isBlocked(), blocked);
}
TEST (CollisionManager , correctlyBlocksMissilesAndBarriers)
Definition at line 1663 of file ClassTests.cpp.
References CollisionManager::addNewEntity(), barrier, CollisionManager::manage(), p1_missile, and unblocked.
{
    CollisionManager colisionManager;
    std::shared_ptr<Deletable> missile_del_sp(new Missile(48,48,0,
      p1_missile));
    std::shared_ptr<Collidable> missile_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile_del_sp);
    std::shared_ptr<Movable> missile_mov_sp = std::dynamic_pointer_cast<Movable>(missile_del_sp);
    colisionManager.addNewEntity(missile_collide_sp);
    std::shared_ptr<Deletable> barrier_del_sp(new Barrier(50,50,barrier));
    std::shared_ptr<Collidable> barrier_collide_sp = std::dynamic_pointer_cast<
      Collidable>(barrier_del_sp);
    std::shared_ptr<Movable> barrier_mov_sp = std::dynamic_pointer_cast<Movable>(barrier_del_sp);
    colisionManager.addNewEntity(barrier_collide_sp);
    EXPECT_EQ(missile_mov_sp->isBlocked(), unblocked);
    colisionManager.manage();
    EXPECT_EQ(missile_mov_sp->isBlocked(), unblocked);
}
TEST (CollisionManager , indicatesCollisionHasTakenPlace)
Definition at line 1686 of file ClassTests.cpp.
References GeometryEngine::isCollision(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
{
    rect_corners rect_A;
    rect_corners rect_B;
    rect_A.upper_left.x = 1.0;
    rect_A.upper_left.y = 8.0;
    rect_A.upper_right.x = 5.0;
    rect_A.upper_right.y = 8.0;
    rect_A.lower_left.x = 1.0;
    rect_A.lower_left.y = 1.0;
    rect_A.lower_right.x = 5.0;
    rect_A.lower_right.y = 1.0;
    rect_B.upper_left.x = 2.0;
    rect_B.upper_left.y = 9.0;
    rect_B.upper_right.x = 6.0;
    rect_B.upper_right.y = 8.0;
    rect_B.lower_left.x = 2.0;
    rect_B.lower_left.y = 2.0;
    rect_B.lower_right.x = 6.0;
    rect_B.lower_right.y = 2.0;
    GeometryEngine collision_helper;
    EXPECT_TRUE(collision_helper.isCollision(rect_A, rect_B));
}
TEST (CollisionManager , correctlyCollidesTanksAndMissiles)
Definition at line 1714 of file ClassTests.cpp.
References CollisionManager::addNewEntity(), CollisionManager::manage(), p1_tank, and p2_missile.
{
    CollisionManager colisionManager;
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p1_tank));
    std::shared_ptr<Collidable> tank_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank_del_sp);
    colisionManager.addNewEntity(tank_collide_sp);
    std::shared_ptr<Deletable> missile_del_sp(new Missile(50,50, 0 ,
      p2_missile));
    std::shared_ptr<Collidable> missile_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile_del_sp);
    colisionManager.addNewEntity(missile_collide_sp);
    EXPECT_FALSE(tank_del_sp->isDeleted());
    EXPECT_FALSE(missile_del_sp->isDeleted());
    colisionManager.manage();
    EXPECT_TRUE(tank_del_sp->isDeleted());
    EXPECT_TRUE(missile_del_sp->isDeleted());
}
TEST (CollisionManager , correctlyCollidesMissilesAndMissiles)
Definition at line 1737 of file ClassTests.cpp.
References CollisionManager::addNewEntity(), CollisionManager::manage(), p1_missile, and p2_missile.
{
    CollisionManager colisionManager;
    std::shared_ptr<Deletable> missile1_del_sp(new Missile(49,49,0,
      p1_missile));
    std::shared_ptr<Collidable> missile1_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile1_del_sp);
    colisionManager.addNewEntity(missile1_collide_sp);
    std::shared_ptr<Deletable> missile2_del_sp(new Missile(50,50, 0 ,
      p2_missile));
    std::shared_ptr<Collidable> missile2_collide_sp = std::dynamic_pointer_cast<
      Collidable>(missile2_del_sp);
    colisionManager.addNewEntity(missile2_collide_sp);
    EXPECT_FALSE(missile1_del_sp->isDeleted());
    EXPECT_FALSE(missile2_del_sp->isDeleted());
    colisionManager.manage();
    EXPECT_TRUE(missile1_del_sp->isDeleted());
    EXPECT_TRUE(missile2_del_sp->isDeleted());
}
TEST (CollisionManager , correctlyCollidesTanksAndMines)
Definition at line 1760 of file ClassTests.cpp.
References CollisionManager::addNewEntity(), CollisionManager::manage(), p1_tank, and p2_mine.
{
    CollisionManager colisionManager;
    std::shared_ptr<Deletable> tank_del_sp(new Tank(30,30,0,p1_tank));
    std::shared_ptr<Collidable> tank_collide_sp = std::dynamic_pointer_cast<
      Collidable>(tank_del_sp);
    colisionManager.addNewEntity(tank_collide_sp);
    std::shared_ptr<Deletable> mine_del_sp(new Mine(50,50,p2_mine));
    std::shared_ptr<Collidable> mine_collide_sp = std::dynamic_pointer_cast<
      Collidable>(mine_del_sp);
    colisionManager.addNewEntity(mine_collide_sp);
    EXPECT_FALSE(tank_del_sp->isDeleted());
    EXPECT_FALSE(mine_del_sp->isDeleted());
    colisionManager.manage();
    EXPECT_TRUE(tank_del_sp->isDeleted());
    EXPECT_TRUE(mine_del_sp->isDeleted());
}