Mine Class Reference
Model class for a Mine.
#include <Mine.h>
Public Member Functions
Mine (float positionX, float positionY, entity_type mineOwner)
Mine entity constructor.
virtual const entity_type & getType () const
Mine is able to provide its identification.
virtual const rect_corners & getBoundingBox ()
Provide the bounding box for the mine entity.
virtual const rect_corners & getAlignedBoundingBox ()
Get Axis Aligned bounding box of entity.
virtual void setUnblocked ()
This function is not used by the mine.
virtual const int setBlocked (const blocked_status obstruction_type)
This function is not used by mine.
virtual void setCollided ()
Set the colllision state of the mine.
virtual bool const isDeleted ()
Boolean state of the mine entities life.
virtual const float getDrawPositionX ()
Retrieve the Mine x Position.
virtual const float getDrawPositionY ()
Retrieve the Mine y Position.
virtual const float getDrawRotation ()
Recieve the Mine rotation.
virtual ~Mine ()
Mine object destructor.
Private Attributes
Orientation _mine
Co-cordinate system for Mine entity.
entity_type _type
Enumeration type defining the Mine.
bool _collidedStatus
Collision state of the Mine entity: 1 for collided, 0 for not.
SpriteDimensions _sprite_dimensions
Mine sprite dimensions.
Detailed Description
Model class for a Mine.
Definition at line 22 of file Mine.h.
Constructor & Destructor Documentation
Mine::Mine (float positionX, float positionY, entity_type mineOwner)
Mine entity constructor.
Throws exceptions if wrong tank owner of position. Initialises private data members
Parameters
positionX :: mine's x position
positionY :: mine's y position
mineOwner :: either player 1 or player 2 will own the mine
Definition at line 17 of file Mine.cpp.
References _collidedStatus, _mine, _sprite_dimensions, _type, SpriteDimensions::mine_sprite_x, SpriteDimensions::mine_sprite_y, p1_mine, p2_mine, Orientation::setHeight(), and Orientation::setWidth().
                                                                 :
    _mine(positionX,positionY,0.0,0.0,0.0, false),
    _sprite_dimensions()
{
    //Keep Class invariant
    if ((mineOwner != p1_mine) && (mineOwner != p2_mine)) throw
      InvalidConstructorArgumentsMine();
    if (positionX < 0) throw InvalidConstructorArgumentsMine();
    if (positionY < 0) throw InvalidConstructorArgumentsMine();
    _mine.setWidth(_sprite_dimensions.
      mine_sprite_x);
    _mine.setHeight(_sprite_dimensions.
      mine_sprite_y);
    _type = mineOwner;
    _collidedStatus = 0;
}
Mine::~Mine () [virtual]
Mine object destructor.
Definition at line 115 of file Mine.cpp.
{
    //This could possibly be added to
}
Member Function Documentation
const rect_corners & Mine::getAlignedBoundingBox () [virtual]
Get Axis Aligned bounding box of entity.
Provide the bounding box for the mine entity.
Returns
const rect_corners
Implements Collidable.
Definition at line 51 of file Mine.cpp.
References _mine, and Orientation::getAlignedGlobalBounds().
{
    return _mine.getAlignedGlobalBounds();
}
const rect_corners & Mine::getBoundingBox () [virtual]
Provide the bounding box for the mine entity.
Returns
const rect_corners
Implements Collidable.
Definition at line 43 of file Mine.cpp.
References _mine, and Orientation::getGlobalBounds().
{
    return _mine.getGlobalBounds();
}
const float Mine::getDrawPositionX () [virtual]
Retrieve the Mine x Position.
Implements Deletable.
Definition at line 91 of file Mine.cpp.
References _mine, and Orientation::getOriginX().
{
    return _mine.getOriginX();
}
const float Mine::getDrawPositionY () [virtual]
Retrieve the Mine y Position.
Implements Deletable.
Definition at line 99 of file Mine.cpp.
References _mine, and Orientation::getOriginY().
{
    return _mine.getOriginY();
}
const float Mine::getDrawRotation () [virtual]
Recieve the Mine rotation.
Implements Deletable.
Definition at line 107 of file Mine.cpp.
References _mine, and Orientation::getRotation().
{
    return _mine.getRotation();
}
const entity_type & Mine::getType () const [virtual]
Mine is able to provide its identification.
Returns
const entity_type
Implements Deletable.
Definition at line 35 of file Mine.cpp.
References _type.
Referenced by TEST().
{
    return _type;
}
const bool Mine::isDeleted () [virtual]
Boolean state of the mine entities life.
Boolean state of the mine entities.
Implements Deletable.
Definition at line 83 of file Mine.cpp.
References _collidedStatus.
Referenced by TEST().
{
    return _collidedStatus;
}
const int Mine::setBlocked (const blocked_status obstruction_type) [virtual]
This function is not used by mine.
Returns
const int
Implements Collidable.
Definition at line 59 of file Mine.cpp.
{
    return 1;
}
void Mine::setCollided () [virtual]
Set the colllision state of the mine.
Implements Collidable.
Definition at line 75 of file Mine.cpp.
References _collidedStatus.
Referenced by TEST().
{
    _collidedStatus = 1;
}
void Mine::setUnblocked () [virtual]
This function is not used by the mine.
This function is not used by mine.
Implements Collidable.
Definition at line 67 of file Mine.cpp.
{
    //This should be thought about and worked aound
}
Member Data Documentation
bool Mine::_collidedStatus [private]
Collision state of the Mine entity: 1 for collided, 0 for not.
Definition at line 59 of file Mine.h.
Referenced by isDeleted(), Mine(), and setCollided().
Orientation Mine::_mine [private]
Co-cordinate system for Mine entity.
Definition at line 55 of file Mine.h.
Referenced by getAlignedBoundingBox(), getBoundingBox(), getDrawPositionX(), getDrawPositionY(), getDrawRotation(), and Mine().
SpriteDimensions Mine::_sprite_dimensions [private]
Mine sprite dimensions.
Definition at line 61 of file Mine.h.
Referenced by Mine().
entity_type Mine::_type [private]
Enumeration type defining the Mine.
Definition at line 57 of file Mine.h.
Referenced by getType(), and Mine().
The documentation for this class was generated from the following files:
Mine.h
Mine.cpp