GeometryEngine Class Reference
Class responisible for handling geometrical calculations.
#include <GeometryEngine.h>
Public Member Functions
bool isCollision (const rect_corners &rect_A, const rect_corners &rect_B)
Function that client code can call to check final collision status.
bool isInLineOfFire (const float &rotation, const rect_corners &shooter, const rect_corners &target, const float &shooter_y, const float &target_y)
Function that checks of tank is in turrets line of fire.
const float calculateVectorLength (const float x_coord_1, const float y_coord_1, const float x_coord_2, const float y_coord_2)
Function to determine the vector lenght between two points.
bool isRectangleOverlapForAxis (coordinate axis, const rect_corners &rect_A, const rect_corners &rect_B)
Main function called to check overlap.
void calculateVectorProjections (std::vector< coordinate > &axis_projections, const rect_corners &rect, const coordinate &axis)
Calculates the projections of the rectangles vertices vectors onto an axis.
void calculateMaxAndMinProjectionMagnitude (const std::vector< coordinate > &axis_projections, const rect_corners &rect, const coordinate &axis, float &max, float &min)
Calculates which of the projected vectors are furtherest along.
const blocked_status getRelativePosition (const rect_corners &rect_entity, const rect_corners &compared_rect_entity)
Determine the relative positioning of two objects within the game.
Private Member Functions
bool lowwerPointsAboveTopOfObject (const rect_corners &rect_entity, const rect_corners &compared_rect_entity)
Compares points of two rectangles.
bool upperPointsBelowBottomOfObject (const rect_corners &rect_entity, const rect_corners &compared_rect_entity)
Compares points of two rectangles.
bool rightPointsLeftOfObject (const rect_corners &rect_entity, const rect_corners &compared_rect_entity)
Compares points of two rectangles.
bool leftPointsRightOfObject (const rect_corners &rect_entity, const rect_corners &compared_rect_entity)
Compares points of two rectangles.
bool isValidRectEntity (const rect_corners &rect_entity)
Checks if the rectangle enrty is valid.
Detailed Description
Class responisible for handling geometrical calculations.
Definition at line 21 of file GeometryEngine.h.
Member Function Documentation
void GeometryEngine::calculateMaxAndMinProjectionMagnitude (const std::vector< coordinate > & axis_projections, const rect_corners & rect, const coordinate & axis, float & max, float & min)
Calculates which of the projected vectors are furtherest along.
Determines which projections are the greatest.
Values for A and B are claculated and passed back by reference
Parameters
axis_projections :: holds the projected axis values
rect :: rectangle whose vertice projections are being calculated from
axis :: used for the calculations
max :: largest projection value saved here
min :: smallers projection value saved here
Returns
bool
Definition at line 157 of file GeometryEngine.cpp.
References coordinate::x, and coordinate::y.
Referenced by isRectangleOverlapForAxis().
{
    std::vector<float> projection_pos; // container that will indicate the projection position along axis
    auto projection = axis_projections.begin();
    for (; projection != axis_projections.end(); ++projection)
        projection_pos.push_back(((projection->x)*axis.x) + ((projection->y)*axis.
      y));
    min = *std::min_element(projection_pos.begin(), projection_pos.end());
    max = *std::max_element(projection_pos.begin(), projection_pos.end());
}
const float GeometryEngine::calculateVectorLength (const float x_coord_1, const float y_coord_1, const float x_coord_2, const float y_coord_2)
Function to determine the vector lenght between two points.
Calculates vector distance.
Used for determing if some geometrical object falls with a certain radius of the other
Parameters
x_coord_1 :: holds the projected axis values
y_coord_1 :: rectangle whose vertice projections are being calculated from
x_coord_2 :: used for the calculations
y_coord_2 :: largest projection value saved here
Returns
const float
Definition at line 177 of file GeometryEngine.cpp.
Referenced by TrackingManager::manage(), and TEST().
{
    return (sqrt(pow((x_coord_1 - x_coord_2),2) + pow((y_coord_1 - y_coord_2),2)));
}
void GeometryEngine::calculateVectorProjections (std::vector< coordinate > & axis_projections, const rect_corners & rect, const coordinate & axis)
Calculates the projections of the rectangles vertices vectors onto an axis.
Calculates axis projections from rectangle vertices onto an axis.
Parameters
axis_projections :: holds the projected axis values
rect :: rectangle whose vertice projections are being calculated from
axis :: used for the calculations
Returns
bool
Definition at line 127 of file GeometryEngine.cpp.
References rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
Referenced by isRectangleOverlapForAxis().
{
    coordinate point;
    point.x = ((rect.upper_right.x*axis.x + rect.upper_right.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.x;
    point.y = ((rect.upper_right.x*axis.x + rect.upper_right.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.y;
    axis_projections.push_back(point);
    point.x = ((rect.upper_left.x*axis.x + rect.upper_left.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.x;
    point.y = ((rect.upper_left.x*axis.x + rect.upper_left.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.y;
    axis_projections.push_back(point);
    point.x = ((rect.lower_right.x*axis.x + rect.lower_right.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.x;
    point.y = ((rect.lower_right.x*axis.x + rect.lower_right.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.y;
    axis_projections.push_back(point);
    point.x = ((rect.lower_left.x*axis.x + rect.lower_left.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.x;
    point.y = ((rect.lower_left.x*axis.x + rect.lower_left.
      y*axis.y)/(powf(axis.x, 2.0) + powf(axis.y, 2.0)))*axis.y;
    axis_projections.push_back(point);
}
const blocked_status GeometryEngine::getRelativePosition (const rect_corners & rect_entity, const rect_corners & compared_rect_entity)
Determine the relative positioning of two objects within the game.
Calculates vector distance.
Throws exception if rectangles are not valid data type.
Parameters
x_coord_1 :: holds the projected axis values
y_coord_1 :: rectangle whose vertice projections are being calculated from
x_coord_2 :: used for the calculations
y_coord_2 :: largest projection value saved here
Returns
const float
Definition at line 190 of file GeometryEngine.cpp.
References blocked_horizontally, blocked_vertically, isValidRectEntity(), leftPointsRightOfObject(), lowwerPointsAboveTopOfObject(), rightPointsLeftOfObject(), unblocked, and upperPointsBelowBottomOfObject().
Referenced by CollisionManager::getResultingBlockedStatus(), and TEST().
{
    if (!isValidRectEntity(rect_entity)) throw
      InvalidRectEntityProvided();
    if (!isValidRectEntity(compared_rect_entity)) throw
      InvalidRectEntityProvided();
    blocked_status blocked_state = unblocked;
    if(upperPointsBelowBottomOfObject(rect_entity,compared_rect_entity))
    {
        blocked_state = blocked_vertically;
    }
    else if(rightPointsLeftOfObject(rect_entity,compared_rect_entity))
    {
        blocked_state = blocked_horizontally;
    }
    else if(leftPointsRightOfObject(rect_entity,compared_rect_entity))
    {
        blocked_state = blocked_horizontally;
    }
    else if(lowwerPointsAboveTopOfObject(rect_entity,compared_rect_entity))
    {
        blocked_state = blocked_vertically;
    }
    return blocked_state;
}
bool GeometryEngine::isCollision (const rect_corners & rect_A, const rect_corners & rect_B)
Function that client code can call to check final collision status.
Determines if two rectangles have collided.
Throws an exception if invald arguments are given. The function goes through each axis projections checking for an overlap.
Parameters
rect_A :: Rectangle A
rect_B :: Rectangle B
Returns
bool
Definition at line 22 of file GeometryEngine.cpp.
References isRectangleOverlapForAxis(), isValidRectEntity(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
Referenced by CollisionManager::reviewCollisionStates(), and TEST().
{
    if (!isValidRectEntity(rect_A)) throw
      InvalidRectEntityProvided();
    if (!isValidRectEntity(rect_B)) throw
      InvalidRectEntityProvided();
    coordinate axis;
    axis.x = rect_A.upper_right.x - rect_A.upper_left.x;
    axis.y = rect_A.upper_right.y - rect_A.upper_left.y;
    if (!isRectangleOverlapForAxis(axis, rect_A, rect_B))
        return false;
    axis.x = rect_A.upper_right.x - rect_A.lower_right.x;
    axis.y = rect_A.upper_right.y - rect_A.lower_right.y;
    if (!isRectangleOverlapForAxis(axis, rect_A, rect_B))
        return false;
    axis.x = rect_B.upper_left.x - rect_B.lower_left.x;
    axis.y = rect_B.upper_left.y - rect_B.lower_left.y;
    if (!isRectangleOverlapForAxis(axis, rect_A, rect_B))
        return false;
    axis.x = rect_B.upper_left.x - rect_B.upper_right.x;
    axis.y = rect_B.upper_left.y - rect_B.upper_right.y;
    if (!isRectangleOverlapForAxis(axis, rect_A, rect_B))
        return false;
    return true;
}
bool GeometryEngine::isInLineOfFire (const float & rotation, const rect_corners & shooter, const rect_corners & target, const float & shooter_y, const float & target_y)
Function that checks of tank is in turrets line of fire.
Determines rectangle is inline of sight of another.
Uses the shooter rotation to determine what angle the turret is sitting at. Based on this angle, the turrt will behave differently. This is because, using the separating axis theorem creates a single axis for two opposites sides of a square. This is why a shooter would detect something from behind
Parameters
rotation :: shooter rotation
shooter :: rectangle corners of the shooter
target :: rectangle corners of the target
Returns
bool
Definition at line 62 of file GeometryEngine.cpp.
References isRectangleOverlapForAxis(), rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
Referenced by TrackingManager::manage(), and TEST().
{
    coordinate axis;
    //develop axis based on the rotation of the shooter
    axis.x = shooter.lower_left.x - shooter.upper_left.x; //axis along the turret
       barrel
    axis.y = shooter.lower_left.y - shooter.upper_left.y;
    if (rotation >= 180.0 && rotation <= 359.0)
    {
        if (isRectangleOverlapForAxis(axis, shooter, target))
        { // also check if the target is above the shooter
            if ((target_y <= shooter_y) && (target.upper_right.y <= shooter_y) && (target.
      upper_left.y <= shooter_y)
                                        && (target.lower_right.y <= shooter_y) && (target.
      lower_left.y <= shooter_y))
                return true;
        }
    }
    else if (rotation >= 0.0 && rotation <= 179.0)
    {
        if (isRectangleOverlapForAxis(axis, shooter, target))
        { // also check if the target is below the shooter
            if ((target_y >= shooter_y) && (target.lower_right.y >= shooter_y) && (target.
      lower_left.y >= shooter_y)
                                        && (target.upper_right.y >= shooter_y) && (target.
      upper_left.y >= shooter_y))
                return true;
        }
    }
    return false;
}
bool GeometryEngine::isRectangleOverlapForAxis (coordinate axis, const rect_corners & rect_A, const rect_corners & rect_B)
Main function called to check overlap.
Determines if there is an overlap on this axis.
Overlaps are calculated for axis projected axis. The projections for both reactangles A and B are compared.
Parameters
axis :: and x y vector
rect_A :: rectangle corners of A
rect_B :: rectangle corners of B
Returns
bool
Definition at line 99 of file GeometryEngine.cpp.
References calculateMaxAndMinProjectionMagnitude(), and calculateVectorProjections().
Referenced by isCollision(), isInLineOfFire(), and TEST().
{
    float max_A = 0.0;
    float min_A = 0.0; // scalar values of dot products between axis and projection
    float max_B = 0.0;
    float min_B = 0.0;
    std::vector<coordinate> axis_projections_A;
    std::vector<coordinate> axis_projections_B;
    calculateVectorProjections(axis_projections_A, rect_A, axis);
    calculateVectorProjections(axis_projections_B, rect_B, axis);
    calculateMaxAndMinProjectionMagnitude(axis_projections_A, rect_A,
      axis, max_A, min_A);
    calculateMaxAndMinProjectionMagnitude(axis_projections_B, rect_B,
      axis, max_B, min_B);
    if ((min_B <= max_A) && (max_B >= min_A))
        return true;
    else
        return false;
}
bool GeometryEngine::isValidRectEntity (const rect_corners & rect_entity) [private]
Checks if the rectangle enrty is valid.
Parameters
rect_entity :: rectangle that is being checked
Returns
bool
Definition at line 280 of file GeometryEngine.cpp.
References rect_corners::lower_left, rect_corners::lower_right, rect_corners::upper_left, rect_corners::upper_right, coordinate::x, and coordinate::y.
Referenced by getRelativePosition(), and isCollision().
{
    if (rect_entity.lower_left.x < -100) return false;
    else if (rect_entity.lower_right.x < -100) return false;
    else if (rect_entity.upper_left.x < -100) return false;
    else if (rect_entity.upper_right.x < -100) return false;
    else if (rect_entity.lower_left.y < -100) return false;
    else if (rect_entity.lower_right.y < -100) return false;
    else if (rect_entity.upper_left.y < -100) return false;
    else if (rect_entity.upper_right.y < -100) return false;
    else return true;
}
bool GeometryEngine::leftPointsRightOfObject (const rect_corners & rect_entity, const rect_corners & compared_rect_entity) [private]
Compares points of two rectangles.
Compared upper left and right y coordinate points. Also checks to see if one is left of the other.
Parameters
rect_entity :: holds the projected axis values
compared_rect_entity :: rectangle whose vertice projections are being calculated from
Returns
bool
Definition at line 268 of file GeometryEngine.cpp.
References rect_corners::lower_right, rect_corners::upper_right, and coordinate::x.
Referenced by getRelativePosition().
{
    if ((rect_entity.upper_right.x >= compared_rect_entity.
      upper_right.x) &&
        (rect_entity.lower_right.x >= compared_rect_entity.
      lower_right.x))
            return true;
    else return false;
}
bool GeometryEngine::lowwerPointsAboveTopOfObject (const rect_corners & rect_entity, const rect_corners & compared_rect_entity) [private]
Compares points of two rectangles.
Compared upper left and right y coordinate points.
Parameters
rect_entity :: holds the projected axis values
compared_rect_entity :: rectangle whose vertice projections are being calculated from
Returns
bool
Definition at line 226 of file GeometryEngine.cpp.
References rect_corners::upper_left, rect_corners::upper_right, and coordinate::y.
Referenced by getRelativePosition().
{
    if ((rect_entity.upper_left.y >= compared_rect_entity.upper_left.
      y) &&
        (rect_entity.upper_right.y >= compared_rect_entity.
      upper_right.y))
            return true;
    else return false;
}
bool GeometryEngine::rightPointsLeftOfObject (const rect_corners & rect_entity, const rect_corners & compared_rect_entity) [private]
Compares points of two rectangles.
Compared lower left and right y coordinate points. Also checks to see if one is right of the other.
Parameters
rect_entity :: holds the projected axis values
compared_rect_entity :: rectangle whose vertice projections are being calculated from
Returns
bool
Definition at line 254 of file GeometryEngine.cpp.
References rect_corners::lower_left, rect_corners::upper_left, and coordinate::x.
Referenced by getRelativePosition().
{
    if ((rect_entity.lower_left.x <= compared_rect_entity.lower_left.
      x) &&
        (rect_entity.upper_left.x <= compared_rect_entity.upper_left.
      x))
            return true;
    else return false;
}
bool GeometryEngine::upperPointsBelowBottomOfObject (const rect_corners & rect_entity, const rect_corners & compared_rect_entity) [private]
Compares points of two rectangles.
Compared lower left and right y coordinate points.
Parameters
rect_entity :: holds the projected axis values
compared_rect_entity :: rectangle whose vertice projections are being calculated from
Returns
bool
Definition at line 240 of file GeometryEngine.cpp.
References rect_corners::lower_left, rect_corners::lower_right, and coordinate::y.
Referenced by getRelativePosition().
{
    if((rect_entity.lower_left.y <= compared_rect_entity.lower_left.
      y) &&
       (rect_entity.lower_right.y <= compared_rect_entity.
      lower_right.y))
            return true;
    else return false;
}
The documentation for this class was generated from the following files:
GeometryEngine.h
GeometryEngine.cpp