TurretManager Class Reference
Manager responsible for controlling the turrets rotation.
#include <TurretManager.h>
Public Member Functions
TurretManager ()
void manage ()
Manage turret movements.
void addNewEntity (std::weak_ptr< Turret > new_entity)
Add a new weak pointer to a game turrt.
virtual ~TurretManager ()
Private Member Functions
void removeGarbage ()
Removed weak pointers of objects that have been deleted.
Private Attributes
std::vector< std::weak_ptr
*
< Turret > > _turretables
Container for all weak pointers to game turret entities.
Detailed Description
Manager responsible for controlling the turrets rotation.
Definition at line 17 of file TurretManager.h.
Constructor & Destructor Documentation
TurretManager::TurretManager ()
Definition at line 11 of file TurretManager.cpp.
{
}
TurretManager::~TurretManager () [virtual]
Definition at line 16 of file TurretManager.cpp.
{
}
Member Function Documentation
void TurretManager::addNewEntity (std::weak_ptr< Turret > new_entity)
Add a new weak pointer to a game turrt.
All the turrets have weak pointers stored in the TurretManager private vector.
Definition at line 45 of file TurretManager.cpp.
References _turretables.
Referenced by Game::addTurretable(), and TEST().
{
    _turretables.push_back(new_entity);
}
void TurretManager::manage ()
Manage turret movements.
All turrets are simply rotated each time the manager runs
Definition at line 24 of file TurretManager.cpp.
References _turretables, and removeGarbage().
Referenced by Game::runAllManagers(), and TEST().
{
    //Clear the vector of deleted turret entities
    removeGarbage();
    auto turret_iterator = _turretables.begin();
    for (; turret_iterator != _turretables.end(); turret_iterator ++)
    {
        //Convert iterator to Weak pointer
        std::weak_ptr<Turret> entity_tur_wp = (*turret_iterator);
        //Lock as Shared Pointer
        std::shared_ptr<Turret> entity_tur_sp = entity_tur_wp.lock();
        entity_tur_sp->rotateTurret();
    }
}
void TurretManager::removeGarbage () [private]
Removed weak pointers of objects that have been deleted.
Definition at line 53 of file TurretManager.cpp.
References _turretables.
Referenced by manage().
{
    auto removable = _turretables.begin();
    for (; removable != _turretables.end();)
    {
        //Convert iterator to Weak pointer
        std::weak_ptr<Turret> removable_wp = (*removable);
        //Lock as Shared Pointer
        std::shared_ptr<Turret> removable_sp = removable_wp.lock();
        //Test to see if the shared pointer exists
        if (removable_sp)
        {
            removable++;
        }
        else
        {
            _turretables.erase(removable);
        }
    }
}
Member Data Documentation
std::vector<std::weak_ptr<Turret> > TurretManager::_turretables [private]
Container for all weak pointers to game turret entities.
Definition at line 27 of file TurretManager.h.
Referenced by addNewEntity(), manage(), and removeGarbage().
The documentation for this class was generated from the following files:
TurretManager.h
TurretManager.cpp