Turret Class Reference
#include <Turret.h>
Public Member Functions
Turret (float positionX, float positionY, float rotation)
Constructor.
virtual const entity_type & getType () const
Provide type.
virtual const bool isDeleted ()
Determine the life state of the Turrent.
virtual const float getDrawPositionX ()
Retrieve the entity's x Position.
virtual const float getDrawPositionY ()
Retrieve the entity's y Position.
virtual const float getDrawRotation ()
Retrieve the entity's Position.
virtual const rect_corners & getBoundingBox ()
Get bounding box of entity.
virtual const rect_corners & getAlignedBoundingBox ()
Get Axis Aligned bounding box of entity.
virtual const int setBlocked (const blocked_status obstruction_type)
Set blocked state of entity.
virtual void setUnblocked ()
Unset the blocked state of the entity.
virtual void setCollided ()
Set collision state of entity.
virtual const float getPositionX ()
Get the current x co-ordinates of Trackable object.
virtual const float getPositionY ()
Get the current y co-ordinates of Trackable object.
virtual const float getOrientation ()
Get the current orientation of Trackable object.
virtual const rect_corners & getTrackingBoundingBox ()
Get the bounding box relevant for line-of-fire detection.
void rotateTurret ()
Rotates the Turret by its set value.
virtual ~Turret ()
Destructor.
Private Attributes
bool _collidedStatus
Collision state of the Turrent Entity: 1 for collided, 0 for not.
float _rotation
The angle of rotation for the Turrnet entity.
Orientation _turret
Co-ordinate system for the Turrnet.
entity_type _type
Enumeration type defining the turrnet.
SpriteDimensions _sprite_dimensions
Turrent Sprite Dimensions.
const float _rotation_rate
Default value for rotation rate.
Detailed Description
Definition at line 23 of file Turret.h.
Constructor & Destructor Documentation
Turret::Turret (float positionX, float positionY, float rotation)
Constructor.
Definition at line 13 of file Turret.cpp.
References _collidedStatus, _sprite_dimensions, _turret, _type, Orientation::getOriginX(), Orientation::getOriginY(), Orientation::getRotation(), Orientation::setHeight(), Orientation::setWidth(), turret, SpriteDimensions::turret_sprite_x, and SpriteDimensions::turret_sprite_y.
                                                              :
    _rotation(rotation),
    _turret(positionX, positionY, 0, 0,rotation,false),
    _type(turret),
    _sprite_dimensions(),
    _rotation_rate(-2)
{
    //Error input checking
    if (_turret.getOriginX() < 0) throw
      InvalidConstructorArgumentsTurret();
    if (_turret.getOriginY() < 0) throw
      InvalidConstructorArgumentsTurret();
    if (_turret.getRotation() < 0) throw
      InvalidConstructorArgumentsTurret();
    if (_type != turret) throw InvalidConstructorArgumentsTurret
      ();
    _turret.setWidth(_sprite_dimensions.
      turret_sprite_x);
    _turret.setHeight(_sprite_dimensions.
      turret_sprite_y);
    _collidedStatus = 0;
}
Turret::~Turret () [virtual]
Destructor.
Definition at line 106 of file Turret.cpp.
{
    // Can addd some arguments here
}
Member Function Documentation
const rect_corners & Turret::getAlignedBoundingBox () [virtual]
Get Axis Aligned bounding box of entity.
Implements Collidable.
Definition at line 61 of file Turret.cpp.
References _turret, and Orientation::getAlignedGlobalBounds().
{
    return _turret.getAlignedGlobalBounds();
}
const rect_corners & Turret::getBoundingBox () [virtual]
Get bounding box of entity.
Implements Collidable.
Definition at line 56 of file Turret.cpp.
References _turret, and Orientation::getGlobalBounds().
{
    return _turret.getGlobalBounds();
}
const float Turret::getDrawPositionX () [virtual]
Retrieve the entity's x Position.
Implements Deletable.
Definition at line 41 of file Turret.cpp.
References _turret, and Orientation::getOriginX().
{
    return _turret.getOriginX();
}
const float Turret::getDrawPositionY () [virtual]
Retrieve the entity's y Position.
Implements Deletable.
Definition at line 46 of file Turret.cpp.
References _turret, and Orientation::getOriginY().
{
    return _turret.getOriginY();
}
const float Turret::getDrawRotation () [virtual]
Retrieve the entity's Position.
Implements Deletable.
Definition at line 51 of file Turret.cpp.
References _turret, and Orientation::getRotation().
{
    return _turret.getRotation();
}
const float Turret::getOrientation () [virtual]
Get the current orientation of Trackable object.
Implements Trackable.
Definition at line 91 of file Turret.cpp.
References _turret, and Orientation::getRotation().
Referenced by TEST().
{
    return _turret.getRotation();
}
const float Turret::getPositionX () [virtual]
Get the current x co-ordinates of Trackable object.
Implements Trackable.
Definition at line 81 of file Turret.cpp.
References _turret, and Orientation::getOriginX().
{
    return _turret.getOriginX();
}
const float Turret::getPositionY () [virtual]
Get the current y co-ordinates of Trackable object.
Implements Trackable.
Definition at line 86 of file Turret.cpp.
References _turret, and Orientation::getOriginY().
{
    return _turret.getOriginY();
}
const rect_corners & Turret::getTrackingBoundingBox () [virtual]
Get the bounding box relevant for line-of-fire detection.
Implements Trackable.
Definition at line 96 of file Turret.cpp.
References _turret, and Orientation::getGlobalBounds().
{
    return _turret.getGlobalBounds();
}
const entity_type & Turret::getType () const [virtual]
Provide type.
Implements Deletable.
Definition at line 31 of file Turret.cpp.
References _type.
{
    return _type;
}
const bool Turret::isDeleted () [virtual]
Determine the life state of the Turrent.
Implements Deletable.
Definition at line 36 of file Turret.cpp.
References _collidedStatus.
{
    return _collidedStatus;
}
void Turret::rotateTurret ()
Rotates the Turret by its set value.
Definition at line 101 of file Turret.cpp.
References _rotation_rate, _turret, and Orientation::rotate().
Referenced by TEST().
{
    _turret.rotate(_rotation_rate);
}
const int Turret::setBlocked (const blocked_status obstruction_type) [virtual]
Set blocked state of entity.
Implements Collidable.
Definition at line 66 of file Turret.cpp.
{
    return 1;
}
void Turret::setCollided () [virtual]
Set collision state of entity.
Implements Collidable.
Definition at line 76 of file Turret.cpp.
References _collidedStatus.
{
    _collidedStatus = 1;
}
void Turret::setUnblocked () [virtual]
Unset the blocked state of the entity.
Implements Collidable.
Definition at line 71 of file Turret.cpp.
{
    //Do nothing here!
}
Member Data Documentation
bool Turret::_collidedStatus [private]
Collision state of the Turrent Entity: 1 for collided, 0 for not.
Definition at line 65 of file Turret.h.
Referenced by isDeleted(), setCollided(), and Turret().
float Turret::_rotation [private]
The angle of rotation for the Turrnet entity.
Definition at line 67 of file Turret.h.
const float Turret::_rotation_rate [private]
Default value for rotation rate.
Definition at line 75 of file Turret.h.
Referenced by rotateTurret().
SpriteDimensions Turret::_sprite_dimensions [private]
Turrent Sprite Dimensions.
Definition at line 73 of file Turret.h.
Referenced by Turret().
Orientation Turret::_turret [private]
Co-ordinate system for the Turrnet.
Definition at line 69 of file Turret.h.
Referenced by getAlignedBoundingBox(), getBoundingBox(), getDrawPositionX(), getDrawPositionY(), getDrawRotation(), getOrientation(), getPositionX(), getPositionY(), getTrackingBoundingBox(), rotateTurret(), and Turret().
entity_type Turret::_type [private]
Enumeration type defining the turrnet.
Definition at line 71 of file Turret.h.
Referenced by getType(), and Turret().
The documentation for this class was generated from the following files:
Turret.h
Turret.cpp