DestructionManager Class Reference
Manager class responsible for deletions of destroyed game entities.
#include <DestructionManager.h>
Public Member Functions
DestructionManager ()
Constructor for the Destruction manager.
void manage (GameStateData &game_state_container)
Destruction management process for the Destruction Manager.
void addNewEntity (std::shared_ptr< Deletable > new_entity)
Add Deletable-type shared_ptr's to the DestructionManagers internal data members.
virtual ~DestructionManager ()
Destructor for the destruction manager.
Private Attributes
std::vector< std::shared_ptr
*
< Deletable > > _destructables
Detailed Description
Manager class responsible for deletions of destroyed game entities.
Definition at line 21 of file DestructionManager.h.
Constructor & Destructor Documentation
DestructionManager::DestructionManager ()
Constructor for the Destruction manager.
Definition at line 13 of file DestructionManager.cpp.
 {
 }
DestructionManager::~DestructionManager () [virtual]
Destructor for the destruction manager.
Definition at line 52 of file DestructionManager.cpp.
{
    //Possible arguments to be added here
}
Member Function Documentation
void DestructionManager::addNewEntity (std::shared_ptr< Deletable > new_entity)
Add Deletable-type shared_ptr's to the DestructionManagers internal data members.
Parameters
new_entity :: type of new entity that will be addded.
Definition at line 60 of file DestructionManager.cpp.
References _destructables.
Referenced by Game::addNewMine(), Game::addNewMissile(), Game::addNewTank(), Game::addNewTurret(), Game::createBarrier(), main(), and TEST().
{
    _destructables.push_back(new_entity);
}
void DestructionManager::manage (GameStateData & game_state_container)
Destruction management process for the Destruction Manager.
If one of the tanks are destroyed, then opposing player receives an additional point.
Parameters
game_state_container :: cotainer that holds the players' score
Definition at line 22 of file DestructionManager.cpp.
References _destructables, GameStateData::increaseP1Score(), GameStateData::increaseP2Score(), p1_tank, and p2_tank.
Referenced by main(), Game::runAllManagers(), and TEST().
{
    auto i = _destructables.begin();
    for(; i != _destructables.end();)
    {
            std::shared_ptr<Deletable> entity_sp = (*i);
            //The manager checks each entity to see if it has recieved a 'death state'
            if(entity_sp->isDeleted())
            {
                if (entity_sp->getType() == p1_tank)
                {
                    game_state_container.increaseP1Score();
                }
                if (entity_sp->getType() == p2_tank)
                {
                    game_state_container.increaseP2Score();
                }
                _destructables.erase(i);
            }
            else
            {
                i++;
            }
    }
}
Member Data Documentation
std::vector<std::shared_ptr<Deletable> > DestructionManager::_destructables [private]
Definition at line 31 of file DestructionManager.h.
Referenced by addNewEntity(), and manage().
The documentation for this class was generated from the following files:
DestructionManager.h
DestructionManager.cpp